export type HonmanOfficialAnswer = {
  answer: "true" | "false";
  explanation: string;
};

export const honmanTestTwoOfficialAnswers: Record<number, HonmanOfficialAnswer> = {
  1: { answer: "true", explanation: "This sign designates a dedicated path for regular bicycles and pedestrians; other vehicles may not proceed." },
  2: { answer: "true", explanation: "Trailers must use the designated leftmost lane on national expressways with two or more lanes." },
  3: { answer: "false", explanation: "Road and tire friction affects braking distance, not reaction distance." },
  4: { answer: "true", explanation: "Vehicles should not obstruct a local bus signaling that it will re-enter traffic, unless avoiding obstruction would require sudden braking or swerving." },
  5: { answer: "true", explanation: "The diamond markings warn that a pedestrian crossing or bicycle crossing is ahead." },
  6: { answer: "true", explanation: "Looking over and under a stopped vehicle can reveal a person's head or feet before they emerge." },
  7: { answer: "true", explanation: "It is dangerous to reduce speed too much in the main through lane. Reduce speed sufficiently after entering the deceleration lane." },
  8: { answer: "true", explanation: "Leaving the designated lane is permitted when yielding to an emergency vehicle or when road construction makes it unavoidable." },
  9: { answer: "false", explanation: "On mountain roads, the downhill vehicle should generally give way because restarting uphill is more difficult." },
  10: { answer: "false", explanation: "For traffic approaching the officer from the front or back, a lamp held straight up has the meaning of a red light." },
  11: { answer: "true", explanation: "A pedestrian may emerge or a vehicle door may open, so a rider must pass stopped traffic carefully." },
  12: { answer: "false", explanation: "This warning sign means that traffic signals are ahead; it is not limited to push-button signals." },
  13: { answer: "true", explanation: "A rider should choose a two-wheeled vehicle suited to their body size and begin with a manageable model." },
  14: { answer: "true", explanation: "Large vehicles have significant off-tracking and a left-rear blind spot, creating danger for pedestrians and cyclists." },
  15: { answer: "false", explanation: "The cloth attached to the center of a towing rope must be white, not red." },
  16: { answer: "false", explanation: "Headlights should also be dipped when following another vehicle so they do not dazzle its driver." },
  17: { answer: "false", explanation: "Heavy cargo increases inertia and therefore increases braking distance." },
  18: { answer: "false", explanation: "Parking is allowed only when at least six meters of open road remains to the right of the parked vehicle." },
  19: { answer: "true", explanation: "A public road must not be appropriated as a personal parking place." },
  20: { answer: "false", explanation: "Reversing on the main through lanes of an expressway is prohibited, regardless of distance." },
  21: { answer: "true", explanation: "Poor visibility is the primary danger in fog or snow, so drivers should use lights early, reduce speed, and use available visual guides." },
  22: { answer: "true", explanation: "The buses-only restriction applies from 7:00 a.m. to 9:00 a.m.; regular motor vehicles may use the lane at 8:00 p.m." },
  23: { answer: "true", explanation: "A general moped should keep signaling while proceeding straight to the point where it completes the second stage of the right turn." },
  24: { answer: "false", explanation: "A two-wheeled vehicle's chain requires the proper amount of slack; it must not be completely tight." },
  25: { answer: "true", explanation: "A vehicle may enter this type of side strip to park or stop only when at least 0.75 meters remains on its left." },
  26: { answer: "false", explanation: "Vehicle ② may overtake vehicle ① when it is safe because the road shown has right of way." },
  27: { answer: "false", explanation: "It is generally safer and easier to follow the ruts made by previous vehicles on a snow-covered road." },
  28: { answer: "false", explanation: "Brake effectiveness and engine performance are also checked during driving." },
  29: { answer: "true", explanation: "A travel plan should leave enough leeway because haste and strain reduce attention and encourage excessive speed." },
  30: { answer: "false", explanation: "Specified small mopeds and light vehicles may also turn left when this signboard permits a left turn." },
  31: { answer: "true", explanation: "Drivers should try to train their eyes on a point as far away as possible to detect potential danger as soon as possible." },
  32: { answer: "true", explanation: "Cargo on a regular truck may extend to a total length of up to 1.2 times the vehicle's length." },
  33: { answer: "true", explanation: "Using the parking brake when starting uphill helps prevent the vehicle from rolling backward." },
  34: { answer: "true", explanation: "The driver is responsible for ensuring that passengers do not open doors carelessly." },
  35: { answer: "false", explanation: "A vehicle must stop immediately before crossing a sidewalk or side strip even when no pedestrians are present." },
  36: { answer: "true", explanation: "As speed increases, a driver's field of vision narrows and close objects become more difficult to see." },
  37: { answer: "false", explanation: "The marking prohibits changing from lane B into lane A; changing from lane A into lane B is permitted." },
  38: { answer: "true", explanation: "Overtaking is prohibited on steep downward slopes, while steep upward slopes are not included in that prohibition." },
  39: { answer: "true", explanation: "A driver should signal a left or right turn 30 meters before the point where the turn will be made." },
  40: { answer: "true", explanation: "The engine oil level must remain between the F and L marks so that it is neither too high nor too low." },
  41: { answer: "true", explanation: "Using a phone or viewing a navigation screen while driving delays the driver's response to danger and can cause an accident." },
  42: { answer: "false", explanation: "The vehicle must stop and yield; it must not make a pedestrian stop because the pedestrian senses danger." },
  43: { answer: "false", explanation: "A driver moving from the road edge into traffic must signal the lane change even after checking behind." },
  44: { answer: "false", explanation: "A driver must maintain safe side clearance from the vehicle being overtaken." },
  45: { answer: "false", explanation: "A vehicle with dangerously malfunctioning steering or brakes must not be driven until it is repaired." },
  46: { answer: "false", explanation: "Vehicles must stop and check for safety at a railway crossing even when visibility is good." },
  47: { answer: "true", explanation: "A general moped must obey its statutory maximum speed of 30 km/h even when the posted limit is 50 km/h." },
  48: { answer: "true", explanation: "A general moped may carry only its driver; riding with a passenger is prohibited." },
  49: { answer: "true", explanation: "Drivers must slow down or stop so that vulnerable pedestrians can pass safely." },
  50: { answer: "false", explanation: "Light vehicles may also proceed in the direction of a green left arrow." },
  51: { answer: "false", explanation: "A right-turning automobile should follow the guide marking and slow down inside the center of the intersection." },
  52: { answer: "true", explanation: "The double-overtaking prohibition does not apply when the first vehicle is overtaking a general moped." },
  53: { answer: "true", explanation: "Vehicles should remain in the same lane whenever possible to maintain safe and smooth traffic flow." },
  54: { answer: "false", explanation: "An automatic-transmission vehicle cannot be moved using the starter motor in this way." },
  55: { answer: "true", explanation: "Main through lanes are the expressway lanes used for normal high-speed travel and overtaking, excluding the listed auxiliary areas." },
  56: { answer: "true", explanation: "Rain gear and attention to footing can prevent pedestrians from noticing vehicles, so drivers must watch them carefully." },
  57: { answer: "true", explanation: "A driver must slow down and, when necessary, stop to avoid obstructing traffic on a priority or wider cross street." },
  58: { answer: "false", explanation: "The sign permits automobiles generally, not only regular motor vehicles, to drive on streetcar tracks." },
  59: { answer: "false", explanation: "Parking within three meters of a garage entrance is prohibited even for the owner or related persons." },
  60: { answer: "true", explanation: "Bright clothing and a highly visible helmet help protect riders who might otherwise be overlooked." },
  61: { answer: "false", explanation: "Regular motorcycles with an engine displacement of 125 cc or less are also prohibited from proceeding." },
  62: { answer: "false", explanation: "When streetcar rails are in the center of the road, the streetcar must be overtaken on the left." },
  63: { answer: "false", explanation: "The ordinary renewal period begins one month, not two months, before the relevant birthday." },
  64: { answer: "true", explanation: "Vehicle A may not cross to the right in order to overtake vehicle B unless the width is less than 6 meters, such as 5.9 meters or less." },
  65: { answer: "false", explanation: "The maximum speed on motorways is the same as on general roads when no maximum speed limit is indicated." },
  66: { answer: "false", explanation: "Passing as well as overtaking is prohibited at a pedestrian or bicycle crossing and within 30 meters before it." },
  67: { answer: "true", explanation: "The illustrated left-hand signals indicate slowing down or stopping." },
  68: { answer: "true", explanation: "The brake does not function well and it is dangerous when there is little space between the pedal and the floorboard." },
  69: { answer: "true", explanation: "A person who is extremely tired, unwell, or mentally uneasy should not drive because concentration is impaired." },
  70: { answer: "true", explanation: "A solid yellow centerline may not be crossed for overtaking even when the left side of the road is less than six meters wide." },
  71: { answer: "false", explanation: "Cargo must not obstruct direction indicators, lamps, or the license plate, even when an observer rides along." },
  72: { answer: "true", explanation: "Only the slow-down and stop signs use this distinctive inverted-triangle shape." },
  73: { answer: "true", explanation: "Stopping and parking are prohibited within a railway crossing and within ten meters of either edge." },
  74: { answer: "false", explanation: "General mopeds must also be covered by compulsory automobile liability or mutual relief insurance." },
  75: { answer: "true", explanation: "A vehicle parked or stopped on an unlit road at night must be made conspicuous with the specified lights or a warning reflector." },
  76: { answer: "true", explanation: "Slow before entering a curve, then accelerate gradually near its end for safe and stable cornering." },
  77: { answer: "false", explanation: "A prohibition on crossing and U-turns does not itself prohibit driving in reverse." },
  78: { answer: "true", explanation: "The maximum speed limit for regular motor vehicles is 100 km/h, excluding three-wheeled vehicles and towing vehicles." },
  79: { answer: "true", explanation: "Passing too close to or cutting in front of a vehicle displaying a novice, senior, or disabled-driver sign is prohibited, but there are no such regulations relating to a learner-driver sign." },
  80: { answer: "false", explanation: "If a driver stares at the lights, he or she will be dazzled and blinded. It is advisable to move one's gaze to the left ahead." },
  81: { answer: "true", explanation: "Drivers should wear clothing that reduces exposure of their skin even in the heat of summer in order to minimize injuries in case they fall off the vehicle." },
  82: { answer: "true", explanation: "For traffic approaching the officer from the front or back, horizontally outstretched arms have the meaning of a red light." },
  83: { answer: "false", explanation: "The triangular sign designates a bicycle crossing, not a bicycle path or dedicated bicycle road." },
  84: { answer: "true", explanation: "Carbon monoxide, hydrocarbons, and nitrogen oxides in automotive emissions contribute to air pollution." },
  85: { answer: "false", explanation: "On a long or steep downhill slope, an automatic vehicle may need L or 2 to provide effective engine braking." },
  86: { answer: "false", explanation: "A maximum speed is a limit, not a required speed; drivers must reduce speed when weather or conditions make that safer." },
  87: { answer: "true", explanation: "The impact at 60 km/h is approximately equivalent to a fall from 14 meters, based on the physical relationship between speed and energy." },
  88: { answer: "true", explanation: "After an earthquake, an abandoned vehicle should be left unlocked and ready to be moved if it obstructs emergency traffic." },
  89: { answer: "true", explanation: "Drivers must slow at a poorly visible uncontrolled intersection and should stop when traffic conditions require it." },
  90: { answer: "true", explanation: "A broken-down vehicle on an expressway must be made highly visible with a rear warning reflector and, in darkness or poor visibility, the specified lights." },
};

export const honmanTestOneOfficialAnswers: Record<number, HonmanOfficialAnswer> = {
  1: { answer: "false", explanation: "New drivers licensed for less than one year are required to display the novice driver sign regardless of their confidence." },
  2: { answer: "false", explanation: "Drivers should mainly use engine braking and apply the foot brake as an auxiliary." },
  3: { answer: "true", explanation: "Park the car in a place where it does not impede the progress of other vehicles." },
  4: { answer: "true", explanation: "Drivers should consider pedestrians while driving." },
  5: { answer: "true", explanation: "This marking designates a no-stopping zone where vehicles must not stop." },
  6: { answer: "true", explanation: "It is a crime to permit driving when intoxicated." },
  7: { answer: "true", explanation: "This amount of distance between vehicles is required when considering stopping distance." },
  8: { answer: "true", explanation: "On multilane roads, general mopeds in principle use the two-step right-turn method for safety." },
  9: { answer: "false", explanation: "Vehicles may proceed at a low speed when passing a safety zone." },
  10: { answer: "true", explanation: "The designated vehicles must travel in the leftmost lane in principle." },
  11: { answer: "false", explanation: "The use of a child seat is required in the rear seat as well." },
  12: { answer: "true", explanation: "This is a law of physics. Drivers must be fully aware of it when driving on a curved road." },
  13: { answer: "false", explanation: "Drivers should give way to the overtaking vehicle by moving over to the left as much as possible." },
  14: { answer: "false", explanation: "Drivers should slow down before the curve and accelerate at the end of the curve." },
  15: { answer: "true", explanation: "A lower speed would result in less damage and increase the possibility of avoiding the collision." },
  16: { answer: "false", explanation: "The driver of a four-wheeled vehicle might overlook a two-wheeled vehicle." },
  17: { answer: "false", explanation: "Only vehicles with a total above-ground height of up to 3.3 meters may proceed." },
  18: { answer: "false", explanation: "Neither parking nor stopping a vehicle is allowed in tunnels with or without vehicular lanes." },
  19: { answer: "true", explanation: "Drivers must fully understand the characteristics of elderly people and children and prepare for unexpected behavior." },
  20: { answer: "true", explanation: "To avoid traffic accidents, clearly indicate that the vehicle has broken down." },
  21: { answer: "false", explanation: "Hazard lights, parking lights or tail lamps are not necessary when an emergency reflector device is positioned." },
  22: { answer: "true", explanation: "The vehicle owner should be responsible for automobile use." },
  23: { answer: "true", explanation: "In a no-overtaking zone, vehicles must not change lanes in order to overtake automobiles or mopeds." },
  24: { answer: "true", explanation: "The specified hand signal for reversing is an arm movement." },
  25: { answer: "true", explanation: "Drivers should allow more distance between vehicles, taking gravity and acceleration into consideration." },
  26: { answer: "true", explanation: "This is a characteristic of automatic-transmission vehicles. Be sure to apply the brakes while the vehicle is stopped." },
  27: { answer: "false", explanation: "Overtaking or passing is not prohibited, but one must not pass too closely or cut in front of the vehicle." },
  28: { answer: "false", explanation: "The meaning of the police officer’s hand signal is the same as a red light, but not the same as the arrow signal." },
  29: { answer: "false", explanation: "The driver is included in the seating capacity." },
  30: { answer: "false", explanation: "The side strip or shoulder of an expressway must not be used as a resting place." },
  31: { answer: "false", explanation: "The sign designates a bicycle path or a dedicated road for bicycles." },
  32: { answer: "false", explanation: "Cargo may be loaded on the seats unless it obstructs driving." },
  33: { answer: "true", explanation: "Many traffic accidents occur at intersections. Careful attention is necessary when proceeding through intersections." },
  34: { answer: "true", explanation: "Those who are unaware of their responsibilities in potential accidents are not qualified as drivers." },
  35: { answer: "true", explanation: "This is permitted as an exception to the general left-side rule." },
  36: { answer: "true", explanation: "Traffic signs and pavement markings communicate speed, how to proceed and other details clearly." },
  37: { answer: "true", explanation: "Sudden braking during high-speed driving is dangerous because the vehicle may lose control." },
  38: { answer: "false", explanation: "Light vehicles may not proceed because it is a side strip for pedestrians." },
  39: { answer: "true", explanation: "Drivers of two-wheeled vehicles should try to widen their field of vision." },
  40: { answer: "true", explanation: "This constitutes driving without a valid license because the suspended license is temporarily invalid." },
  41: { answer: "false", explanation: "One should move his or her gaze slightly to the left so as not to be dazzled by the lights." },
  42: { answer: "false", explanation: "One should avoid moving too close to the vehicle ahead and change lanes slowly." },
  43: { answer: "false", explanation: "It is permissible to cross the road when executing a left turn in order to enter or leave a location facing the left side." },
  44: { answer: "false", explanation: "Slouching too far forward is dangerous because the viewing field becomes narrow." },
  45: { answer: "true", explanation: "Confirmation is necessary when proceeding through a multilane railway crossing." },
  46: { answer: "false", explanation: "The driver must proceed as the traffic sign designates, on the left side." },
  47: { answer: "false", explanation: "Wave-shaped ripples on the tire are called the standing-wave phenomenon." },
  48: { answer: "true", explanation: "Both slowing down and stopping use the same signal, with the arm extending diagonally downward from the vehicle." },
  49: { answer: "false", explanation: "The steering wheel will pull to the right because it is pulled toward the side with lower tire pressure." },
  50: { answer: "true", explanation: "Considering the influence of fatigue, driving for two consecutive hours or longer should be avoided." },
  51: { answer: "false", explanation: "Vehicles approaching from the left have right of way, so vehicle B may not obstruct the progress of vehicle A." },
  52: { answer: "false", explanation: "Drivers should avoid approaching the shoulder because it becomes loose and might crumble on a rainy day." },
  53: { answer: "false", explanation: "Parking is prohibited within 1 meter of a fire alarm." },
  54: { answer: "false", explanation: "Automobiles must approach the center of the road when not driving on a one-way street." },
  55: { answer: "false", explanation: "Vehicles must stop. Slowing down is not an option." },
  56: { answer: "true", explanation: "The sign shows that the road is closed to passenger vehicles with a capacity of 11 passengers or more." },
  57: { answer: "true", explanation: "Drivers may park while loading or unloading cargo when the driver is immediately available to drive." },
  58: { answer: "false", explanation: "The personal parking place must be within 2 kilometers." },
  59: { answer: "true", explanation: "As dangerous overtaking is prohibited, giving up the attempt to overtake is right for safety reasons." },
  60: { answer: "true", explanation: "This warning sign indicates a danger of animals appearing suddenly on the road." },
  61: { answer: "true", explanation: "One should not put up with drowsiness, but should relieve it before resuming driving." },
  62: { answer: "false", explanation: "General mopeds may not proceed either." },
  63: { answer: "true", explanation: "It is safer to leave the vehicle and wait somewhere else because a parked vehicle may be struck." },
  64: { answer: "true", explanation: "The signboard indicates that the signal is provided for the smooth flow of bus traffic." },
  65: { answer: "true", explanation: "The horn may be used when needed to avoid danger." },
  66: { answer: "true", explanation: "Reaction distance is unrelated to worn tires because the brakes do not begin operating during reaction distance." },
  67: { answer: "false", explanation: "A permit must be obtained because the total length extends more than one-tenth of the vehicle’s length behind the automobile." },
  68: { answer: "false", explanation: "The sticker indicates the next inspection timing by year and month." },
  69: { answer: "true", explanation: "Fatigue and its effects are most evident in the eyes because of their heavy use while driving." },
  70: { answer: "true", explanation: "Headlights both maintain the range of vision and warn other drivers of the vehicle’s presence." },
  71: { answer: "false", explanation: "Vehicles executing right turns must not obstruct oncoming vehicles proceeding straight or turning left." },
  72: { answer: "false", explanation: "Vehicles should stop immediately before the intersection, not immediately before the traffic signal." },
  73: { answer: "false", explanation: "Vehicles that cannot satisfy the minimum speed limit are allowed to use the slower traffic lane." },
  74: { answer: "true", explanation: "This sign designates motor vehicles only and is placed on a national expressway or motorway." },
  75: { answer: "true", explanation: "Kinetic energy at collision is proportional to the square of speed; one-half times one-half equals one-quarter." },
  76: { answer: "false", explanation: "There should be room to pull the hand brake further; otherwise, the brake may not operate well." },
  77: { answer: "false", explanation: "This sign warns of falling rocks." },
  78: { answer: "true", explanation: "Drivers should account for reaction time so they can respond safely when danger arises." },
  79: { answer: "true", explanation: "Corners are dangerous locations where drivers must not overtake and must slow down." },
  80: { answer: "true", explanation: "At an intersection, vehicles must let an emergency vehicle proceed in any direction." },
  81: { answer: "false", explanation: "The documents must be kept in the vehicle while driving." },
  82: { answer: "true", explanation: "A two-wheeled vehicle tends to be overlooked in the blind spot of a four-wheeled vehicle’s rearview mirror." },
  83: { answer: "true", explanation: "Sudden maneuvers are dangerous and should be avoided, particularly on bad road surfaces." },
  84: { answer: "false", explanation: "Vehicle A does not have to slow down because it has the right of way." },
  85: { answer: "false", explanation: "Coolant or oil leakage is a mechanical breakdown that requires repair." },
  86: { answer: "false", explanation: "Automobiles and mopeds may not enter the side strip or sidewalk." },
  87: { answer: "true", explanation: "One should respect traffic conditions and drive in an orderly manner." },
  88: { answer: "true", explanation: "The distance and speed of two-wheeled vehicles tend to be misjudged because they are small." },
  89: { answer: "true", explanation: "Driving at a lower speed is necessary because the area illuminated by headlights is limited." },
  90: { answer: "true", explanation: "When entering a roadside garage, consider other traffic and the safety of pulling out the next time." },
};

export const honmanTestThreeOfficialAnswers: Record<number, HonmanOfficialAnswer> = {
  1: { answer: "false", explanation: "Centrifugal force is proportional to the square of speed, so tripling speed increases it nine times." },
  2: { answer: "false", explanation: "The left auxiliary sign indicates the start of a regulation, while the middle and right signs indicate its end." },
  3: { answer: "true", explanation: "Long high-speed driving can dull speed perception, so drivers should check the speedometer regularly." },
  4: { answer: "false", explanation: "A large vehicle license does not authorize the holder to drive special heavy equipment." },
  5: { answer: "true", explanation: "Frequent braking on long descents can cause vapor lock, so engine braking should be used appropriately." },
  6: { answer: "true", explanation: "The marking indicates the end of the traffic regulation, here the end of a no U-turn zone." },
  7: { answer: "false", explanation: "Every driver must stop and check for safety before entering a railway crossing, even when following another vehicle." },
  8: { answer: "true", explanation: "A wet road and worn tires can increase stopping distance to about twice the normal distance." },
  9: { answer: "false", explanation: "When turning right from a one-way street, a driver should first approach the right edge of the road." },
  10: { answer: "true", explanation: "The illustrated side strip is for pedestrians, so bicycles may not use it." },
  11: { answer: "false", explanation: "Because two-wheeled vehicles are small, drivers often perceive them as farther away and slower than they really are." },
  12: { answer: "true", explanation: "Drivers are responsible for taking precautions to avoid splashing pedestrians with mud or water." },
  13: { answer: "false", explanation: "The person steering the towed vehicle must hold a license valid for that type of vehicle." },
  14: { answer: "true", explanation: "Overtaking is dangerous and should not begin if the driver has any uncertainty." },
  15: { answer: "false", explanation: "Regular vehicles should not use a bus-only lane in heavy traffic because they may be unable to leave when a bus approaches." },
  16: { answer: "false", explanation: "A vehicle may cross a yellow lane line when necessary to yield to an approaching emergency vehicle." },
  17: { answer: "false", explanation: "The regular motor vehicle is on the wider road and has priority over the streetcar in the illustrated situation." },
  18: { answer: "false", explanation: "Battery fluid decreases through natural evaporation and its level must be checked." },
  19: { answer: "true", explanation: "The driver should check around and under the vehicle before entering because these areas become blind spots from the driver's seat." },
  20: { answer: "false", explanation: "Overtaking in a tunnel is prohibited only when the tunnel has no vehicular lanes." },
  21: { answer: "false", explanation: "During business hours, stopping or parking within ten meters of a bus or streetcar stop marker is prohibited even for boarding passengers." },
  22: { answer: "true", explanation: "A hydraulic brake pedal that sinks under steady pressure can indicate a dangerous brake-fluid leak." },
  23: { answer: "true", explanation: "Cargo should be kept low and evenly distributed so the vehicle's center of gravity remains stable." },
  24: { answer: "false", explanation: "The 3.8-meter cargo-height limit is measured from the ground, not from the cargo bed." },
  25: { answer: "true", explanation: "Overtaking is prohibited at and within 30 meters before the listed intersections and crossings because these locations are especially dangerous." },
  26: { answer: "true", explanation: "The sign permits time-limited parking for up to 60 minutes between 8:00 and 20:00." },
  27: { answer: "true", explanation: "A signal should be canceled immediately after the indicated maneuver is complete." },
  28: { answer: "true", explanation: "On a road with marked lanes, overtaking should use the lane immediately to the right." },
  29: { answer: "true", explanation: "After a puncture, hold the steering steady, ease off the accelerator, slow gradually, and brake gently." },
  30: { answer: "true", explanation: "For vehicles facing them, the road-closed and no-entry signs both prohibit proceeding." },
  31: { answer: "true", explanation: "Drivers should check medication effects and must avoid driving after taking medicine that causes drowsiness." },
  32: { answer: "false", explanation: "Expressway driving causes eye strain and psychological fatigue; resting only once every four hours is insufficient." },
  33: { answer: "false", explanation: "In poor visibility, maintain a greater safe following distance and watch the vehicle ahead's brake lights." },
  34: { answer: "true", explanation: "The diamond markings warn of a pedestrian or bicycle crossing ahead, so drivers should not accelerate or overtake." },
  35: { answer: "true", explanation: "Brake lights and other signals communicate an intention to slow down or stop." },
  36: { answer: "false", explanation: "A broken-down vehicle stopped on an expressway must have an emergency warning reflector behind it, even during the day." },
  37: { answer: "false", explanation: "When signal A is green, the right-turning driver does not need to wait for signal B to turn green." },
  38: { answer: "false", explanation: "Drivers should wear clothing that does not interfere with safe vehicle control." },
  39: { answer: "true", explanation: "Rain can increase braking distance and fatigue can increase reaction distance, so a longer following distance is necessary." },
  40: { answer: "true", explanation: "Drivers of four-wheeled vehicles tend to overlook smaller two-wheeled vehicles." },
  41: { answer: "true", explanation: "Signal at least three seconds before changing lanes, then move gradually while accelerating." },
  42: { answer: "false", explanation: "A vehicle being overtaken must generally be passed on its right side." },
  43: { answer: "false", explanation: "Drivers should reduce speed at night because pedestrians and bicycles are detected later." },
  44: { answer: "true", explanation: "Seating and loading limits exist to preserve safe handling and stability; exceeding them can cause accidents." },
  45: { answer: "false", explanation: "Optional insurance helps prepare for accidents and should not be avoided on the theory that it causes complacency." },
  46: { answer: "true", explanation: "At a two-lane-each-way intersection without a special sign, a general moped uses the same right-turn method as an automobile." },
  47: { answer: "true", explanation: "Three children under 12 count as two adults, so the stated occupants remain within the five-person capacity." },
  48: { answer: "true", explanation: "Drivers should anticipate that children may become distracted and suddenly run into the road." },
  49: { answer: "false", explanation: "If the rear wheels slide right, steer right—toward the direction of the slide." },
  50: { answer: "true", explanation: "This mandatory-direction sign requires vehicles to turn left; straight travel and right turns are prohibited." },
  51: { answer: "false", explanation: "Parking and stopping are also prohibited on a steep uphill slope." },
  52: { answer: "true", explanation: "A vehicle with a defective muffler, excessive noise, or excessive smoke must not be driven." },
  53: { answer: "true", explanation: "When indicator lights are difficult to see, a corresponding hand signal helps make the driver's intention clear." },
  54: { answer: "false", explanation: "Vehicle A is on the priority main lane; merging vehicle B must not obstruct vehicle A." },
  55: { answer: "true", explanation: "Tire checks should cover pressure, tread, cracks, damage, embedded objects, and abnormal wear." },
  56: { answer: "true", explanation: "High engine speed after starting or while using air conditioning can cause sudden starts in automatic vehicles." },
  57: { answer: "true", explanation: "A driver immobilized on a railway crossing must warn the train immediately and then move the vehicle out promptly." },
  58: { answer: "true", explanation: "A vehicle must stop before crossing a sidewalk or side strip whether or not pedestrians are visible." },
  59: { answer: "false", explanation: "A novice-driver sign must be displayed on both the front and rear of the vehicle." },
  60: { answer: "false", explanation: "The vehicle on the dangerous cliff side should stop first and let the oncoming vehicle pass." },
  61: { answer: "true", explanation: "A solid yellow centerline has the same prohibition whether single or double; neither vehicle may cross it to overtake." },
  62: { answer: "true", explanation: "The maximum speed on general roads is 60 km/h for both large passenger vehicles and large trucks." },
  63: { answer: "false", explanation: "When police or traffic-warden signals conflict with a traffic light, drivers must obey the officer's signal." },
  64: { answer: "true", explanation: "Safe driving requires understanding one's personality and habits and compensating for them." },
  65: { answer: "true", explanation: "The marking permits entering the right side on the sharp curve, but drivers must anticipate oncoming traffic and avoid a head-on collision." },
  66: { answer: "false", explanation: "A driver need not slow past a safety zone unless pedestrians are present." },
  67: { answer: "true", explanation: "A sudden maneuver by a truck farther ahead can warn of an unseen hazard." },
  68: { answer: "false", explanation: "Every traffic accident must be reported to police, even if injuries are slight or the drivers agree privately." },
  69: { answer: "true", explanation: "At night or in poor visibility, high beams or flashing headlights can warn unseen road users of the vehicle's approach." },
  70: { answer: "true", explanation: "At a three-lane-each-way intersection, a general moped must use the two-step right turn and may not follow the green right arrow." },
  71: { answer: "true", explanation: "Underinflated tires at high speed can develop a standing wave and burst, so slightly higher specified high-speed pressure is appropriate." },
  72: { answer: "true", explanation: "The auxiliary marking indicates the end of a no-parking zone, so parking is allowed beyond the sign." },
  73: { answer: "false", explanation: "Vision also deteriorates from glare when moving suddenly from a dark place into a bright one." },
  74: { answer: "true", explanation: "On a one-way road away from an intersection, moving right is permitted when moving left would obstruct an emergency vehicle." },
  75: { answer: "true", explanation: "At night, the tail and brake lights of vehicles ahead provide important information about traffic conditions." },
  76: { answer: "false", explanation: "Only designated vehicles or vehicles with police-chief permission may use a road bearing this sign." },
  77: { answer: "true", explanation: "On mountain curves, drivers should anticipate that an oncoming vehicle may cross the centerline." },
  78: { answer: "true", explanation: "After a crash, preventing secondary collisions includes moving the vehicle safely out of traffic and switching off the engine." },
  79: { answer: "true", explanation: "Group driving must not include zigzagging, cutting in, or behavior that endangers or disturbs others." },
  80: { answer: "false", explanation: "Riding with a passenger requires additional coordinated movements and precautions compared with riding alone." },
  81: { answer: "true", explanation: "A two-wheeled vehicle requires body-based balance while moving and stability when stopped." },
  82: { answer: "true", explanation: "Even with chains or snow tires, drivers must leave extra distance, reduce speed, and avoid abrupt braking or steering." },
  83: { answer: "false", explanation: "A driver must stop before the pedestrian crossing when another vehicle is stopped there, not merely slow down." },
  84: { answer: "true", explanation: "The expressway main-lane maximum for large trucks and specified medium trucks is 90 km/h." },
  85: { answer: "false", explanation: "A rider should press the knees against the fuel tank and point the toes forward." },
  86: { answer: "true", explanation: "Wet steel plates are extremely slippery, so drivers should reduce speed before reaching them." },
  87: { answer: "true", explanation: "Drivers must avoid unnecessary noise and consider people living alongside the road." },
  88: { answer: "true", explanation: "Keeping the motorcycle upright and applying both brakes with engine braking reduces sliding or flipping risk." },
  89: { answer: "true", explanation: "A left-turn-permitted sign allows a careful left turn even when the signal is red or yellow." },
  90: { answer: "false", explanation: "The marking warns that traffic on the upcoming cross street has priority, not traffic on the driver's current street." },
};

export const honmanTestFourOfficialAnswers: Record<number, HonmanOfficialAnswer> = {
  1: { answer: "false", explanation: "A driver should begin signaling three seconds before changing lanes, not 30 meters before." },
  2: { answer: "true", explanation: "The yellow sidewalk-edge marking prohibits parking but permits a brief stop to let passengers out." },
  3: { answer: "true", explanation: "A first-class license holder may return a taxi or chauffeured vehicle when no passengers are carried." },
  4: { answer: "true", explanation: "For a regular truck of 660 cc or less, the permitted loaded height is up to 2.5 meters above the ground." },
  5: { answer: "false", explanation: "Use the front brake more strongly on a dry surface and the rear brake more strongly on a slippery surface." },
  6: { answer: "false", explanation: "The marking prohibits parking and stopping on the side strip, but specified small mopeds and light vehicles may proceed there." },
  7: { answer: "false", explanation: "A two-wheeled vehicle may be pushed on a sidewalk or crossing only with its engine switched off." },
  8: { answer: "true", explanation: "A motorcycle should move gradually into the right-turn lane well before the intersection." },
  9: { answer: "true", explanation: "A thorough pre-trip inspection helps prevent dangerous breakdown stops on an expressway." },
  10: { answer: "false", explanation: "Both the maximum-speed sign and the no-stopping-zone marking are regulatory, not designation, controls." },
  11: { answer: "true", explanation: "Before starting an automatic vehicle, apply the handbrake, select P, and depress the brake pedal." },
  12: { answer: "true", explanation: "The sign prohibits entering the right side of the road for overtaking; overtaking without crossing right remains permitted." },
  13: { answer: "false", explanation: "The person who lends a vehicle may also be held responsible for an accident." },
  14: { answer: "false", explanation: "Overtaking is prohibited at and within 30 meters before a pedestrian or bicycle crossing, but not after it." },
  15: { answer: "false", explanation: "Drivers may leave the designated lane when necessary to yield to an approaching emergency vehicle." },
  16: { answer: "false", explanation: "A driver must stop behind the streetcar unless there is at least 1.5 meters of clearance to pass safely." },
  17: { answer: "true", explanation: "Selecting reverse activates reversing lights and communicates the intention to reverse." },
  18: { answer: "true", explanation: "For traffic toward the officer's front or back, both arms raised vertically have the meaning of a red light." },
  19: { answer: "true", explanation: "A suitable manual vehicle may be moved with the starter in low gear as an emergency measure after warning trains." },
  20: { answer: "true", explanation: "The sign identifies the centerline, whose physical position may vary across the road or by time of day." },
  21: { answer: "true", explanation: "After a crash, the driver must stop, aid injured people, and prevent secondary accidents." },
  22: { answer: "true", explanation: "Carrying a passenger on a regular motorcycle is prohibited during the rider's first licensed year." },
  23: { answer: "false", explanation: "For seating-capacity calculations, three children under 12 count as two adults." },
  24: { answer: "true", explanation: "Because driving information is obtained primarily by observation, vision is the most important driving sense." },
  25: { answer: "true", explanation: "Away from an intersection, moving left to yield to an emergency vehicle does not always require a complete stop." },
  26: { answer: "false", explanation: "The general moped is on the wider priority road and may proceed before the regular motor vehicle." },
  27: { answer: "false", explanation: "Engine braking is stronger in lower gears." },
  28: { answer: "true", explanation: "Road and tire conditions affect friction and therefore braking and stopping distance." },
  29: { answer: "false", explanation: "The handbrake may still help when the foot brake fails on a downhill slope." },
  30: { answer: "true", explanation: "Drivers must always account for both reaction and braking distance because a vehicle cannot stop instantly." },
  31: { answer: "false", explanation: "At night, the specified lights must be used in addition to the emergency warning reflector." },
  32: { answer: "true", explanation: "Even authorized vehicles must slow down on a pedestrian-only road regardless of whether pedestrians are visible." },
  33: { answer: "true", explanation: "Stopping and parking are prohibited beside a safety zone and within ten meters of its front or rear." },
  34: { answer: "false", explanation: "The marking designates a bicycle crossing, not an exclusive bicycle lane." },
  35: { answer: "false", explanation: "Forcefully reapplying the brakes during a skid is dangerous and can make the skid worse." },
  36: { answer: "false", explanation: "The vehicle with an obstacle on its side must yield to oncoming traffic whose path is clear." },
  37: { answer: "true", explanation: "On a long descent, use L or 2; relying on the foot brake in D can overheat the brakes and cause vapor lock." },
  38: { answer: "false", explanation: "Use the solid white line on the left as a guide and travel slightly left of the lane center." },
  39: { answer: "false", explanation: "A yellow arrow signal applies only to streetcars; automobiles may not proceed on it." },
  40: { answer: "true", explanation: "Two-wheeled vehicles must anticipate that an overlooked four-wheeled vehicle may turn left across their path." },
  41: { answer: "true", explanation: "Throwing objects or extending people or objects outside a moving vehicle is prohibited." },
  42: { answer: "true", explanation: "Unnecessary noise, abrupt starts or acceleration, and racing the engine are prohibited." },
  43: { answer: "true", explanation: "The described right-arm and bent left-arm gestures are valid hand signals for a right turn." },
  44: { answer: "false", explanation: "Overtaking a vehicle that is itself overtaking another automobile is prohibited double overtaking." },
  45: { answer: "false", explanation: "A driver must stop before entering a congested pedestrian or bicycle crossing and leave it clear." },
  46: { answer: "true", explanation: "Strong side winds at expressway tunnel or cutting exits can pull the steering, so reduce speed and grip firmly." },
  47: { answer: "false", explanation: "At night, drivers must keep a sufficient following distance rather than moving closer to the vehicle ahead." },
  48: { answer: "true", explanation: "Within a horn-sounding zone, the horn must be used at poorly visible hilltops, curves, and intersections." },
  49: { answer: "false", explanation: "Drivers must follow lane-use rules and should not select lanes merely according to traffic volume." },
  50: { answer: "true", explanation: "Cutting in may be unavoidable when necessary to prevent a head-on collision." },
  51: { answer: "false", explanation: "The restriction applies to total vehicle weight exceeding 5,500 kg, not cargo weight alone." },
  52: { answer: "false", explanation: "Daily checks also include assessing engine operation at low and high speeds while driving." },
  53: { answer: "true", explanation: "After overtaking, wait until the passed vehicle is visible in the mirror before safely returning left." },
  54: { answer: "true", explanation: "Correct posture reduces fatigue and preserves reliable steering and pedal control." },
  55: { answer: "true", explanation: "All three illustrated pavement markings indicate right-turn paths through an intersection." },
  56: { answer: "false", explanation: "Three-wheeled regular vehicles and towing vehicles have an 80 km/h maximum, not 100 km/h." },
  57: { answer: "true", explanation: "Stop, check both directions and the exit space, and do not enter a railway crossing if traffic may trap the vehicle inside." },
  58: { answer: "true", explanation: "A spongy hydraulic brake pedal indicates air in the system and poor braking effectiveness." },
  59: { answer: "false", explanation: "A driver must slow down for children near a stopped school bus, but a complete stop is not required." },
  60: { answer: "true", explanation: "The minimum essential observer may ride in the cargo bed without police-chief permission." },
  61: { answer: "false", explanation: "The illustrated side strip prohibits parking and stopping, so a vehicle may not enter it even with 0.75 meters remaining." },
  62: { answer: "true", explanation: "A traffic accident creates financial, legal, and psychological burdens for the driver and family." },
  63: { answer: "true", explanation: "On an unsigned general road, automobiles have a 60 km/h maximum regardless of engine displacement." },
  64: { answer: "true", explanation: "A steep downward slope requires slowing because gravity increases speed and reduces braking effectiveness." },
  65: { answer: "false", explanation: "A towing license is required only when the towed vehicle's gross weight exceeds 750 kg." },
  66: { answer: "true", explanation: "General automobiles may not use a local-bus-only lane except for turns or unavoidable circumstances." },
  67: { answer: "false", explanation: "When an officer signals stop at an intersection, stop immediately before the intersection, not one meter before the officer." },
  68: { answer: "false", explanation: "Small vehicles tend to look farther away, large vehicles closer, and speed slower at night." },
  69: { answer: "false", explanation: "In busy urban traffic at night, use low beams to avoid dazzling other road users." },
  70: { answer: "true", explanation: "Passenger vehicles and large trucks must obey the posted 40 km/h maximum." },
  71: { answer: "false", explanation: "A driver may safely leave the road when necessary to avoid a head-on collision." },
  72: { answer: "false", explanation: "Without a sidewalk or side strip, park against the left edge and leave pedestrian space on the right." },
  73: { answer: "true", explanation: "The described foot and knee position is the safe, balanced motorcycle posture." },
  74: { answer: "false", explanation: "The sign prohibits right turns by any truck with a maximum load of two tons or more." },
  75: { answer: "true", explanation: "Other vehicles must never obstruct an emergency vehicle entering or leaving a main lane." },
  76: { answer: "true", explanation: "Alcohol impairs judgment and alertness; no one should drive after drinking any amount." },
  77: { answer: "false", explanation: "A two-wheeled vehicle should lean toward the inside of a curve, not outward." },
  78: { answer: "true", explanation: "The warning sign indicates traffic merging from the left ahead." },
  79: { answer: "true", explanation: "Signal a U-turn 30 meters before the point where it will be made." },
  80: { answer: "true", explanation: "A green light does not guarantee a clear intersection, so drivers must check before proceeding." },
  81: { answer: "true", explanation: "Water in brake drums can reduce braking effectiveness, so the brakes should be tested after deep water." },
  82: { answer: "true", explanation: "Vehicles must stop and yield whenever a pedestrian or bicycle is crossing or about to cross." },
  83: { answer: "true", explanation: "An undivided expressway section uses the same maximum speed as a general road." },
  84: { answer: "true", explanation: "Slowing beside a safety zone is required only when pedestrians are present." },
  85: { answer: "false", explanation: "Centrifugal force acts outward from the curve, not in the illustrated direction B." },
  86: { answer: "false", explanation: "All accidents, including property-only accidents, must be reported to police." },
  87: { answer: "false", explanation: "Drivers should plan the route and rest stops in advance to travel safely with time to spare." },
  88: { answer: "true", explanation: "Vehicle size, body type, and cargo all affect the extent of blind spots." },
  89: { answer: "true", explanation: "At night, opposing headlights can hide a pedestrian near the centerline, so reducing speed is prudent." },
  90: { answer: "false", explanation: "A high cargo center of gravity reduces stability and increases rollover risk at speed." },
};
