export type HonmanOfficialAnswer = {
  answer: "true" | "false";
  explanation: string;
};

export const honmanTestOneOfficialAnswers: Record<number, HonmanOfficialAnswer> = {
  1: { answer: "false", explanation: "New drivers licensed for less than one year are required to display the novice driver sign regardless of their confidence." },
  2: { answer: "false", explanation: "Drivers should mainly use engine braking and apply the foot brake as an auxiliary." },
  3: { answer: "true", explanation: "Park the car in a place where it does not impede the progress of other vehicles." },
  4: { answer: "true", explanation: "Drivers should consider pedestrians while driving." },
  5: { answer: "true", explanation: "This marking designates a no-stopping zone where vehicles must not stop." },
  6: { answer: "true", explanation: "It is a crime to permit driving when intoxicated." },
  7: { answer: "true", explanation: "This amount of distance between vehicles is required when considering stopping distance." },
  8: { answer: "true", explanation: "On multilane roads, general mopeds in principle use the two-step right-turn method for safety." },
  9: { answer: "false", explanation: "Vehicles may proceed at a low speed when passing a safety zone." },
  10: { answer: "true", explanation: "The designated vehicles must travel in the leftmost lane in principle." },
  11: { answer: "false", explanation: "The use of a child seat is required in the rear seat as well." },
  12: { answer: "true", explanation: "This is a law of physics. Drivers must be fully aware of it when driving on a curved road." },
  13: { answer: "false", explanation: "Drivers should give way to the overtaking vehicle by moving over to the left as much as possible." },
  14: { answer: "false", explanation: "Drivers should slow down before the curve and accelerate at the end of the curve." },
  15: { answer: "true", explanation: "A lower speed would result in less damage and increase the possibility of avoiding the collision." },
  16: { answer: "false", explanation: "The driver of a four-wheeled vehicle might overlook a two-wheeled vehicle." },
  17: { answer: "false", explanation: "Only vehicles with a total above-ground height of up to 3.3 meters may proceed." },
  18: { answer: "false", explanation: "Neither parking nor stopping a vehicle is allowed in tunnels with or without vehicular lanes." },
  19: { answer: "true", explanation: "Drivers must fully understand the characteristics of elderly people and children and prepare for unexpected behavior." },
  20: { answer: "true", explanation: "To avoid traffic accidents, clearly indicate that the vehicle has broken down." },
  21: { answer: "false", explanation: "Hazard lights, parking lights or tail lamps are not necessary when an emergency reflector device is positioned." },
  22: { answer: "true", explanation: "The vehicle owner should be responsible for automobile use." },
  23: { answer: "true", explanation: "In a no-overtaking zone, vehicles must not change lanes in order to overtake automobiles or mopeds." },
  24: { answer: "true", explanation: "The specified hand signal for reversing is an arm movement." },
  25: { answer: "true", explanation: "Drivers should allow more distance between vehicles, taking gravity and acceleration into consideration." },
  26: { answer: "true", explanation: "This is a characteristic of automatic-transmission vehicles. Be sure to apply the brakes while the vehicle is stopped." },
  27: { answer: "false", explanation: "Overtaking or passing is not prohibited, but one must not pass too closely or cut in front of the vehicle." },
  28: { answer: "false", explanation: "The meaning of the police officer’s hand signal is the same as a red light, but not the same as the arrow signal." },
  29: { answer: "false", explanation: "The driver is included in the seating capacity." },
  30: { answer: "false", explanation: "The side strip or shoulder of an expressway must not be used as a resting place." },
  31: { answer: "false", explanation: "The sign designates a bicycle path or a dedicated road for bicycles." },
  32: { answer: "false", explanation: "Cargo may be loaded on the seats unless it obstructs driving." },
  33: { answer: "true", explanation: "Many traffic accidents occur at intersections. Careful attention is necessary when proceeding through intersections." },
  34: { answer: "true", explanation: "Those who are unaware of their responsibilities in potential accidents are not qualified as drivers." },
  35: { answer: "true", explanation: "This is permitted as an exception to the general left-side rule." },
  36: { answer: "true", explanation: "Traffic signs and pavement markings communicate speed, how to proceed and other details clearly." },
  37: { answer: "true", explanation: "Sudden braking during high-speed driving is dangerous because the vehicle may lose control." },
  38: { answer: "false", explanation: "Light vehicles may not proceed because it is a side strip for pedestrians." },
  39: { answer: "true", explanation: "Drivers of two-wheeled vehicles should try to widen their field of vision." },
  40: { answer: "true", explanation: "This constitutes driving without a valid license because the suspended license is temporarily invalid." },
  41: { answer: "false", explanation: "One should move his or her gaze slightly to the left so as not to be dazzled by the lights." },
  42: { answer: "false", explanation: "One should avoid moving too close to the vehicle ahead and change lanes slowly." },
  43: { answer: "false", explanation: "It is permissible to cross the road when executing a left turn in order to enter or leave a location facing the left side." },
  44: { answer: "false", explanation: "Slouching too far forward is dangerous because the viewing field becomes narrow." },
  45: { answer: "true", explanation: "Confirmation is necessary when proceeding through a multilane railway crossing." },
  46: { answer: "false", explanation: "The driver must proceed as the traffic sign designates, on the left side." },
  47: { answer: "false", explanation: "Wave-shaped ripples on the tire are called the standing-wave phenomenon." },
  48: { answer: "true", explanation: "Both slowing down and stopping use the same signal, with the arm extending diagonally downward from the vehicle." },
  49: { answer: "false", explanation: "The steering wheel will pull to the right because it is pulled toward the side with lower tire pressure." },
  50: { answer: "true", explanation: "Considering the influence of fatigue, driving for two consecutive hours or longer should be avoided." },
  51: { answer: "false", explanation: "Vehicles approaching from the left have right of way, so vehicle B may not obstruct the progress of vehicle A." },
  52: { answer: "false", explanation: "Drivers should avoid approaching the shoulder because it becomes loose and might crumble on a rainy day." },
  53: { answer: "false", explanation: "Parking is prohibited within 1 meter of a fire alarm." },
  54: { answer: "false", explanation: "Automobiles must approach the center of the road when not driving on a one-way street." },
  55: { answer: "false", explanation: "Vehicles must stop. Slowing down is not an option." },
  56: { answer: "true", explanation: "The sign shows that the road is closed to passenger vehicles with a capacity of 11 passengers or more." },
  57: { answer: "true", explanation: "Drivers may park while loading or unloading cargo when the driver is immediately available to drive." },
  58: { answer: "false", explanation: "The personal parking place must be within 2 kilometers." },
  59: { answer: "true", explanation: "As dangerous overtaking is prohibited, giving up the attempt to overtake is right for safety reasons." },
  60: { answer: "true", explanation: "This warning sign indicates a danger of animals appearing suddenly on the road." },
  61: { answer: "true", explanation: "One should not put up with drowsiness, but should relieve it before resuming driving." },
  62: { answer: "false", explanation: "General mopeds may not proceed either." },
  63: { answer: "true", explanation: "It is safer to leave the vehicle and wait somewhere else because a parked vehicle may be struck." },
  64: { answer: "true", explanation: "The signboard indicates that the signal is provided for the smooth flow of bus traffic." },
  65: { answer: "true", explanation: "The horn may be used when needed to avoid danger." },
  66: { answer: "true", explanation: "Reaction distance is unrelated to worn tires because the brakes do not begin operating during reaction distance." },
  67: { answer: "false", explanation: "A permit must be obtained because the total length extends more than one-tenth of the vehicle’s length behind the automobile." },
  68: { answer: "false", explanation: "The sticker indicates the next inspection timing by year and month." },
  69: { answer: "true", explanation: "Fatigue and its effects are most evident in the eyes because of their heavy use while driving." },
  70: { answer: "true", explanation: "Headlights both maintain the range of vision and warn other drivers of the vehicle’s presence." },
  71: { answer: "false", explanation: "Vehicles executing right turns must not obstruct oncoming vehicles proceeding straight or turning left." },
  72: { answer: "false", explanation: "Vehicles should stop immediately before the intersection, not immediately before the traffic signal." },
  73: { answer: "false", explanation: "Vehicles that cannot satisfy the minimum speed limit are allowed to use the slower traffic lane." },
  74: { answer: "true", explanation: "This sign designates motor vehicles only and is placed on a national expressway or motorway." },
  75: { answer: "true", explanation: "Kinetic energy at collision is proportional to the square of speed; one-half times one-half equals one-quarter." },
  76: { answer: "false", explanation: "There should be room to pull the hand brake further; otherwise, the brake may not operate well." },
  77: { answer: "false", explanation: "This sign warns of falling rocks." },
  78: { answer: "true", explanation: "Drivers should account for reaction time so they can respond safely when danger arises." },
  79: { answer: "true", explanation: "Corners are dangerous locations where drivers must not overtake and must slow down." },
  80: { answer: "true", explanation: "At an intersection, vehicles must let an emergency vehicle proceed in any direction." },
  81: { answer: "false", explanation: "The documents must be kept in the vehicle while driving." },
  82: { answer: "true", explanation: "A two-wheeled vehicle tends to be overlooked in the blind spot of a four-wheeled vehicle’s rearview mirror." },
  83: { answer: "true", explanation: "Sudden maneuvers are dangerous and should be avoided, particularly on bad road surfaces." },
  84: { answer: "false", explanation: "Vehicle A does not have to slow down because it has the right of way." },
  85: { answer: "false", explanation: "Coolant or oil leakage is a mechanical breakdown that requires repair." },
  86: { answer: "false", explanation: "Automobiles and mopeds may not enter the side strip or sidewalk." },
  87: { answer: "true", explanation: "One should respect traffic conditions and drive in an orderly manner." },
  88: { answer: "true", explanation: "The distance and speed of two-wheeled vehicles tend to be misjudged because they are small." },
  89: { answer: "true", explanation: "Driving at a lower speed is necessary because the area illuminated by headlights is limited." },
  90: { answer: "true", explanation: "When entering a roadside garage, consider other traffic and the safety of pulling out the next time." },
};
