export type HonmanQuestion = {
  id: number;
  text: string;
  figure?: { src: string; alt: string };
};

export const honmanTestOne: HonmanQuestion[] = [
  { id: 1, text: "Of the people who have only recently obtained a regular driver’s license, only people who are not confident in their driving display the novice driver sign; people who are confident in their driving are not required to display it." },
  { id: 2, text: "When driving down a long downward slope, drivers of four-wheeled vehicles should mainly apply the foot brake and drivers of two-wheeled vehicles should mainly apply the brakes on the front and back wheels. Engine braking should be used as an auxiliary." },
  { id: 3, text: "If a driver is unavoidably forced to park on an expressway because the vehicle cannot be driven due to a breakdown, etc., the driver must park on a sufficiently wide shoulder or side strip." },
  { id: 4, text: "If a pedestrian is crossing at or near an intersection that has no pedestrian crossing, a vehicle must reduce its speed, slow down, stop, or take other precautions so as not to hinder the pedestrian’s crossing." },
  { id: 5, text: "Where there is a pavement marking as shown in Figure 1, vehicles are permitted to proceed but must not stop within it.", figure: { src: "/images/honman-test/figure-1.svg", alt: "Figure 1: hatched rectangular pavement marking" } },
  { id: 6, text: "One must not offer or recommend alcohol to someone who may drive later." },
  { id: 7, text: "The necessary distance between vehicles on national expressways, assuming a dry road surface and new tires, is about 100 meters at 100 km/h." },
  { id: 8, text: "At intersections between roads with three or more lanes in each direction (multi-lane roads) and with traffic control, if there is no indication from traffic signs, etc., general mopeds must execute a right turn using the two-step method." },
  { id: 9, text: "When there are passengers getting on and off a streetcar, a driver must stop until all of the passengers or other people finish crossing the road, regardless of whether there is a safety zone or not." },
  { id: 10, text: "On a road where there is a traffic sign as shown in Figure 2, large-size trucks, specified medium trucks, and special heavy equipment must travel in the leftmost lane.", figure: { src: "/images/honman-test/figure-2.svg", alt: "Figure 2: heavy trucks must use the leftmost lane sign" } },
  { id: 11, text: "The use of a child seat is not required for a preschool child less than six years of age riding in the rear seat of a four-wheeled vehicle." },
  { id: 12, text: "Centrifugal force increases proportionally to the square of speed, and also increases as the radius of the curve decreases." },
  { id: 13, text: "When a driver is being overtaken by another vehicle, it is not particularly necessary for the driver to give way in their lane, as long as he or she does not accelerate, and even if there is not enough room between his or her vehicle and the vehicle in front." },
  { id: 14, text: "The method of passing around the curve as shown in Figure 3 is correct.", figure: { src: "/images/honman-test/figure-3.svg", alt: "Figure 3: acceleration and deceleration around a road curve" } },
  { id: 15, text: "Even when it looks as though there will be a head-on collision with an oncoming vehicle, the driver should not give up but should try to avoid the vehicle, even if just a little, by using the brake or steering wheel." },
  { id: 16, text: "If a two-wheeled vehicle is being driven in a position that can be seen from a four-wheeled vehicle, it won’t be overlooked by the driver of the four-wheeled vehicle." },
  { id: 17, text: "Where there is a traffic sign as shown in Figure 4, vehicles loaded with cargo of a height of up to 3.3 meters from the cargo bed may proceed.", figure: { src: "/images/honman-test/figure-4.svg", alt: "Figure 4: 3.3 meter height restriction sign" } },
  { id: 18, text: "Parking and stopping are permitted in tunnels with vehicular lanes." },
  { id: 19, text: "Some pedestrians such as elderly people and children behave in an unexpected manner, so drivers must carefully observe their movements." },
  { id: 20, text: "When parking a regular motor vehicle on a general road in the daytime because of a breakdown, drivers should position an emergency warning reflector device or open the trunk or hood so that other drivers can see that the vehicle is broken down." },
  { id: 21, text: "When parking or stopping a regular motor vehicle on a general road at night, even if the driver positions an emergency warning reflector device at the rear of the vehicle, he or she must turn on the hazard lights, parking lights, or tail lamps." },
  { id: 46, text: "Where there is a traffic sign as shown in Figure 10 on the road, a driver must proceed as indicated by the black arrow.", figure: { src: "/images/honman-test/figure-10.svg", alt: "Figure 10: proceed as indicated by the black arrow" } },
  { id: 47, text: "The hydroplaning phenomenon, which occurs while driving at high speed, is the wave appearing in the tire that occurs when tire pressure is low." },
  { id: 48, text: "The hand signal for slowing down is the same as that for stopping." },
  { id: 49, text: "If the pressure of the front right tire is lower than that of the front left tire, the steering wheel will pull to the left." },
  { id: 50, text: "If driving for a long period, a driver should stop driving once every two hours and have a rest." },
  { id: 51, text: "When vehicle A and vehicle B are approaching an intersection that has no traffic signal and the streets are the same width, as shown in Figure 11, vehicle A may not obstruct the progress of vehicle B.", figure: { src: "/images/honman-test/figure-11.svg", alt: "Figure 11: vehicles A and B approaching an uncontrolled intersection" } },
  { id: 52, text: "Because visibility is poor when it is raining, in order to avoid a head-on collision with an oncoming vehicle, it is best to approach the shoulder as close as possible and proceed." },
  { id: 53, text: "Parking is prohibited within 5 meters of a fire hydrant, a place where firefighting equipment is stored, or a fire alarm." },
  { id: 54, text: "When executing a right turn, the automobile must initially approach the right edge of the road as closely as possible and slow down immediately inside the center point of the intersection. (Except roundabout.)" },
  { id: 55, text: "When the traffic signal is a flashing red light, vehicles must stop or slow down." },
  { id: 56, text: "On a road where there is a traffic sign as shown in Figure 12, a passenger vehicle with 10 passengers may proceed.", figure: { src: "/images/honman-test/figure-12.svg", alt: "Figure 12: passenger vehicle prohibition sign" } },
  { id: 57, text: "An automobile may stop for ten minutes on a road where there is less than 3.5 meters of space between the right side of the vehicle and the right side of the road while the driver stands beside the vehicle and gives instructions for the loading of cargo." },
  { id: 58, text: "The owner of an automobile (excluding two-wheeled motor vehicles) must obtain a personal parking place for it that is not on a road and is within 5 kilometers of the address or other base position from which the automobile will be used." },
  { id: 59, text: "If the driver notices that the vehicle behind is attempting to overtake the driver’s own vehicle, when intending to overtake the vehicle ahead and checking for safety, he or she should give up the attempt to overtake the vehicle ahead." },
  { id: 60, text: "The traffic sign in Figure 13 indicates that there is a danger of animals appearing suddenly on the road.", figure: { src: "/images/honman-test/figure-13.svg", alt: "Figure 13: warning sign for animals appearing suddenly" } },
  { id: 61, text: "If drivers feel even slightly sleepy while driving at night, they should stop the vehicle in a safe location and take a nap or rest for a short time, resuming driving after they feel refreshed." },
  { id: 62, text: "On roads where there is a traffic sign as shown in Figure 14, large-size and regular motorcycles may not proceed, but general mopeds may proceed.", figure: { src: "/images/honman-test/figure-14.svg", alt: "Figure 14: motorcycle prohibition sign" } },
  { id: 63, text: "If unavoidably forced to park on an expressway due to a breakdown, the driver (and any passengers) should leave the vehicle and move to a safe location after completing the necessary measures to prevent danger." },
  { id: 64, text: "Where there is a signboard as shown in Figure 15, only buses may follow the traffic signal indicated by the signboard.", figure: { src: "/images/honman-test/figure-15.svg", alt: "Figure 15: buses-only signboard" } },
  { id: 65, text: "When a vehicle attempts to overtake the vehicle ahead, the vehicle ahead may not notice and begin to change to the right lane. If the driver of the overtaking vehicle senses danger, he or she may sound the horn." },
  { id: 66, text: "When tires wear down, the frictional resistance between the road surface and the tires decreases. Braking distance increases but reaction distance is not affected." },
  { id: 67, text: "If loading cargo that cannot be divided as shown in Figure 16, a driver need not obtain a permit from the police chief having jurisdiction over the place of departure.", figure: { src: "/images/honman-test/figure-16.svg", alt: "Figure 16: truck carrying an indivisible projecting load" } },
  { id: 68, text: "An inspection sticker indicates the month and year in which the inspection was made." },
  { id: 69, text: "Fatigue and its effects while driving are shown most strongly in the eyes; incidences of failing to notice something or mistaking what one sees become more frequent and one’s sense of judgment deteriorates." },
  { id: 70, text: "When proceeding in a place such as a tunnel or in thick fog that inhibits one’s ability to see 50 meters ahead (200 meters on an expressway), the lights must be turned on, even in the daytime." },
  { id: 71, text: "In the situation shown in Figure 17, vehicle A has entered the intersection first intending to execute a right turn. If vehicle B proceeds straight through, vehicle A must wait inside the intersection until it passes, but if vehicle B is executing a left turn, vehicle A may go ahead and execute a right turn.", figure: { src: "/images/honman-test/figure-17.svg", alt: "Figure 17: vehicles A and B at an intersection" } },
  { id: 72, text: "At intersections with a traffic signal but no stop line, the correct position to stop is immediately before the traffic signal." },
  { id: 73, text: "Vehicles other than large-size trucks loaded with cargo may not use the slower traffic lane of an expressway." },
  { id: 74, text: "The traffic sign shown in Figure 18 designates a national expressway or a motorway.", figure: { src: "/images/honman-test/figure-18.svg", alt: "Figure 18: national expressway or motorway sign" } },
  { id: 75, text: "When a vehicle collides with an object at rest, if it can decrease its speed to half, the kinetic energy at the time of impact will be just about one-quarter of that generated when speed is not decreased." },
];
