export type UnitKanji = { kanji: string; meaning: string; readings: string; example: string };

export const minnaN5KanjiByUnit: Record<number, UnitKanji[]> = {
  1:[
    {kanji:"私",meaning:"আমি/ব্যক্তিগত",readings:"わたし・し",example:"私 · わたし"},
    {kanji:"人",meaning:"মানুষ/জাতীয়তার ব্যক্তি",readings:"ひと・じん・にん",example:"あの人 · あのひと／日本人 · にほんじん"},
    {kanji:"方",meaning:"ব্যক্তি (ভদ্র)/দিক",readings:"かた・ほう",example:"あの方 · あのかた"},
    {kanji:"先",meaning:"আগে/অগ্রবর্তী",readings:"せん・さき",example:"先生 · せんせい"},
    {kanji:"生",meaning:"জীবন/জন্ম/শিক্ষার্থী",readings:"せい・しょう・い(きる)",example:"先生 · せんせい／学生 · がくせい"},
    {kanji:"教",meaning:"শেখানো/শিক্ষা",readings:"きょう・おし(える)",example:"教師 · きょうし"},
    {kanji:"師",meaning:"বিশেষজ্ঞ/শিক্ষক",readings:"し",example:"教師 · きょうし"},
    {kanji:"学",meaning:"শেখা/বিদ্যা",readings:"がく・まな(ぶ)",example:"学生 · がくせい／大学 · だいがく"},
    {kanji:"会",meaning:"মিলিত হওয়া/সমিতি",readings:"かい・あ(う)",example:"会社員 · かいしゃいん"},
    {kanji:"社",meaning:"কোম্পানি/সংস্থা",readings:"しゃ・やしろ",example:"会社 · かいしゃ／社員 · しゃいん"},
    {kanji:"員",meaning:"সদস্য/কর্মচারী",readings:"いん",example:"会社員 · かいしゃいん／銀行員 · ぎんこういん"},
    {kanji:"銀",meaning:"রূপা",readings:"ぎん",example:"銀行員 · ぎんこういん"},
    {kanji:"行",meaning:"যাওয়া/লাইন/ব্যাংক",readings:"こう・ぎょう・い(く)",example:"銀行 · ぎんこう"},
    {kanji:"医",meaning:"চিকিৎসা",readings:"い",example:"医者 · いしゃ"},
    {kanji:"者",meaning:"ব্যক্তি/পেশাজীবী",readings:"しゃ・もの",example:"医者 · いしゃ／研究者 · けんきゅうしゃ"},
    {kanji:"研",meaning:"ঘষে শান দেওয়া/গবেষণা",readings:"けん・と(ぐ)",example:"研究者 · けんきゅうしゃ"},
    {kanji:"究",meaning:"গভীরভাবে অনুসন্ধান",readings:"きゅう・きわ(める)",example:"研究 · けんきゅう"},
    {kanji:"大",meaning:"বড়/মহান",readings:"だい・おお(きい)",example:"大学 · だいがく"},
    {kanji:"病",meaning:"অসুস্থতা/রোগ",readings:"びょう・やまい",example:"病院 · びょういん"},
    {kanji:"院",meaning:"প্রতিষ্ঠান/হাসপাতাল",readings:"いん",example:"病院 · びょういん"},
    {kanji:"一",meaning:"এক",readings:"いち・ひと(つ)",example:"一歳 · いっさい"},
    {kanji:"歳",meaning:"বয়স/বছর",readings:"さい",example:"何歳 · なんさい"},
    {kanji:"何",meaning:"কী/কত",readings:"なに・なん",example:"何歳 · なんさい"},
    {kanji:"韓",meaning:"কোরিয়া",readings:"かん",example:"韓国 · かんこく"},
    {kanji:"国",meaning:"দেশ",readings:"くに・こく",example:"韓国 · かんこく／お国 · おくに"},
    {kanji:"中",meaning:"মাঝে/চীন",readings:"ちゅう・なか",example:"中国 · ちゅうごく"},
    {kanji:"日",meaning:"সূর্য/দিন/জাপান",readings:"に・にち・ひ",example:"日本 · にほん"},
    {kanji:"本",meaning:"মূল/বই/জাপান",readings:"ほん・もと",example:"日本 · にほん"},
    {kanji:"電",meaning:"বিদ্যুৎ",readings:"でん",example:"パワー電気 · パワーでんき"},
    {kanji:"気",meaning:"শক্তি/বায়ু/মনের অবস্থা",readings:"き",example:"電気 · でんき"},
    {kanji:"神",meaning:"দেবতা/ঈশ্বর",readings:"しん・じん・かみ",example:"神戸病院 · こうべびょういん"},
    {kanji:"戸",meaning:"দরজা/পরিবার গণনা",readings:"と・こ",example:"神戸 · こうべ"},
    {kanji:"富",meaning:"সম্পদ/সমৃদ্ধি",readings:"ふ・とみ",example:"富士大学 · ふじだいがく"},
    {kanji:"士",meaning:"পেশাজীবী/যোদ্ধা",readings:"し・じ",example:"富士 · ふじ"},
    {kanji:"名",meaning:"নাম",readings:"な・めい",example:"お名前 · おなまえ"},
  ],
  2:[
    {kanji:"本",meaning:"বই/মূল",readings:"ほん・もと",example:"この本 · このほん"},
    {kanji:"辞",meaning:"শব্দ/পদত্যাগ",readings:"じ・や(める)",example:"辞書 · じしょ"},
    {kanji:"書",meaning:"লেখা/বই",readings:"しょ・か(く)",example:"辞書 · じしょ"},
    {kanji:"新",meaning:"নতুন",readings:"しん・あたら(しい)",example:"新聞 · しんぶん"},
    {kanji:"聞",meaning:"শোনা/জিজ্ঞেস করা",readings:"ぶん・き(く)",example:"新聞 · しんぶん"},
    {kanji:"雑",meaning:"বিবিধ/মিশ্র",readings:"ざつ・ぞう",example:"雑誌 · ざっし"},
    {kanji:"誌",meaning:"পত্রিকা/নথি",readings:"し",example:"雑誌 · ざっし"},
    {kanji:"電",meaning:"বিদ্যুৎ",readings:"でん",example:"電話 · でんわ"},
    {kanji:"話",meaning:"কথা/কথা বলা",readings:"わ・はな(す)",example:"電話 · でんわ"},
    {kanji:"車",meaning:"গাড়ি/যান",readings:"くるま・しゃ",example:"あの車 · あのくるま"},
    {kanji:"土",meaning:"মাটি/স্থানীয়",readings:"ど・つち",example:"お土産 · おみやげ"},
    {kanji:"産",meaning:"উৎপাদন/জন্ম",readings:"さん・う(む)",example:"お土産 · おみやげ"},
    {kanji:"英",meaning:"ইংল্যান্ড/ইংরেজি",readings:"えい",example:"英語 · えいご"},
    {kanji:"語",meaning:"ভাষা/শব্দ",readings:"ご・かた(る)",example:"英語 · えいご"},
    {kanji:"何",meaning:"কী/কত",readings:"なに・なん",example:"何ですか · なんですか"},
    {kanji:"気",meaning:"মন/ভাব/শক্তি",readings:"き・け",example:"気にしないでください"},
  ],
  3:[
    {kanji:"場",meaning:"জায়গা/ক্ষেত্র",readings:"ば・じょう",example:"場所 · ばしょ"},{kanji:"所",meaning:"স্থান",readings:"ところ・しょ",example:"場所 · ばしょ"},
    {kanji:"教",meaning:"শেখানো/শিক্ষা",readings:"きょう・おし(える)",example:"教室 · きょうしつ"},{kanji:"室",meaning:"ঘর/কক্ষ",readings:"しつ・むろ",example:"教室 · きょうしつ／会議室 · かいぎしつ"},
    {kanji:"食",meaning:"খাওয়া/খাদ্য",readings:"しょく・た(べる)",example:"食堂 · しょくどう"},{kanji:"堂",meaning:"হল/বড় কক্ষ",readings:"どう",example:"食堂 · しょくどう"},
    {kanji:"事",meaning:"বিষয়/কাজ",readings:"じ・こと",example:"事務所 · じむしょ"},{kanji:"務",meaning:"দায়িত্ব/কাজ",readings:"む・つと(める)",example:"事務所 · じむしょ"},
    {kanji:"会",meaning:"সভা/মিলিত হওয়া",readings:"かい・あ(う)",example:"会議室 · かいぎしつ／会社 · かいしゃ"},{kanji:"議",meaning:"আলোচনা/পরামর্শ",readings:"ぎ",example:"会議 · かいぎ"},
    {kanji:"受",meaning:"গ্রহণ করা",readings:"う(ける)・じゅ",example:"受付 · うけつけ"},{kanji:"付",meaning:"লাগানো/সংযুক্ত",readings:"つ(ける)・ふ",example:"受付 · うけつけ"},
    {kanji:"部",meaning:"বিভাগ/অংশ",readings:"ぶ・へ",example:"部屋 · へや"},{kanji:"屋",meaning:"ঘর/দোকান",readings:"や・おく",example:"部屋 · へや"},
    {kanji:"階",meaning:"তলা/সিঁড়ির ধাপ",readings:"かい",example:"階段 · かいだん"},{kanji:"段",meaning:"ধাপ/স্তর",readings:"だん",example:"階段 · かいだん"},
    {kanji:"自",meaning:"নিজে",readings:"じ・みずか(ら)",example:"自動販売機 · じどうはんばいき"},{kanji:"動",meaning:"চলা/নড়া",readings:"どう・うご(く)",example:"自動 · じどう"},
    {kanji:"販",meaning:"বিক্রি/বিপণন",readings:"はん",example:"販売 · はんばい"},{kanji:"売",meaning:"বিক্রি করা",readings:"ばい・う(る)",example:"販売 · はんばい"},{kanji:"機",meaning:"যন্ত্র/মেশিন",readings:"き",example:"自動販売機 · じどうはんばいき"},
    {kanji:"電",meaning:"বিদ্যুৎ",readings:"でん",example:"電話 · でんわ"},{kanji:"話",meaning:"কথা/কথা বলা",readings:"わ・はな(す)",example:"電話 · でんわ"},
    {kanji:"社",meaning:"কোম্পানি/সংস্থা",readings:"しゃ",example:"会社 · かいしゃ"},{kanji:"国",meaning:"দেশ",readings:"くに・こく",example:"お国 · おくに"},
    {kanji:"地",meaning:"মাটি/স্থান",readings:"ち・じ",example:"地下 · ちか"},{kanji:"下",meaning:"নিচে",readings:"した・か",example:"地下 · ちか"},{kanji:"何",meaning:"কী/কত",readings:"なに・なん",example:"何階 · なんがい"},
    {kanji:"百",meaning:"একশ",readings:"ひゃく",example:"八百円 · はっぴゃくえん"},{kanji:"千",meaning:"এক হাজার",readings:"せん",example:"二千円 · にせんえん"},{kanji:"万",meaning:"দশ হাজার",readings:"まん",example:"二万円 · にまんえん"},{kanji:"円",meaning:"yen/বৃত্ত",readings:"えん・まる",example:"二千五百円 · にせんごひゃくえん"},
    {kanji:"靴",meaning:"জুতা",readings:"くつ",example:"靴売り場 · くつうりば"},
  ],
  4:[{kanji:"時",meaning:"সময়/ঘণ্টা",readings:"じ・とき",example:"七時 · しちじ"},{kanji:"分",meaning:"মিনিট/অংশ",readings:"ふん・ぶん",example:"十分 · じゅっぷん"},{kanji:"半",meaning:"অর্ধেক",readings:"はん",example:"七時半"},{kanji:"今",meaning:"এখন",readings:"いま・こん",example:"今 · いま"},{kanji:"毎",meaning:"প্রতি",readings:"まい",example:"毎日 · まいにち"},{kanji:"週",meaning:"সপ্তাহ",readings:"しゅう",example:"毎週 · まいしゅう"}],
  5:[{kanji:"行",meaning:"যাওয়া",readings:"い・こう",example:"行きます · いきます"},{kanji:"来",meaning:"আসা",readings:"き・らい",example:"来ます · きます"},{kanji:"帰",meaning:"ফেরা",readings:"かえ・き",example:"帰ります"},{kanji:"駅",meaning:"স্টেশন",readings:"えき",example:"駅 · えき"},{kanji:"歩",meaning:"হাঁটা",readings:"ある(く)・ほ",example:"歩いて · あるいて"},{kanji:"校",meaning:"বিদ্যালয়",readings:"こう",example:"学校 · がっこう"}],
  6:[{kanji:"食",meaning:"খাওয়া/খাদ্য",readings:"た・しょく",example:"食べます"},{kanji:"飲",meaning:"পান করা",readings:"の・いん",example:"飲みます"},{kanji:"見",meaning:"দেখা",readings:"み・けん",example:"見ます"},{kanji:"写",meaning:"অনুলিপি/ছবি তোলা",readings:"しゃ・うつ(す)",example:"写真 · しゃしん"},{kanji:"真",meaning:"সত্য/প্রকৃত",readings:"しん・ま",example:"写真 · しゃしん"},{kanji:"画",meaning:"ছবি/আঁকা",readings:"が・かく",example:"映画 · えいが"}],
  7:[{kanji:"書",meaning:"লেখা",readings:"か・しょ",example:"書きます"},{kanji:"読",meaning:"পড়া",readings:"よ・どく",example:"読みます"},{kanji:"話",meaning:"কথা বলা",readings:"はな・わ",example:"話します"},{kanji:"語",meaning:"ভাষা",readings:"ご",example:"日本語 · にほんご"},{kanji:"英",meaning:"ইংল্যান্ড/ইংরেজি",readings:"えい",example:"英語 · えいご"},{kanji:"貸",meaning:"ধার দেওয়া",readings:"か(す)・たい",example:"貸します · かします"}],
  8:[{kanji:"大",meaning:"বড়",readings:"おお・だい",example:"大きい"},{kanji:"小",meaning:"ছোট",readings:"ちい・しょう",example:"小さい"},{kanji:"新",meaning:"নতুন",readings:"あたら・しん",example:"新しい"},{kanji:"古",meaning:"পুরোনো",readings:"ふる・こ",example:"古い"},{kanji:"静",meaning:"শান্ত",readings:"しず(か)・せい",example:"静か · しずか"},{kanji:"便",meaning:"সুবিধা",readings:"べん",example:"便利 · べんり"}],
  9:[{kanji:"好",meaning:"পছন্দ",readings:"す・こう",example:"好きです"},{kanji:"音",meaning:"শব্দ",readings:"おと・おん",example:"音楽 · おんがく"},{kanji:"料",meaning:"ফি/উপকরণ",readings:"りょう",example:"料理 · りょうり"},{kanji:"理",meaning:"যুক্তি/নীতি",readings:"り",example:"料理 · りょうり"},{kanji:"転",meaning:"ঘোরা",readings:"てん",example:"運転 · うんてん"},{kanji:"解",meaning:"বোঝা/সমাধান",readings:"かい・わか(る)",example:"理解します · りかいします"}],
  10:[{kanji:"有",meaning:"থাকা/অধিকার",readings:"あ・ゆう",example:"有ります"},{kanji:"中",meaning:"ভিতরে/মাঝে",readings:"なか・ちゅう",example:"箱の中"},{kanji:"外",meaning:"বাইরে",readings:"そと・がい",example:"家の外"},{kanji:"後",meaning:"পরে/পেছনে",readings:"うし(ろ)・ご",example:"後ろ · うしろ"},{kanji:"机",meaning:"ডেস্ক",readings:"つくえ",example:"机 · つくえ"},{kanji:"隣",meaning:"পাশের",readings:"となり",example:"隣 · となり"}],
  11:[{kanji:"一",meaning:"এক",readings:"いち・ひと",example:"一つ · ひとつ"},{kanji:"二",meaning:"দুই",readings:"に・ふた",example:"二人 · ふたり"},{kanji:"三",meaning:"তিন",readings:"さん・みっ",example:"三つ"},{kanji:"間",meaning:"সময়/ফাঁক",readings:"かん・あいだ",example:"二時間"},{kanji:"家",meaning:"বাড়ি/পরিবার",readings:"いえ・か",example:"家族 · かぞく"},{kanji:"族",meaning:"বংশ/গোষ্ঠী",readings:"ぞく",example:"家族 · かぞく"}],
  12:[{kanji:"高",meaning:"উঁচু/দামি",readings:"たか・こう",example:"高かったです"},{kanji:"安",meaning:"সস্তা/নিরাপদ",readings:"やす・あん",example:"安いです"},{kanji:"番",meaning:"ক্রম/নম্বর",readings:"ばん",example:"一番 · いちばん"},{kanji:"同",meaning:"একই",readings:"おな(じ)・どう",example:"同じ · おなじ"},{kanji:"長",meaning:"লম্বা/প্রধান",readings:"なが(い)・ちょう",example:"長い · ながい"},{kanji:"昔",meaning:"অতীত/সেকাল",readings:"むかし",example:"昔 · むかし"}],
  13:[{kanji:"欲",meaning:"চাওয়া",readings:"ほ・よく",example:"欲しいです"},{kanji:"買",meaning:"কেনা",readings:"か・ばい",example:"買いたいです"},{kanji:"遊",meaning:"খেলা/ঘোরা",readings:"あそ・ゆう",example:"遊びに行きます"},{kanji:"物",meaning:"জিনিস",readings:"もの・ぶつ",example:"飲み物 · のみもの"},{kanji:"留",meaning:"থামা/রাখা",readings:"りゅう・とど(まる)",example:"留学 · りゅうがく"},{kanji:"暖",meaning:"উষ্ণ",readings:"あたた(かい)・だん",example:"暖かい · あたたかい"}],
  14:[{kanji:"待",meaning:"অপেক্ষা",readings:"ま・たい",example:"待ってください"},{kanji:"立",meaning:"দাঁড়ানো",readings:"た・りつ",example:"立っています"},{kanji:"使",meaning:"ব্যবহার",readings:"つか・し",example:"使ってください"},{kanji:"閉",meaning:"বন্ধ করা",readings:"し(める)・へい",example:"閉めます · しめます"},{kanji:"押",meaning:"চাপা",readings:"お(す)・おう",example:"押します · おします"},{kanji:"窓",meaning:"জানালা",readings:"まど",example:"窓 · まど"}],
  15:[{kanji:"入",meaning:"প্রবেশ",readings:"はい・にゅう",example:"入ってもいいです"},{kanji:"出",meaning:"বের হওয়া",readings:"で・しゅつ",example:"出てはいけません"},{kanji:"住",meaning:"বাস করা",readings:"す・じゅう",example:"住んでいます"},{kanji:"止",meaning:"থামা",readings:"と(める)・し",example:"止めます · とめます"},{kanji:"務",meaning:"দায়িত্ব/কাজ",readings:"つと(める)・む",example:"務めます · つとめます"},{kanji:"結",meaning:"বাঁধা/সংযুক্ত",readings:"けつ・むす(ぶ)",example:"結婚します · けっこんします"}],
  16:[{kanji:"朝",meaning:"সকাল",readings:"あさ・ちょう",example:"朝ごはん"},{kanji:"昼",meaning:"দুপুর",readings:"ひる・ちゅう",example:"昼休み"},{kanji:"夜",meaning:"রাত",readings:"よる・や",example:"夜になります"},{kanji:"頭",meaning:"মাথা",readings:"あたま・とう",example:"頭 · あたま"},{kanji:"楽",meaning:"আনন্দ/সহজ",readings:"たの(しい)・がく",example:"楽しい · たのしい"},{kanji:"始",meaning:"শুরু",readings:"はじ(める)・し",example:"始めます · はじめます"}],
  17:[{kanji:"忘",meaning:"ভুলে যাওয়া",readings:"わす・ぼう",example:"忘れないで"},{kanji:"持",meaning:"ধরা/সঙ্গে রাখা",readings:"も・じ",example:"持ってこなければ"},{kanji:"薬",meaning:"ওষুধ",readings:"くすり・やく",example:"薬を飲みます"},{kanji:"払",meaning:"পরিশোধ করা",readings:"はら(う)・ふつ",example:"払います · はらいます"},{kanji:"心",meaning:"মন/হৃদয়",readings:"こころ・しん",example:"心配 · しんぱい"},{kanji:"配",meaning:"বিতরণ/চিন্তা",readings:"はい",example:"心配 · しんぱい"}],
  18:[{kanji:"前",meaning:"আগে",readings:"まえ・ぜん",example:"寝る前に"},{kanji:"作",meaning:"তৈরি",readings:"つく・さく",example:"料理を作る"},{kanji:"洗",meaning:"ধোয়া",readings:"あら(う)・せん",example:"洗います · あらいます"},{kanji:"集",meaning:"জড়ো করা",readings:"あつ(める)・しゅう",example:"集めます · あつめます"},{kanji:"泳",meaning:"সাঁতার",readings:"およ(ぐ)・えい",example:"泳ぎます · およぎます"},{kanji:"力",meaning:"শক্তি/সামর্থ্য",readings:"ちから・りょく",example:"できる · できます"}],
  19:[{kanji:"登",meaning:"ওঠা",readings:"のぼ・とう",example:"山に登ったこと"},{kanji:"休",meaning:"বিশ্রাম",readings:"やす・きゅう",example:"休んだり"},{kanji:"掃",meaning:"পরিষ্কার",readings:"そう",example:"掃除します"},{kanji:"散",meaning:"ছড়িয়ে পড়া",readings:"さん",example:"散歩します · さんぽします"},{kanji:"医",meaning:"চিকিৎসা",readings:"い",example:"医者 · いしゃ"},{kanji:"寒",meaning:"ঠান্ডা",readings:"さむ(い)・かん",example:"寒いです · さむいです"}],
  20:[{kanji:"知",meaning:"জানা",readings:"し・ち",example:"知っている"},{kanji:"当",meaning:"সঠিক/সেই",readings:"とう・あ(たる)",example:"本当 · ほんとう"},{kanji:"暇",meaning:"অবসর",readings:"ひま",example:"暇です · ひまです"},{kanji:"彼",meaning:"সে (পুরুষ)",readings:"かれ",example:"彼女 · かのじょ"},{kanji:"全",meaning:"সম্পূর্ণ/সব",readings:"ぜん・すべ(て)",example:"全然 · ぜんぜん"},{kanji:"気",meaning:"মেজাজ/আত্মা",readings:"き",example:"元気 · げんき"}],
  21:[{kanji:"思",meaning:"মনে করা",readings:"おも・し",example:"いいと思います"},{kanji:"言",meaning:"বলা/উক্তি",readings:"い・げん",example:"行くと言いました"},{kanji:"意",meaning:"মত/ইচ্ছা",readings:"い",example:"意見 · いけん"},{kanji:"正",meaning:"সঠিক",readings:"ただ(しい)・せい",example:"正しいです · ただしいです"},{kanji:"天",meaning:"আকাশ/স্বর্গ",readings:"てん",example:"天気 · てんき"},{kanji:"案",meaning:"প্রস্তাব/ধারণা",readings:"あん",example:"案 · あん"}],
  22:[{kanji:"着",meaning:"পরা/পৌঁছানো",readings:"き・ちゃく",example:"着ている人"},{kanji:"働",meaning:"কাজ",readings:"はたら・どう",example:"働いている会社"},{kanji:"服",meaning:"পোশাক",readings:"ふく",example:"洋服 · ようふく"},{kanji:"息",meaning:"শ্বাস",readings:"いき・そく",example:"息子 · むすこ"},{kanji:"子",meaning:"সন্তান",readings:"こ・し",example:"息子 · むすこ"},{kanji:"鏡",meaning:"আয়না/লেন্স",readings:"きょう・かがみ",example:"眼鏡 · めがね"}],
  23:[{kanji:"回",meaning:"ঘোরা/বার",readings:"まわ・かい",example:"右へ回します"},{kanji:"開",meaning:"খোলা",readings:"あ・かい",example:"ドアが開きます"},{kanji:"道",meaning:"রাস্তা",readings:"みち・どう",example:"道 · みち"},{kanji:"花",meaning:"ফুল",readings:"はな",example:"花 · はな"},{kanji:"咲",meaning:"ফোটা",readings:"さ(く)",example:"咲きます · さきます"},{kanji:"引",meaning:"টানা",readings:"ひ(く)・いん",example:"引きます · ひきます"}],
  24:[{kanji:"手",meaning:"হাত",readings:"て・しゅ",example:"手伝います"},{kanji:"送",meaning:"পাঠানো",readings:"おく・そう",example:"駅まで送ります"},{kanji:"教",meaning:"শেখানো",readings:"おし・きょう",example:"教えてくれました"},{kanji:"直",meaning:"ঠিক করা/সোজা",readings:"なお(す)・ちょく",example:"直します · なおします"},{kanji:"紹",meaning:"পরিচয়",readings:"しょう",example:"紹介します · しょうかいします"},{kanji:"介",meaning:"মধ্যস্থতা",readings:"かい",example:"紹介します · しょうかいします"}],
  25:[{kanji:"終",meaning:"শেষ",readings:"お・しゅう",example:"仕事が終わったら"},{kanji:"雨",meaning:"বৃষ্টি",readings:"あめ・う",example:"雨が降っても"},{kanji:"連",meaning:"যোগ/সঙ্গে",readings:"れん・つ",example:"連絡します"},{kanji:"決",meaning:"সিদ্ধান্ত",readings:"き・けつ",example:"決めます"},{kanji:"練",meaning:"অনুশীলন",readings:"れん",example:"練習します · れんしゅうします"},{kanji:"習",meaning:"শেখা/অভ্যাস",readings:"なら(う)・しゅう",example:"練習します · れんしゅうします"}],
};
