export type VocabularyExample = {
  japanese: string;
  romaji: string;
  bengali: string;
};

const unit1Examples: VocabularyExample[] = [
  { japanese: "わたしは ラナです。", romaji: "Watashi wa Rana desu.", bengali: "আমি রানা।" },
  { japanese: "あなたは がくせいですか。", romaji: "Anata wa gakusei desu ka.", bengali: "আপনি কি শিক্ষার্থী?" },
  { japanese: "あのひとは せんせいです。", romaji: "Ano hito wa sensei desu.", bengali: "ওই ব্যক্তি শিক্ষক।" },
  { japanese: "たなかさんは にほんじんです。", romaji: "Tanaka-san wa Nihon-jin desu.", bengali: "তানাকা-সান জাপানি।" },
  { japanese: "はなちゃんは ごさいです。", romaji: "Hana-chan wa go-sai desu.", bengali: "হানা-চানের বয়স পাঁচ বছর।" },
  { japanese: "わたしは バングラデシュじんです。", romaji: "Watashi wa Banguradeshu-jin desu.", bengali: "আমি বাংলাদেশি।" },
  { japanese: "ミラーさんは せんせいです。", romaji: "Miraa-san wa sensei desu.", bengali: "মিলার-সান শিক্ষক।" },
  { japanese: "わたしは にほんごの きょうしです。", romaji: "Watashi wa Nihongo no kyoushi desu.", bengali: "আমি জাপানি ভাষার শিক্ষক।" },
  { japanese: "アリさんは だいがくの がくせいです。", romaji: "Ari-san wa daigaku no gakusei desu.", bengali: "আলি-সান বিশ্ববিদ্যালয়ের শিক্ষার্থী।" },
  { japanese: "わたしは かいしゃいんです。", romaji: "Watashi wa kaishain desu.", bengali: "আমি কোম্পানির কর্মচারী।" },
  { japanese: "サントスさんは IMCの しゃいんです。", romaji: "Santosu-san wa IMC no shain desu.", bengali: "সান্তোস-সান IMC-এর কর্মচারী।" },
  { japanese: "マリアさんは ぎんこういんです。", romaji: "Maria-san wa ginkouin desu.", bengali: "মারিয়া-সান ব্যাংকের কর্মচারী।" },
  { japanese: "カリムさんは いしゃです。", romaji: "Karimu-san wa isha desu.", bengali: "করিম-সান ডাক্তার।" },
  { japanese: "ワンさんは けんきゅうしゃです。", romaji: "Wan-san wa kenkyuusha desu.", bengali: "ওয়াং-সান গবেষক।" },
  { japanese: "さくらだいがくは とうきょうです。", romaji: "Sakura daigaku wa Toukyou desu.", bengali: "সাকুরা বিশ্ববিদ্যালয় টোকিওতে।" },
  { japanese: "こうべびょういんは おおきいです。", romaji: "Koube byouin wa ookii desu.", bengali: "কোবে হাসপাতাল বড়।" },
  { japanese: "あのかたは どなたですか。", romaji: "Ano kata wa donata desu ka.", bengali: "ওই ভদ্রলোক/ভদ্রমহিলা কে?" },
  { japanese: "わたしは にじゅうごさいです。", romaji: "Watashi wa nijuu-go-sai desu.", bengali: "আমার বয়স পঁচিশ বছর।" },
  { japanese: "おいくつですか。", romaji: "Oikutsu desu ka.", bengali: "আপনার বয়স কত?" },
  { japanese: "はい、がくせいです。", romaji: "Hai, gakusei desu.", bengali: "হ্যাঁ, আমি শিক্ষার্থী।" },
  { japanese: "いいえ、せんせいでは ありません。", romaji: "Iie, sensei dewa arimasen.", bengali: "না, আমি শিক্ষক নই।" },
  { japanese: "スミスさんは アメリカから きました。", romaji: "Sumisu-san wa Amerika kara kimashita.", bengali: "স্মিথ-সান আমেরিকা থেকে এসেছেন।" },
  { japanese: "ベーカーさんは イギリスじんです。", romaji: "Beekaa-san wa Igirisu-jin desu.", bengali: "বেকার-সান ব্রিটিশ।" },
  { japanese: "ラオさんは インドから きました。", romaji: "Rao-san wa Indo kara kimashita.", bengali: "রাও-সান ভারত থেকে এসেছেন।" },
  { japanese: "ディアさんは インドネシアじんです。", romaji: "Dia-san wa Indoneshia-jin desu.", bengali: "দিয়া-সান ইন্দোনেশীয়।" },
  { japanese: "キムさんは かんこくじんです。", romaji: "Kimu-san wa Kankoku-jin desu.", bengali: "কিম-সান দক্ষিণ কোরীয়।" },
  { japanese: "ワットさんは タイから きました。", romaji: "Watto-san wa Tai kara kimashita.", bengali: "ওয়াত-সান থাইল্যান্ড থেকে এসেছেন।" },
  { japanese: "ワンさんは ちゅうごくじんです。", romaji: "Wan-san wa Chuugoku-jin desu.", bengali: "ওয়াং-সান চীনা।" },
  { japanese: "シュミットさんは ドイツじんです。", romaji: "Shumitto-san wa Doitsu-jin desu.", bengali: "শুমিট-সান জার্মান।" },
  { japanese: "たなかさんは にほんから きました。", romaji: "Tanaka-san wa Nihon kara kimashita.", bengali: "তানাকা-সান জাপান থেকে এসেছেন।" },
  { japanese: "サントスさんは ブラジルじんです。", romaji: "Santosu-san wa Burajiru-jin desu.", bengali: "সান্তোস-সান ব্রাজিলীয়।" },
  { japanese: "わたしは IMCの しゃいんです。", romaji: "Watashi wa IMC no shain desu.", bengali: "আমি IMC-এর কর্মচারী।" },
  { japanese: "パワーでんきは にほんの かいしゃです。", romaji: "Pawaa Denki wa Nihon no kaisha desu.", bengali: "Power Electric একটি জাপানি কোম্পানি।" },
  { japanese: "ブラジルエアーの しゃいんです。", romaji: "Burajiru Eaa no shain desu.", bengali: "আমি Brazil Air-এর কর্মচারী।" },
  { japanese: "AKCは アメリカの かいしゃです。", romaji: "AKC wa Amerika no kaisha desu.", bengali: "AKC একটি আমেরিকান কোম্পানি।" },
  { japanese: "カリムさんは こうべびょういんの いしゃです。", romaji: "Karimu-san wa Koube byouin no isha desu.", bengali: "করিম-সান কোবে হাসপাতালের ডাক্তার।" },
  { japanese: "わたしは さくらだいがくの がくせいです。", romaji: "Watashi wa Sakura daigaku no gakusei desu.", bengali: "আমি সাকুরা বিশ্ববিদ্যালয়ের শিক্ষার্থী।" },
  { japanese: "ミラーさんは ふじだいがくの きょうしです。", romaji: "Miraa-san wa Fuji daigaku no kyoushi desu.", bengali: "মিলার-সান ফুজি বিশ্ববিদ্যালয়ের শিক্ষক।" },
  { japanese: "わたしの しごとは エンジニアです。", romaji: "Watashi no shigoto wa enjinia desu.", bengali: "আমার পেশা ইঞ্জিনিয়ার।" },
  { japanese: "おくには どちらですか。", romaji: "Okuni wa dochira desu ka.", bengali: "আপনার দেশ কোনটি?" },
];

const unit2Examples: VocabularyExample[] = [
  { japanese: "これは 本です。", romaji: "Kore wa hon desu.", bengali: "এটি একটি বই।" },
  { japanese: "それは 辞書です。", romaji: "Sore wa jisho desu.", bengali: "সেটি একটি অভিধান।" },
  { japanese: "あれは テレビです。", romaji: "Are wa terebi desu.", bengali: "ওটি একটি টেলিভিশন।" },
  { japanese: "この本は おもしろいです。", romaji: "Kono hon wa omoshiroi desu.", bengali: "এই বইটি মজার।" },
  { japanese: "そのノートは 新しいです。", romaji: "Sono nooto wa atarashii desu.", bengali: "সেই খাতাটি নতুন।" },
  { japanese: "あの車は ミラーさんのです。", romaji: "Ano kuruma wa Miraa-san no desu.", bengali: "ঐ গাড়িটি মিলার-সানের।" },
  { japanese: "これは 日本語の 本です。", romaji: "Kore wa Nihongo no hon desu.", bengali: "এটি জাপানি ভাষার বই।" },
  { japanese: "これは 英語の 辞書です。", romaji: "Kore wa Eigo no jisho desu.", bengali: "এটি ইংরেজি ভাষার অভিধান।" },
  { japanese: "そのノートは わたしのです。", romaji: "Sono nooto wa watashi no desu.", bengali: "সেই খাতাটি আমার।" },
  { japanese: "これは きょうの 新聞です。", romaji: "Kore wa kyou no shinbun desu.", bengali: "এটি আজকের সংবাদপত্র।" },
  { japanese: "この雑誌は 日本のです。", romaji: "Kono zasshi wa Nihon no desu.", bengali: "এই ম্যাগাজিনটি জাপানের।" },
  { japanese: "そのかばんは だれのですか。", romaji: "Sono kaban wa dare no desu ka.", bengali: "সেই ব্যাগটি কার?" },
  { japanese: "これは 会社の 電話です。", romaji: "Kore wa kaisha no denwa desu.", bengali: "এটি কোম্পানির টেলিফোন।" },
  { japanese: "あれは 新しい テレビです。", romaji: "Are wa atarashii terebi desu.", bengali: "ওটি নতুন টেলিভিশন।" },
  { japanese: "このカメラは 日本のです。", romaji: "Kono kamera wa Nihon no desu.", bengali: "এই ক্যামেরাটি জাপানের।" },
  { japanese: "それは IMCの コンピューターです。", romaji: "Sore wa IMC no konpyuutaa desu.", bengali: "সেটি IMC-এর কম্পিউটার।" },
  { japanese: "あの車は だれのですか。", romaji: "Ano kuruma wa dare no desu ka.", bengali: "ঐ গাড়িটি কার?" },
  { japanese: "これは チョコレートです。どうぞ。", romaji: "Kore wa chokoreeto desu. Douzo.", bengali: "এটি চকলেট। নিন।" },
  { japanese: "コーヒーも どうぞ。", romaji: "Koohii mo douzo.", bengali: "কফিও নিন।" },
  { japanese: "これは 京都の お土産です。", romaji: "Kore wa Kyouto no omiyage desu.", bengali: "এটি কিয়োটোর স্মারক উপহার।" },
  { japanese: "これは 英語の 本です。", romaji: "Kore wa Eigo no hon desu.", bengali: "এটি ইংরেজি ভাষার বই।" },
  { japanese: "これは 何ですか。", romaji: "Kore wa nan desu ka.", bengali: "এটি কী?" },
  { japanese: "これは どうぞ。", romaji: "Kore wa douzo.", bengali: "এটি গ্রহণ করুন।" },
  { japanese: "ありがとうございます。", romaji: "Arigatou gozaimasu.", bengali: "অনেক ধন্যবাদ।" },
  { japanese: "どういたしまして。", romaji: "Dou itashimashite.", bengali: "স্বাগতম; কোনো সমস্যা নেই।" },
  { japanese: "すみません。これは だれのですか。", romaji: "Sumimasen. Kore wa dare no desu ka.", bengali: "মাফ করবেন, এটি কার?" },
  { japanese: "気にしないでください。", romaji: "Ki ni shinaide kudasai.", bengali: "চিন্তা করবেন না।" },
  { japanese: "はい、そうです。", romaji: "Hai, sou desu.", bengali: "হ্যাঁ, তাই।" },
  { japanese: "いいえ、ちがいます。", romaji: "Iie, chigaimasu.", bengali: "না, তা নয়।" },
  { japanese: "あ、これは わたしのです。", romaji: "A, kore wa watashi no desu.", bengali: "ওহ্, এটি আমার।" },
];

const unit3Examples: VocabularyExample[] = [
  { japanese: "ここは 受付です。", romaji: "Koko wa uketsuke desu.", bengali: "এখানে reception।" },
  { japanese: "そこは ロビーです。", romaji: "Soko wa robii desu.", bengali: "সেখানে lobby।" },
  { japanese: "あそこは 食堂です。", romaji: "Asoko wa shokudou desu.", bengali: "ওখানে ক্যান্টিন।" },
  { japanese: "トイレは どこですか。", romaji: "Toire wa doko desu ka.", bengali: "টয়লেট কোথায়?" },
  { japanese: "エレベーターは こちらです。", romaji: "Erebeetaa wa kochira desu.", bengali: "লিফট এই দিকে।" },
  { japanese: "会議室は そちらです。", romaji: "Kaigishitsu wa sochira desu.", bengali: "সভাকক্ষ ওই দিকে।" },
  { japanese: "お手洗いは あちらです。", romaji: "Otearai wa achira desu.", bengali: "বিশ্রামাগার ওই দিকে।" },
  { japanese: "受付は どちらですか。", romaji: "Uketsuke wa dochira desu ka.", bengali: "Reception কোন দিকে?" },
  { japanese: "教室は ここです。", romaji: "Kyoushitsu wa koko desu.", bengali: "শ্রেণিকক্ষ এখানে।" },
  { japanese: "食堂に 自動販売機が あります。", romaji: "Shokudou ni jidouhanbaiki ga arimasu.", bengali: "ক্যান্টিনে vending machine আছে।" },
  { japanese: "山田さんは 事務所に います。", romaji: "Yamada-san wa jimusho ni imasu.", bengali: "ইয়ামাদা অফিসে আছেন।" },
  { japanese: "会議室は あそこです。", romaji: "Kaigishitsu wa asoko desu.", bengali: "সভাকক্ষ ওখানে।" },
  { japanese: "受付に 田中さんが います。", romaji: "Uketsuke ni Tanaka-san ga imasu.", bengali: "Reception-এ তানাকা আছেন।" },
  { japanese: "ロビーに 電話が あります。", romaji: "Robii ni denwa ga arimasu.", bengali: "Lobby-তে টেলিফোন আছে।" },
  { japanese: "この部屋は 会議室です。", romaji: "Kono heya wa kaigishitsu desu.", bengali: "এই ঘরটি সভাকক্ষ।" },
  { japanese: "お手洗いは どちらですか。", romaji: "Otearai wa dochira desu ka.", bengali: "বিশ্রামাগার কোন দিকে?" },
  { japanese: "階段は エレベーターの となりです。", romaji: "Kaidan wa erebeetaa no tonari desu.", bengali: "সিঁড়ি lift-এর পাশে।" },
  { japanese: "エレベーターは あちらです。", romaji: "Erebeetaa wa achira desu.", bengali: "Lift ওই দিকে।" },
  { japanese: "エスカレーターは そこです。", romaji: "Esukareetaa wa soko desu.", bengali: "Escalator সেখানে।" },
  { japanese: "自動販売機は ロビーに あります。", romaji: "Jidouhanbaiki wa robii ni arimasu.", bengali: "Vending machine lobby-তে আছে।" },
  { japanese: "電話は 事務所に あります。", romaji: "Denwa wa jimusho ni arimasu.", bengali: "Telephone অফিসে আছে।" },
  { japanese: "IMCは 日本の会社です。", romaji: "IMC wa Nihon no kaisha desu.", bengali: "IMC একটি জাপানি কোম্পানি।" },
  { japanese: "お国は どちらですか。", romaji: "Okuni wa dochira desu ka.", bengali: "আপনার দেশ কোনটি?" },
  { japanese: "うちは 東京です。", romaji: "Uchi wa Toukyou desu.", bengali: "আমার বাড়ি টোকিওতে।" },
  { japanese: "カメラ売り場は 五階です。", romaji: "Kamera uriba wa go-kai desu.", bengali: "Camera counter পঞ্চম তলায়।" },
  { japanese: "食堂は 地下です。", romaji: "Shokudou wa chika desu.", bengali: "Canteen basement-এ।" },
  { japanese: "会議室は 三階です。", romaji: "Kaigishitsu wa san-gai desu.", bengali: "Meeting room তৃতীয় তলায়।" },
  { japanese: "受付は 何階ですか。", romaji: "Uketsuke wa nan-gai desu ka.", bengali: "Reception কোন তলায়?" },
  { japanese: "このワインは いくらですか。", romaji: "Kono wain wa ikura desu ka.", bengali: "এই wine-এর দাম কত?" },
  { japanese: "これは 百円です。", romaji: "Kore wa hyaku-en desu.", bengali: "এটির দাম ১০০ yen।" },
  { japanese: "そのネクタイは 千円です。", romaji: "Sono nekutai wa sen-en desu.", bengali: "সেই necktie-এর দাম ১,০০০ yen।" },
  { japanese: "このカメラは 二万円です。", romaji: "Kono kamera wa ni-man-en desu.", bengali: "এই camera-র দাম ২০,০০০ yen।" },
  { japanese: "このかばんは 七千三百円です。", romaji: "Kono kaban wa nana-sen san-byaku-en desu.", bengali: "এই bag-এর দাম ৭,৩০০ yen।" },
  { japanese: "靴売り場は どちらですか。", romaji: "Kutsu uriba wa dochira desu ka.", bengali: "জুতার counter কোন দিকে?" },
  { japanese: "このネクタイは イタリアのです。", romaji: "Kono nekutai wa Itaria no desu.", bengali: "এই necktie-টি ইতালির।" },
  { japanese: "日本のワインは ありますか。", romaji: "Nihon no wain wa arimasu ka.", bengali: "Japanese wine আছে কি?" },
];

const unit4Examples: VocabularyExample[] = [
  { japanese: "毎朝 6時に 起きます。", romaji: "Maiasa roku-ji ni okimasu.", bengali: "প্রতিদিন সকাল ৬টায় উঠি।" },
  { japanese: "毎晩 11時に 寝ます。", romaji: "Maiban juuichi-ji ni nemasu.", bengali: "প্রতি রাত ১১টায় ঘুমাই।" },
  { japanese: "9時から 5時まで 働きます。", romaji: "Ku-ji kara go-ji made hatarakimasu.", bengali: "৯টা থেকে ৫টা পর্যন্ত কাজ করি।" },
  { japanese: "日曜日に 休みます。", romaji: "Nichiyoubi ni yasumimasu.", bengali: "রবিবার বিশ্রাম নিই।" },
  { japanese: "毎晩 日本語を 勉強します。", romaji: "Maiban Nihongo o benkyou shimasu.", bengali: "প্রতি রাতে জাপানি পড়ি।" },
  { japanese: "仕事は 5時に 終わります。", romaji: "Shigoto wa go-ji ni owarimasu.", bengali: "কাজ ৫টায় শেষ হয়।" },
  { japanese: "デパートは 10時からです。", romaji: "Depaato wa juu-ji kara desu.", bengali: "ডিপার্টমেন্ট স্টোর ১০টা থেকে খোলে।" },
  { japanese: "銀行は 3時に 終わります。", romaji: "Ginkou wa san-ji ni owarimasu.", bengali: "ব্যাংক ৩টায় বন্ধ হয়।" },
  { japanese: "郵便局は どこですか。", romaji: "Yuubinkyoku wa doko desu ka.", bengali: "ডাকঘর কোথায়?" },
  { japanese: "図書館は 月曜日に 休みます。", romaji: "Toshokan wa getsuyoubi ni yasumimasu.", bengali: "লাইব্রেরি সোমবার বন্ধ থাকে।" },
  { japanese: "美術館は 9時から 5時までです。", romaji: "Bijutsukan wa ku-ji kara go-ji made desu.", bengali: "শিল্প জাদুঘর ৯টা থেকে ৫টা পর্যন্ত।" },
  { japanese: "今 何時ですか。", romaji: "Ima nan-ji desu ka.", bengali: "এখন কয়টা?" },
  { japanese: "今 7時です。", romaji: "Ima shichi-ji desu.", bengali: "এখন ৭টা।" },
  { japanese: "7時10分です。", romaji: "Shichi-ji juppun desu.", bengali: "এখন ৭টা ১০ মিনিট।" },
  { japanese: "6時半に 起きます。", romaji: "Roku-ji han ni okimasu.", bengali: "সাড়ে ৬টায় উঠি।" },
  { japanese: "今 何時ですか。", romaji: "Ima nan-ji desu ka.", bengali: "এখন কয়টা?" },
  { japanese: "あと 何分ですか。", romaji: "Ato nan-pun desu ka.", bengali: "আর কত মিনিট?" },
  { japanese: "午前 8時から 働きます。", romaji: "Gozen hachi-ji kara hatarakimasu.", bengali: "সকাল ৮টা থেকে কাজ করি।" },
  { japanese: "会議は 午後 2時です。", romaji: "Kaigi wa gogo ni-ji desu.", bengali: "মিটিং দুপুর ২টায়।" },
  { japanese: "朝 6時に 起きます。", romaji: "Asa roku-ji ni okimasu.", bengali: "সকাল ৬টায় উঠি।" },
  { japanese: "昼に 休みます。", romaji: "Hiru ni yasumimasu.", bengali: "দুপুরে বিশ্রাম নিই।" },
  { japanese: "晩 11時に 寝ます。", romaji: "Ban juuichi-ji ni nemasu.", bengali: "রাত ১১টায় ঘুমাই।" },
  { japanese: "おととい 休みました。", romaji: "Ototoi yasumimashita.", bengali: "গত পরশু ছুটি নিয়েছিলাম।" },
  { japanese: "昨日 勉強しました。", romaji: "Kinou benkyou shimashita.", bengali: "গতকাল পড়াশোনা করেছি।" },
  { japanese: "今日 働きます。", romaji: "Kyou hatarakimasu.", bengali: "আজ কাজ করব।" },
  { japanese: "明日 休みます。", romaji: "Ashita yasumimasu.", bengali: "আগামীকাল বিশ্রাম নেব।" },
  { japanese: "あさって 試験が あります。", romaji: "Asatte shiken ga arimasu.", bengali: "আগামী পরশু পরীক্ষা আছে।" },
  { japanese: "今朝 6時に 起きました。", romaji: "Kesa roku-ji ni okimashita.", bengali: "আজ সকালে ৬টায় উঠেছি।" },
  { japanese: "今晩 日本語を 勉強します。", romaji: "Konban Nihongo o benkyou shimasu.", bengali: "আজ রাতে জাপানি পড়ব।" },
  { japanese: "日曜日は 休みです。", romaji: "Nichiyoubi wa yasumi desu.", bengali: "রবিবার ছুটি।" },
  { japanese: "昼休みは 12時から 1時までです。", romaji: "Hiruyasumi wa juu-ni-ji kara ichi-ji made desu.", bengali: "দুপুরের বিরতি ১২টা থেকে ১টা।" },
  { japanese: "試験は 金曜日です。", romaji: "Shiken wa kinyoubi desu.", bengali: "পরীক্ষা শুক্রবার।" },
  { japanese: "会議は 何時ですか。", romaji: "Kaigi wa nan-ji desu ka.", bengali: "মিটিং কয়টায়?" },
  { japanese: "映画は 7時からです。", romaji: "Eiga wa shichi-ji kara desu.", bengali: "সিনেমা ৭টা থেকে।" },
  { japanese: "毎朝 6時半に 起きます。", romaji: "Maiasa roku-ji han ni okimasu.", bengali: "প্রতি সকাল সাড়ে ৬টায় উঠি।" },
  { japanese: "毎晩 11時に 寝ます。", romaji: "Maiban juuichi-ji ni nemasu.", bengali: "প্রতি রাত ১১টায় ঘুমাই।" },
  { japanese: "毎日 日本語を 勉強します。", romaji: "Mainichi Nihongo o benkyou shimasu.", bengali: "প্রতিদিন জাপানি পড়ি।" },
  { japanese: "月曜日に 働きます。", romaji: "Getsuyoubi ni hatarakimasu.", bengali: "সোমবার কাজ করি।" },
  { japanese: "火曜日に 会議が あります。", romaji: "Kayoubi ni kaigi ga arimasu.", bengali: "মঙ্গলবার মিটিং আছে।" },
  { japanese: "水曜日は 休みです。", romaji: "Suiyoubi wa yasumi desu.", bengali: "বুধবার ছুটি।" },
  { japanese: "木曜日に 勉強します。", romaji: "Mokuyoubi ni benkyou shimasu.", bengali: "বৃহস্পতিবার পড়াশোনা করি।" },
  { japanese: "金曜日に 試験が あります。", romaji: "Kinyoubi ni shiken ga arimasu.", bengali: "শুক্রবার পরীক্ষা আছে।" },
  { japanese: "土曜日に 映画を 見ます。", romaji: "Doyoubi ni eiga o mimasu.", bengali: "শনিবার সিনেমা দেখি।" },
  { japanese: "日曜日に 休みます。", romaji: "Nichiyoubi ni yasumimasu.", bengali: "রবিবার বিশ্রাম নিই।" },
  { japanese: "休みは 何曜日ですか。", romaji: "Yasumi wa nan-youbi desu ka.", bengali: "ছুটি কী বার?" },
  { japanese: "銀行は 9時からです。", romaji: "Ginkou wa ku-ji kara desu.", bengali: "ব্যাংক ৯টা থেকে খোলে।" },
  { japanese: "図書館は 5時までです。", romaji: "Toshokan wa go-ji made desu.", bengali: "লাইব্রেরি ৫টা পর্যন্ত।" },
  { japanese: "休みは 土曜日と 日曜日です。", romaji: "Yasumi wa doyoubi to nichiyoubi desu.", bengali: "ছুটি শনিবার ও রবিবার।" },
  { japanese: "毎日 勉強します。大変ですね。", romaji: "Mainichi benkyou shimasu. Taihen desu ne.", bengali: "প্রতিদিন পড়েন—কষ্টকর, তাই না!" },
  { japanese: "電話番号は 03-1234-5678です。", romaji: "Denwa bangou wa zero-san no ichi-ni-san-yon no go-roku-nana-hachi desu.", bengali: "ফোন নম্বর 03-1234-5678।" },
  { japanese: "会社は 何番ですか。", romaji: "Kaisha wa nan-ban desu ka.", bengali: "কোম্পানির নম্বর কত?" },
  { japanese: "そちらは 何時ですか。", romaji: "Sochira wa nan-ji desu ka.", bengali: "আপনাদের ওখানে কয়টা?" },
  { japanese: "ニューヨークは 午前 9時です。", romaji: "Nyuuyooku wa gozen ku-ji desu.", bengali: "নিউইয়র্কে সকাল ৯টা।" },
  { japanese: "北京は 今 午後 3時です。", romaji: "Pekin wa ima gogo san-ji desu.", bengali: "বেইজিংয়ে এখন দুপুর ৩টা।" },
  { japanese: "ロサンゼルスは 日曜日です。", romaji: "Rosanzerusu wa nichiyoubi desu.", bengali: "লস অ্যাঞ্জেলেসে রবিবার।" },
  { japanese: "ロンドンは 今 何時ですか。", romaji: "Rondon wa ima nan-ji desu ka.", bengali: "লন্ডনে এখন কয়টা?" },
];

const unit5Examples: VocabularyExample[] = [
  {japanese:"東京へ 行きます。",romaji:"Toukyou e ikimasu.",bengali:"টোকিও যাই।"},{japanese:"バングラデシュから 来ました。",romaji:"Banguradeshu kara kimashita.",bengali:"বাংলাদেশ থেকে এসেছি।"},{japanese:"毎日 うちへ 帰ります。",romaji:"Mainichi uchi e kaerimasu.",bengali:"প্রতিদিন বাড়ি ফিরি।"},{japanese:"バスで 学校へ 行きます。",romaji:"Basu de gakkou e ikimasu.",bengali:"বাসে স্কুলে যাই।"},{japanese:"日曜日に スーパーへ 行きます。",romaji:"Nichiyoubi ni suupaa e ikimasu.",bengali:"রবিবার সুপারমার্কেটে যাই।"},{japanese:"駅で 友達に 会いました。",romaji:"Eki de tomodachi ni aimashita.",bengali:"স্টেশনে বন্ধুর সঙ্গে দেখা হয়েছে।"},
  {japanese:"飛行機で 日本へ 来ました。",romaji:"Hikouki de Nihon e kimashita.",bengali:"বিমানে জাপানে এসেছি।"},{japanese:"船で 九州へ 行きます。",romaji:"Fune de Kyuushuu e ikimasu.",bengali:"জাহাজে কিউশু যাই।"},{japanese:"電車で 会社へ 行きます。",romaji:"Densha de kaisha e ikimasu.",bengali:"ট্রেনে কোম্পানিতে যাই।"},{japanese:"地下鉄で 駅へ 行きます。",romaji:"Chikatetsu de eki e ikimasu.",bengali:"পাতাল রেলে স্টেশনে যাই।"},{japanese:"新幹線で 大阪へ 行きます。",romaji:"Shinkansen de Oosaka e ikimasu.",bengali:"শিনকানসেনে ওসাকা যাই।"},{japanese:"バスで 学校へ 行きます。",romaji:"Basu de gakkou e ikimasu.",bengali:"বাসে স্কুলে যাই।"},
  {japanese:"タクシーで 駅へ 行きます。",romaji:"Takushii de eki e ikimasu.",bengali:"ট্যাক্সিতে স্টেশনে যাই।"},{japanese:"自転車で 大学へ 行きます。",romaji:"Jitensha de daigaku e ikimasu.",bengali:"সাইকেলে বিশ্ববিদ্যালয়ে যাই।"},{japanese:"駅から うちまで 歩いて 帰ります。",romaji:"Eki kara uchi made aruite kaerimasu.",bengali:"স্টেশন থেকে বাড়ি পর্যন্ত হেঁটে ফিরি।"},{japanese:"駅に 人が います。",romaji:"Eki ni hito ga imasu.",bengali:"স্টেশনে একজন মানুষ আছেন।"},{japanese:"友達と 京都へ 行きます。",romaji:"Tomodachi to Kyouto e ikimasu.",bengali:"বন্ধুর সঙ্গে কিয়োটো যাই।"},{japanese:"彼は 会社員です。",romaji:"Kare wa kaishain desu.",bengali:"সে কোম্পানির কর্মচারী।"},
  {japanese:"彼女は 東京へ 行きました。",romaji:"Kanojo wa Toukyou e ikimashita.",bengali:"সে টোকিও গিয়েছিল।"},{japanese:"家族と 日本へ 来ました。",romaji:"Kazoku to Nihon e kimashita.",bengali:"পরিবারের সঙ্গে জাপানে এসেছি।"},{japanese:"一人で 大阪へ 行きます。",romaji:"Hitori de Oosaka e ikimasu.",bengali:"একা ওসাকা যাই।"},{japanese:"先週 京都へ 行きました。",romaji:"Senshuu Kyouto e ikimashita.",bengali:"গত সপ্তাহে কিয়োটো গিয়েছিলাম।"},{japanese:"今週は どこへも 行きません。",romaji:"Konshuu wa doko e mo ikimasen.",bengali:"এই সপ্তাহে কোথাও যাব না।"},{japanese:"来週 東京へ 行きます。",romaji:"Raishuu Toukyou e ikimasu.",bengali:"আগামী সপ্তাহে টোকিও যাব।"},
  {japanese:"先月 日本へ 来ました。",romaji:"Sengetsu Nihon e kimashita.",bengali:"গত মাসে জাপানে এসেছি।"},{japanese:"今月 大阪へ 行きます。",romaji:"Kongetsu Oosaka e ikimasu.",bengali:"এই মাসে ওসাকা যাব।"},{japanese:"来月 国へ 帰ります。",romaji:"Raigetsu kuni e kaerimasu.",bengali:"আগামী মাসে দেশে ফিরব।"},{japanese:"去年 日本へ 来ました。",romaji:"Kyonen Nihon e kimashita.",bengali:"গত বছর জাপানে এসেছি।"},{japanese:"今年 京都へ 行きます。",romaji:"Kotoshi Kyouto e ikimasu.",bengali:"এই বছর কিয়োটো যাব।"},{japanese:"来年 国へ 帰ります。",romaji:"Rainen kuni e kaerimasu.",bengali:"আগামী বছর দেশে ফিরব।"},
  {japanese:"2026年に 日本へ 来ました。",romaji:"Nisen nijuu-roku-nen ni Nihon e kimashita.",bengali:"২০২৬ সালে জাপানে এসেছি।"},{japanese:"何年に 日本へ 来ましたか。",romaji:"Nan-nen ni Nihon e kimashita ka.",bengali:"কোন বছরে জাপানে এসেছেন?"},{japanese:"3月に 京都へ 行きます。",romaji:"San-gatsu ni Kyouto e ikimasu.",bengali:"মার্চে কিয়োটো যাব।"},{japanese:"何月に 国へ 帰りますか。",romaji:"Nan-gatsu ni kuni e kaerimasu ka.",bengali:"কোন মাসে দেশে ফিরবেন?"},{japanese:"1日に 大阪へ 行きます。",romaji:"Tsuitachi ni Oosaka e ikimasu.",bengali:"১ তারিখে ওসাকা যাব।"},{japanese:"2日に 東京へ 行きました。",romaji:"Futsuka ni Toukyou e ikimashita.",bengali:"২ তারিখে টোকিও গিয়েছিলাম।"},
  {japanese:"3日に 国へ 帰ります。",romaji:"Mikka ni kuni e kaerimasu.",bengali:"৩ তারিখে দেশে ফিরব।"},{japanese:"4日に 友達が 来ます。",romaji:"Yokka ni tomodachi ga kimasu.",bengali:"৪ তারিখে বন্ধু আসবে।"},{japanese:"5日に 京都へ 行きます。",romaji:"Itsuka ni Kyouto e ikimasu.",bengali:"৫ তারিখে কিয়োটো যাব।"},{japanese:"6日に 大阪へ 行きます。",romaji:"Muika ni Oosaka e ikimasu.",bengali:"৬ তারিখে ওসাকা যাব।"},{japanese:"7日に 日本へ 来ました。",romaji:"Nanoka ni Nihon e kimashita.",bengali:"৭ তারিখে জাপানে এসেছি।"},{japanese:"8日に 東京へ 行きます。",romaji:"Youka ni Toukyou e ikimasu.",bengali:"৮ তারিখে টোকিও যাব।"},
  {japanese:"9日に うちへ 帰ります。",romaji:"Kokonoka ni uchi e kaerimasu.",bengali:"৯ তারিখে বাড়ি ফিরব।"},{japanese:"10日に 友達と 行きます。",romaji:"Tooka ni tomodachi to ikimasu.",bengali:"১০ তারিখে বন্ধুর সঙ্গে যাব।"},{japanese:"14日に 試験が あります。",romaji:"Juuyokka ni shiken ga arimasu.",bengali:"১৪ তারিখে পরীক্ষা আছে।"},{japanese:"20日に 国へ 帰ります。",romaji:"Hatsuka ni kuni e kaerimasu.",bengali:"২০ তারিখে দেশে ফিরব।"},{japanese:"24日に 家族が 来ます。",romaji:"Nijuu-yokka ni kazoku ga kimasu.",bengali:"২৪ তারিখে পরিবার আসবে।"},{japanese:"25日に 東京へ 行きます。",romaji:"Nijuu-go-nichi ni Toukyou e ikimasu.",bengali:"২৫ তারিখে টোকিও যাব।"},
  {japanese:"今日は 何日ですか。",romaji:"Kyou wa nan-nichi desu ka.",bengali:"আজ কত তারিখ?"},{japanese:"いつ 日本へ 来ましたか。",romaji:"Itsu Nihon e kimashita ka.",bengali:"কখন জাপানে এসেছেন?"},{japanese:"誕生日は 7月7日です。",romaji:"Tanjoubi wa shichi-gatsu nanoka desu.",bengali:"জন্মদিন ৭ জুলাই।"},{japanese:"そうですね。来週 行きましょう。",romaji:"Sou desu ne. Raishuu ikimashou.",bengali:"হ্যাঁ, তাই। আগামী সপ্তাহে যাই।"},{japanese:"どうも ありがとうございました。",romaji:"Doumo arigatou gozaimashita.",bengali:"অনেক ধন্যবাদ।"},{japanese:"どういたしまして。",romaji:"Dou itashimashite.",bengali:"স্বাগতম/কোনো সমস্যা নেই।"},
  {japanese:"新幹線は 14番線です。",romaji:"Shinkansen wa juu-yon-bansen desu.",bengali:"শিনকানসেন ১৪ নম্বর প্ল্যাটফর্মে।"},{japanese:"次の 電車は 急行です。",romaji:"Tsugi no densha wa kyuukou desu.",bengali:"পরের ট্রেনটি rapid train।"},{japanese:"普通で 京都へ 行きます。",romaji:"Futsuu de Kyouto e ikimasu.",bengali:"লোকাল ট্রেনে কিয়োটো যাই।"},{japanese:"急行は 8時に 来ます。",romaji:"Kyuukou wa hachi-ji ni kimasu.",bengali:"Rapid train ৮টায় আসে।"},{japanese:"特急で 大阪へ 行きます。",romaji:"Tokkyuu de Oosaka e ikimasu.",bengali:"Express train-এ ওসাকা যাই।"},{japanese:"大阪城へ 行きました。",romaji:"Oosakajou e ikimashita.",bengali:"ওসাকা দুর্গে গিয়েছিলাম।"},
];

const unit6Examples: VocabularyExample[] = [
  {japanese:"毎朝 ごはんを 食べます。",romaji:"Maiasa gohan o tabemasu.",bengali:"প্রতি সকালে ভাত খাই।"},
  {japanese:"水を 飲みます。",romaji:"Mizu o nomimasu.",bengali:"পানি পান করি।"},
  {japanese:"たばこを 吸いません。",romaji:"Tabako o suimasen.",bengali:"আমি ধূমপান করি না।"},
  {japanese:"うちで テレビを 見ます。",romaji:"Uchi de terebi o mimasu.",bengali:"বাড়িতে টেলিভিশন দেখি।"},
  {japanese:"音楽を 聞きます。",romaji:"Ongaku o kikimasu.",bengali:"গান শুনি।"},
  {japanese:"図書館で 本を 読みます。",romaji:"Toshokan de hon o yomimasu.",bengali:"লাইব্রেরিতে বই পড়ি।"},
  {japanese:"手紙を 書きます。",romaji:"Tegami o kakimasu.",bengali:"চিঠি লিখি।"},
  {japanese:"デパートで おみやげを 買います。",romaji:"Depaato de omiyage o kaimasu.",bengali:"ডিপার্টমেন্ট স্টোরে স্মারক কিনি।"},
  {japanese:"京都で 写真を 撮ります。",romaji:"Kyouto de shashin o torimasu.",bengali:"কিয়োটোতে ছবি তুলি।"},
  {japanese:"毎日 宿題を します。",romaji:"Mainichi shukudai o shimasu.",bengali:"প্রতিদিন বাড়ির কাজ করি।"},
  {japanese:"駅で 友達に 会います。",romaji:"Eki de tomodachi ni aimasu.",bengali:"স্টেশনে বন্ধুর সঙ্গে দেখা করি।"},
  {japanese:"ごはんを 食べましょう。",romaji:"Gohan o tabemashou.",bengali:"চলুন খাবার খাই।"},
  {japanese:"朝ごはんを 食べました。",romaji:"Asagohan o tabemashita.",bengali:"সকালের খাবার খেয়েছি।"},
  {japanese:"いっしょに 昼ごはんを 食べませんか。",romaji:"Issho ni hirugohan o tabemasen ka.",bengali:"একসঙ্গে দুপুরের খাবার খাবেন?"},
  {japanese:"家族と 晩ごはんを 食べます。",romaji:"Kazoku to bangohan o tabemasu.",bengali:"পরিবারের সঙ্গে রাতের খাবার খাই।"},
  {japanese:"朝 パンを 食べます。",romaji:"Asa pan o tabemasu.",bengali:"সকালে রুটি খাই।"},
  {japanese:"卵を 二つ 買います。",romaji:"Tamago o futatsu kaimasu.",bengali:"দুটি ডিম কিনি।"},
  {japanese:"肉を 食べません。",romaji:"Niku o tabemasen.",bengali:"মাংস খাই না।"},
  {japanese:"魚を 食べます。",romaji:"Sakana o tabemasu.",bengali:"মাছ খাই।"},
  {japanese:"市場で 野菜を 買います。",romaji:"Ichiba de yasai o kaimasu.",bengali:"বাজারে শাকসবজি কিনি।"},
  {japanese:"果物を 毎日 食べます。",romaji:"Kudamono o mainichi tabemasu.",bengali:"প্রতিদিন ফল খাই।"},
  {japanese:"冷たい 水を 飲みます。",romaji:"Tsumetai mizu o nomimasu.",bengali:"ঠান্ডা পানি পান করি।"},
  {japanese:"お茶を 飲みませんか。",romaji:"Ocha o nomimasen ka.",bengali:"সবুজ চা খাবেন?"},
  {japanese:"紅茶を 飲みます。",romaji:"Koucha o nomimasu.",bengali:"ব্ল্যাক টি পান করি।"},
  {japanese:"牛乳を 飲みます。",romaji:"Gyuunyuu o nomimasu.",bengali:"দুধ পান করি।"},
  {japanese:"オレンジジュースを 買います。",romaji:"Orenji juusu o kaimasu.",bengali:"কমলার জুস কিনি।"},
  {japanese:"ビールを 飲みませんか。",romaji:"Biiru o nomimasen ka.",bengali:"বিয়ার পান করবেন?"},
  {japanese:"父は お酒を 飲みます。",romaji:"Chichi wa osake o nomimasu.",bengali:"বাবা সাকে পান করেন।"},
  {japanese:"ここで たばこを 吸いません。",romaji:"Koko de tabako o suimasen.",bengali:"এখানে ধূমপান করি না।"},
  {japanese:"友達に 手紙を 書きます。",romaji:"Tomodachi ni tegami o kakimasu.",bengali:"বন্ধুকে চিঠি লিখি।"},
  {japanese:"会社で レポートを 書きます。",romaji:"Kaisha de repooto o kakimasu.",bengali:"কোম্পানিতে রিপোর্ট লিখি।"},
  {japanese:"庭で 写真を 撮ります。",romaji:"Niwa de shashin o torimasu.",bengali:"বাগানে ছবি তুলি।"},
  {japanese:"うちで ビデオを 見ます。",romaji:"Uchi de bideo o mimasu.",bengali:"বাড়িতে ভিডিও দেখি।"},
  {japanese:"あの 店で パンを 買います。",romaji:"Ano mise de pan o kaimasu.",bengali:"ওই দোকানে রুটি কিনি।"},
  {japanese:"庭で お花見を します。",romaji:"Niwa de ohanami o shimasu.",bengali:"বাগানে চেরি ফুল দেখি।"},
  {japanese:"図書館で 宿題を します。",romaji:"Toshokan de shukudai o shimasu.",bengali:"লাইব্রেরিতে বাড়ির কাজ করি।"},
  {japanese:"日曜日に テニスを します。",romaji:"Nichiyoubi ni tenisu o shimasu.",bengali:"রবিবার টেনিস খেলি।"},
  {japanese:"友達と サッカーを します。",romaji:"Tomodachi to sakkaa o shimasu.",bengali:"বন্ধুর সঙ্গে ফুটবল খেলি।"},
  {japanese:"公園で お花見を します。",romaji:"Kouen de ohanami o shimasu.",bengali:"পার্কে চেরি ফুল দেখি।"},
  {japanese:"何を 食べますか。",romaji:"Nani o tabemasu ka.",bengali:"কী খাবেন?"},
  {japanese:"いっしょに 京都へ 行きませんか。",romaji:"Issho ni Kyouto e ikimasen ka.",bengali:"একসঙ্গে কিয়োটো যাবেন?"},
  {japanese:"すみません、今日は ちょっと…。",romaji:"Sumimasen, kyou wa chotto...",bengali:"দুঃখিত, আজ একটু অসুবিধা…।"},
  {japanese:"いつも コーヒーを 飲みます。",romaji:"Itsumo koohii o nomimasu.",bengali:"সবসময় কফি পান করি।"},
  {japanese:"時々 映画を 見ます。",romaji:"Tokidoki eiga o mimasu.",bengali:"মাঝে মাঝে সিনেমা দেখি।"},
  {japanese:"宿題を します。それから 本を 読みます。",romaji:"Shukudai o shimasu. Sorekara hon o yomimasu.",bengali:"বাড়ির কাজ করি। তারপর বই পড়ি।"},
  {japanese:"ええ、行きましょう。",romaji:"Ee, ikimashou.",bengali:"হ্যাঁ, চলুন যাই।"},
  {japanese:"いいですね。そうしましょう。",romaji:"Ii desu ne. Sou shimashou.",bengali:"বেশ ভালো। তাই করি চলুন।"},
  {japanese:"はい、分かりました。",romaji:"Hai, wakarimashita.",bengali:"হ্যাঁ, বুঝেছি।"},
  {japanese:"これは 何ですか。",romaji:"Kore wa nan desu ka.",bengali:"এটি কী?"},
  {japanese:"じゃ、また 明日。",romaji:"Ja, mata ashita.",bengali:"তাহলে, কাল আবার দেখা হবে।"},
  {japanese:"駅で 新聞を 買います。",romaji:"Eki de shinbun o kaimasu.",bengali:"স্টেশনে সংবাদপত্র কিনি।"},
  {japanese:"学校で 日本語を 勉強します。",romaji:"Gakkou de Nihongo o benkyou shimasu.",bengali:"স্কুলে জাপানি পড়ি।"},
  {japanese:"市場で 魚を 買います。",romaji:"Ichiba de sakana o kaimasu.",bengali:"বাজারে মাছ কিনি।"},
  {japanese:"関西で 写真を 撮りました。",romaji:"Kansai de shashin o torimashita.",bengali:"কানসাইয়ে ছবি তুলেছিলাম।"},
  {japanese:"京都で おみやげを 買います。",romaji:"Kyouto de omiyage o kaimasu.",bengali:"কিয়োটোতে স্মারক কিনি।"},
  {japanese:"先生に 写真を 見せます。",romaji:"Sensei ni shashin o misemasu.",bengali:"শিক্ষককে ছবি দেখাই।"},
  {japanese:"冷たい 飲み物を 買います。",romaji:"Tsumetai nomimono o kaimasu.",bengali:"ঠান্ডা পানীয় কিনি।"},
  {japanese:"夜中に 水を 飲みました。",romaji:"Yonaka ni mizu o nomimashita.",bengali:"মধ্যরাতে পানি পান করেছিলাম।"},
  {japanese:"店は 9時までです。",romaji:"Mise wa ku-ji made desu.",bengali:"দোকান ৯টা পর্যন্ত খোলা।"},
  {japanese:"7時ごろ 晩ごはんを 食べます。",romaji:"Shichi-ji goro bangohan o tabemasu.",bengali:"প্রায় ৭টার দিকে রাতের খাবার খাই।"},
];

export function getMinnaN5VocabularyExample(unitNumber: number, index: number) {
  if (unitNumber === 1) return unit1Examples[index];
  if (unitNumber === 2) return unit2Examples[index];
  if (unitNumber === 3) return unit3Examples[index];
  if (unitNumber === 4) return unit4Examples[index];
  if (unitNumber === 5) return unit5Examples[index];
  if (unitNumber === 6) return unit6Examples[index];
  return undefined;
}
