export type UnitKanji = { kanji: string; meaning: string; readings: string; example: string };

export const minnaN5KanjiByUnit: Record<number, UnitKanji[]> = {
  1:[{kanji:"私",meaning:"আমি/ব্যক্তিগত",readings:"わたし · watashi",example:"私 は ハリムです。"},{kanji:"人",meaning:"মানুষ",readings:"ひと・じん・にん",example:"日本人 · にほんじん"},{kanji:"名",meaning:"নাম",readings:"な・めい",example:"名前 · なまえ"}],
  2:[{kanji:"本",meaning:"বই/মূল",readings:"ほん・もと",example:"この本 · このほん"},{kanji:"何",meaning:"কী",readings:"なに・なん",example:"何ですか · なんですか"},{kanji:"国",meaning:"দেশ",readings:"くに・こく",example:"お国 · おくに"}],
  3:[{kanji:"上",meaning:"উপরে",readings:"うえ・じょう",example:"机の上 · つくえのうえ"},{kanji:"下",meaning:"নিচে",readings:"した・か",example:"いすの下"},{kanji:"円",meaning:"Yen/বৃত্ত",readings:"えん",example:"百円 · ひゃくえん"}],
  4:[{kanji:"時",meaning:"সময়/ঘণ্টা",readings:"じ・とき",example:"七時 · しちじ"},{kanji:"分",meaning:"মিনিট/অংশ",readings:"ふん・ぶん",example:"十分 · じゅっぷん"},{kanji:"半",meaning:"অর্ধেক",readings:"はん",example:"七時半"}],
  5:[{kanji:"行",meaning:"যাওয়া",readings:"い・こう",example:"行きます · いきます"},{kanji:"来",meaning:"আসা",readings:"き・らい",example:"来ます · きます"},{kanji:"帰",meaning:"ফেরা",readings:"かえ・き",example:"帰ります"}],
  6:[{kanji:"食",meaning:"খাওয়া/খাদ্য",readings:"た・しょく",example:"食べます"},{kanji:"飲",meaning:"পান করা",readings:"の・いん",example:"飲みます"},{kanji:"見",meaning:"দেখা",readings:"み・けん",example:"見ます"}],
  7:[{kanji:"書",meaning:"লেখা",readings:"か・しょ",example:"書きます"},{kanji:"読",meaning:"পড়া",readings:"よ・どく",example:"読みます"},{kanji:"話",meaning:"কথা বলা",readings:"はな・わ",example:"話します"}],
  8:[{kanji:"大",meaning:"বড়",readings:"おお・だい",example:"大きい"},{kanji:"小",meaning:"ছোট",readings:"ちい・しょう",example:"小さい"},{kanji:"新",meaning:"নতুন",readings:"あたら・しん",example:"新しい"},{kanji:"古",meaning:"পুরোনো",readings:"ふる・こ",example:"古い"}],
  9:[{kanji:"好",meaning:"পছন্দ",readings:"す・こう",example:"好きです"},{kanji:"分",meaning:"বোঝা/ভাগ",readings:"わ・ぶん",example:"分かります"},{kanji:"音",meaning:"শব্দ",readings:"おと・おん",example:"音楽 · おんがく"}],
  10:[{kanji:"有",meaning:"থাকা/অধিকার",readings:"あ・ゆう",example:"有ります"},{kanji:"中",meaning:"ভিতরে/মাঝে",readings:"なか・ちゅう",example:"箱の中"},{kanji:"外",meaning:"বাইরে",readings:"そと・がい",example:"家の外"}],
  11:[{kanji:"一",meaning:"এক",readings:"いち・ひと",example:"一つ · ひとつ"},{kanji:"二",meaning:"দুই",readings:"に・ふた",example:"二人 · ふたり"},{kanji:"三",meaning:"তিন",readings:"さん・みっ",example:"三つ"},{kanji:"間",meaning:"সময়/ফাঁক",readings:"かん・あいだ",example:"二時間"}],
  12:[{kanji:"前",meaning:"আগে/সামনে",readings:"まえ・ぜん",example:"前の日"},{kanji:"高",meaning:"উঁচু/দামি",readings:"たか・こう",example:"高かったです"},{kanji:"安",meaning:"সস্তা/নিরাপদ",readings:"やす・あん",example:"安いです"}],
  13:[{kanji:"欲",meaning:"চাওয়া",readings:"ほ・よく",example:"欲しいです"},{kanji:"買",meaning:"কেনা",readings:"か・ばい",example:"買いたいです"},{kanji:"遊",meaning:"খেলা/ঘোরা",readings:"あそ・ゆう",example:"遊びに行きます"}],
  14:[{kanji:"待",meaning:"অপেক্ষা",readings:"ま・たい",example:"待ってください"},{kanji:"立",meaning:"দাঁড়ানো",readings:"た・りつ",example:"立っています"},{kanji:"使",meaning:"ব্যবহার",readings:"つか・し",example:"使ってください"}],
  15:[{kanji:"入",meaning:"প্রবেশ",readings:"はい・にゅう",example:"入ってもいいです"},{kanji:"出",meaning:"বের হওয়া",readings:"で・しゅつ",example:"出てはいけません"},{kanji:"住",meaning:"বাস করা",readings:"す・じゅう",example:"住んでいます"}],
  16:[{kanji:"朝",meaning:"সকাল",readings:"あさ・ちょう",example:"朝ごはん"},{kanji:"昼",meaning:"দুপুর",readings:"ひる・ちゅう",example:"昼休み"},{kanji:"夜",meaning:"রাত",readings:"よる・や",example:"夜になります"}],
  17:[{kanji:"忘",meaning:"ভুলে যাওয়া",readings:"わす・ぼう",example:"忘れないで"},{kanji:"持",meaning:"ধরা/সঙ্গে রাখা",readings:"も・じ",example:"持ってこなければ"},{kanji:"薬",meaning:"ওষুধ",readings:"くすり・やく",example:"薬を飲みます"}],
  18:[{kanji:"出",meaning:"বের হওয়া",readings:"で・しゅつ",example:"出ることができます"},{kanji:"前",meaning:"আগে",readings:"まえ・ぜん",example:"寝る前に"},{kanji:"作",meaning:"তৈরি",readings:"つく・さく",example:"料理を作る"}],
  19:[{kanji:"登",meaning:"ওঠা",readings:"のぼ・とう",example:"山に登ったこと"},{kanji:"休",meaning:"বিশ্রাম",readings:"やす・きゅう",example:"休んだり"},{kanji:"掃",meaning:"পরিষ্কার",readings:"そう",example:"掃除します"}],
  20:[{kanji:"言",meaning:"বলা",readings:"い・げん",example:"何と言った？"},{kanji:"思",meaning:"ভাবা",readings:"おも・し",example:"そう思う"},{kanji:"知",meaning:"জানা",readings:"し・ち",example:"知っている"}],
  21:[{kanji:"思",meaning:"মনে করা",readings:"おも・し",example:"いいと思います"},{kanji:"言",meaning:"বলা/উক্তি",readings:"い・げん",example:"行くと言いました"},{kanji:"意",meaning:"মত/ইচ্ছা",readings:"い",example:"意見 · いけん"}],
  22:[{kanji:"着",meaning:"পরা/পৌঁছানো",readings:"き・ちゃく",example:"着ている人"},{kanji:"働",meaning:"কাজ",readings:"はたら・どう",example:"働いている会社"},{kanji:"住",meaning:"বাস",readings:"す・じゅう",example:"住む町"}],
  23:[{kanji:"時",meaning:"যখন/সময়",readings:"とき・じ",example:"行く時"},{kanji:"回",meaning:"ঘোরা/বার",readings:"まわ・かい",example:"右へ回します"},{kanji:"開",meaning:"খোলা",readings:"あ・かい",example:"ドアが開きます"}],
  24:[{kanji:"手",meaning:"হাত",readings:"て・しゅ",example:"手伝います"},{kanji:"送",meaning:"পাঠানো",readings:"おく・そう",example:"駅まで送ります"},{kanji:"教",meaning:"শেখানো",readings:"おし・きょう",example:"教えてくれました"}],
  25:[{kanji:"終",meaning:"শেষ",readings:"お・しゅう",example:"仕事が終わったら"},{kanji:"雨",meaning:"বৃষ্টি",readings:"あめ・う",example:"雨が降っても"},{kanji:"連",meaning:"যোগ/সঙ্গে",readings:"れん・つ",example:"連絡します"},{kanji:"決",meaning:"সিদ্ধান্ত",readings:"き・けつ",example:"決めます"}],
};
