export type KanjiSentenceExample = {
  japanese: string;
  romaji: string;
  bengali: string;
};

const unit1KanjiExamples: Record<string, KanjiSentenceExample> = {
  私: { japanese: "私は ハリムです。", romaji: "Watashi wa Harimu desu.", bengali: "আমি হালিম।" },
  人: { japanese: "あの人は 先生です。", romaji: "Ano hito wa sensei desu.", bengali: "ওই ব্যক্তি শিক্ষক।" },
  方: { japanese: "あの方は どなたですか。", romaji: "Ano kata wa donata desu ka.", bengali: "ওই ভদ্রলোক/ভদ্রমহিলা কে?" },
  先: { japanese: "田中先生は 日本人です。", romaji: "Tanaka-sensei wa Nihon-jin desu.", bengali: "তানাকা-সেনসেই জাপানি।" },
  生: { japanese: "私は 大学生です。", romaji: "Watashi wa daigakusei desu.", bengali: "আমি বিশ্ববিদ্যালয়ের শিক্ষার্থী।" },
  教: { japanese: "ミラーさんは 日本語を 教えます。", romaji: "Miraa-san wa Nihongo o oshiemasu.", bengali: "মিলার-সান জাপানি ভাষা শেখান।" },
  師: { japanese: "私は 日本語の 教師です。", romaji: "Watashi wa Nihongo no kyoushi desu.", bengali: "আমি জাপানি ভাষার শিক্ষক।" },
  学: { japanese: "アリさんは 大学で 日本語を 学びます。", romaji: "Ari-san wa daigaku de Nihongo o manabimasu.", bengali: "আলি-সান বিশ্ববিদ্যালয়ে জাপানি ভাষা শেখেন।" },
  会: { japanese: "IMCは 日本の 会社です。", romaji: "IMC wa Nihon no kaisha desu.", bengali: "IMC একটি জাপানি কোম্পানি।" },
  社: { japanese: "サントスさんは 会社の 社員です。", romaji: "Santosu-san wa kaisha no shain desu.", bengali: "সান্তোস-সান কোম্পানির কর্মচারী।" },
  員: { japanese: "私は 会社員です。", romaji: "Watashi wa kaishain desu.", bengali: "আমি কোম্পানির কর্মচারী।" },
  銀: { japanese: "マリアさんは 銀行員です。", romaji: "Maria-san wa ginkouin desu.", bengali: "মারিয়া-সান ব্যাংকের কর্মচারী।" },
  行: { japanese: "父は 銀行員です。", romaji: "Chichi wa ginkouin desu.", bengali: "আমার বাবা ব্যাংকের কর্মচারী।" },
  医: { japanese: "カリムさんは 医者です。", romaji: "Karimu-san wa isha desu.", bengali: "করিম-সান ডাক্তার।" },
  者: { japanese: "ワンさんは 研究者です。", romaji: "Wan-san wa kenkyuusha desu.", bengali: "ওয়াং-সান গবেষক।" },
  研: { japanese: "研究者は 大学に います。", romaji: "Kenkyuusha wa daigaku ni imasu.", bengali: "গবেষক বিশ্ববিদ্যালয়ে আছেন।" },
  究: { japanese: "先生は 日本語を 研究します。", romaji: "Sensei wa Nihongo o kenkyuu shimasu.", bengali: "শিক্ষক জাপানি ভাষা নিয়ে গবেষণা করেন।" },
  大: { japanese: "私は さくら大学の 学生です。", romaji: "Watashi wa Sakura daigaku no gakusei desu.", bengali: "আমি সাকুরা বিশ্ববিদ্যালয়ের শিক্ষার্থী।" },
  病: { japanese: "病院は ここです。", romaji: "Byouin wa koko desu.", bengali: "হাসপাতাল এখানে।" },
  院: { japanese: "カリムさんは 神戸病院の 医者です。", romaji: "Karimu-san wa Koube byouin no isha desu.", bengali: "করিম-সান কোবে হাসপাতালের ডাক্তার।" },
  一: { japanese: "妹は 一歳です。", romaji: "Imouto wa issai desu.", bengali: "আমার ছোট বোনের বয়স এক বছর।" },
  歳: { japanese: "私は 二十五歳です。", romaji: "Watashi wa nijuu-go-sai desu.", bengali: "আমার বয়স পঁচিশ বছর।" },
  何: { japanese: "ミラーさんは 何歳ですか。", romaji: "Miraa-san wa nan-sai desu ka.", bengali: "মিলার-সানের বয়স কত?" },
  韓: { japanese: "キムさんは 韓国人です。", romaji: "Kimu-san wa Kankoku-jin desu.", bengali: "কিম-সান দক্ষিণ কোরীয়।" },
  国: { japanese: "お国は どちらですか。", romaji: "Okuni wa dochira desu ka.", bengali: "আপনার দেশ কোনটি?" },
  中: { japanese: "ワンさんは 中国人です。", romaji: "Wan-san wa Chuugoku-jin desu.", bengali: "ওয়াং-সান চীনা।" },
  日: { japanese: "田中さんは 日本人です。", romaji: "Tanaka-san wa Nihon-jin desu.", bengali: "তানাকা-সান জাপানি।" },
  本: { japanese: "ミラーさんは 日本から 来ました。", romaji: "Miraa-san wa Nihon kara kimashita.", bengali: "মিলার-সান জাপান থেকে এসেছেন।" },
  電: { japanese: "私は パワー電気の 社員です。", romaji: "Watashi wa Pawaa Denki no shain desu.", bengali: "আমি Power Electric-এর কর্মচারী।" },
  気: { japanese: "パワー電気は 日本の 会社です。", romaji: "Pawaa Denki wa Nihon no kaisha desu.", bengali: "Power Electric একটি জাপানি কোম্পানি।" },
  神: { japanese: "神戸病院は 大きいです。", romaji: "Koube byouin wa ookii desu.", bengali: "কোবে হাসপাতাল বড়।" },
  戸: { japanese: "カリムさんは 神戸に います。", romaji: "Karimu-san wa Koube ni imasu.", bengali: "করিম-সান কোবেতে আছেন।" },
  富: { japanese: "ミラーさんは 富士大学の 教師です。", romaji: "Miraa-san wa Fuji daigaku no kyoushi desu.", bengali: "মিলার-সান ফুজি বিশ্ববিদ্যালয়ের শিক্ষক।" },
  士: { japanese: "富士大学は 日本の 大学です。", romaji: "Fuji daigaku wa Nihon no daigaku desu.", bengali: "ফুজি বিশ্ববিদ্যালয় জাপানের একটি বিশ্ববিদ্যালয়।" },
  名: { japanese: "お名前は 何ですか。", romaji: "Onamae wa nan desu ka.", bengali: "আপনার নাম কী?" },
};

const unit2KanjiExamples: Record<string, KanjiSentenceExample> = {
  本: { japanese: "この本は おもしろいです。", romaji: "Kono hon wa omoshiroi desu.", bengali: "এই বইটি মজার।" },
  辞: { japanese: "これは 英語の 辞書です。", romaji: "Kore wa Eigo no jisho desu.", bengali: "এটি ইংরেজি ভাষার অভিধান।" },
  書: { japanese: "その辞書は わたしのです。", romaji: "Sono jisho wa watashi no desu.", bengali: "সেই অভিধানটি আমার।" },
  新: { japanese: "これは きょうの 新聞です。", romaji: "Kore wa kyou no shinbun desu.", bengali: "এটি আজকের সংবাদপত্র।" },
  聞: { japanese: "新聞は そこです。", romaji: "Shinbun wa soko desu.", bengali: "সংবাদপত্রটি সেখানে।" },
  雑: { japanese: "この雑誌は 日本のです。", romaji: "Kono zasshi wa Nihon no desu.", bengali: "এই ম্যাগাজিনটি জাপানের।" },
  誌: { japanese: "それは カメラの 雑誌です。", romaji: "Sore wa kamera no zasshi desu.", bengali: "সেটি ক্যামেরার ম্যাগাজিন।" },
  電: { japanese: "これは 会社の 電話です。", romaji: "Kore wa kaisha no denwa desu.", bengali: "এটি কোম্পানির টেলিফোন।" },
  話: { japanese: "あの電話は だれのですか。", romaji: "Ano denwa wa dare no desu ka.", bengali: "ঐ টেলিফোনটি কার?" },
  車: { japanese: "あの車は ミラーさんのです。", romaji: "Ano kuruma wa Miraa-san no desu.", bengali: "ঐ গাড়িটি মিলার-সানের।" },
  土: { japanese: "これは 京都の お土産です。", romaji: "Kore wa Kyouto no omiyage desu.", bengali: "এটি কিয়োটোর স্মারক উপহার।" },
  産: { japanese: "お土産は チョコレートです。", romaji: "Omiyage wa chokoreeto desu.", bengali: "স্মারক উপহারটি চকলেট।" },
  英: { japanese: "これは 英語の 本です。", romaji: "Kore wa Eigo no hon desu.", bengali: "এটি ইংরেজি ভাষার বই।" },
  語: { japanese: "英語の 辞書は これです。", romaji: "Eigo no jisho wa kore desu.", bengali: "ইংরেজি অভিধানটি এটি।" },
  何: { japanese: "これは 何ですか。", romaji: "Kore wa nan desu ka.", bengali: "এটি কী?" },
  気: { japanese: "気にしないでください。", romaji: "Ki ni shinaide kudasai.", bengali: "চিন্তা করবেন না।" },
};

const unit3KanjiExamples: Record<string, KanjiSentenceExample> = {
  場:{japanese:"この場所は 受付です。",romaji:"Kono basho wa uketsuke desu.",bengali:"এই জায়গাটি reception।"},所:{japanese:"お手洗いは どこですか。",romaji:"Otearai wa doko desu ka.",bengali:"Restroom কোথায়?"},
  教:{japanese:"先生は 教室に います。",romaji:"Sensei wa kyoushitsu ni imasu.",bengali:"শিক্ষক classroom-এ আছেন।"},室:{japanese:"会議室は あそこです。",romaji:"Kaigishitsu wa asoko desu.",bengali:"Meeting room ওখানে।"},
  食:{japanese:"食堂に 自動販売機が あります。",romaji:"Shokudou ni jidouhanbaiki ga arimasu.",bengali:"Canteen-এ vending machine আছে।"},堂:{japanese:"食堂は こちらです。",romaji:"Shokudou wa kochira desu.",bengali:"Canteen এই দিকে।"},
  事:{japanese:"事務所は 二階です。",romaji:"Jimusho wa nikai desu.",bengali:"Office দ্বিতীয় তলায়।"},務:{japanese:"山田さんは 事務所に います。",romaji:"Yamada-san wa jimusho ni imasu.",bengali:"ইয়ামাদা office-এ আছেন।"},
  会:{japanese:"会議室は どちらですか。",romaji:"Kaigishitsu wa dochira desu ka.",bengali:"Meeting room কোন দিকে?"},議:{japanese:"会議は 会議室です。",romaji:"Kaigi wa kaigishitsu desu.",bengali:"Meeting সভাকক্ষে।"},
  受:{japanese:"受付は ここです。",romaji:"Uketsuke wa koko desu.",bengali:"Reception এখানে।"},付:{japanese:"受付に 人が います。",romaji:"Uketsuke ni hito ga imasu.",bengali:"Reception-এ একজন আছেন।"},
  部:{japanese:"この部屋は 教室です。",romaji:"Kono heya wa kyoushitsu desu.",bengali:"এই room-টি classroom।"},屋:{japanese:"部屋に 電話が あります。",romaji:"Heya ni denwa ga arimasu.",bengali:"Room-এ telephone আছে।"},
  階:{japanese:"階段は あちらです。",romaji:"Kaidan wa achira desu.",bengali:"সিঁড়ি ওই দিকে।"},段:{japanese:"エレベーターは 階段の となりです。",romaji:"Erebeetaa wa kaidan no tonari desu.",bengali:"Lift সিঁড়ির পাশে।"},
  自:{japanese:"自動販売機は ロビーに あります。",romaji:"Jidouhanbaiki wa robii ni arimasu.",bengali:"Vending machine lobby-তে আছে।"},動:{japanese:"これは 自動販売機です。",romaji:"Kore wa jidouhanbaiki desu.",bengali:"এটি vending machine।"},
  販:{japanese:"会社に 自動販売機が あります。",romaji:"Kaisha ni jidouhanbaiki ga arimasu.",bengali:"Company-তে vending machine আছে।"},売:{japanese:"あそこに 自動販売機が あります。",romaji:"Asoko ni jidouhanbaiki ga arimasu.",bengali:"ওখানে vending machine আছে।"},機:{japanese:"自動販売機は そこです。",romaji:"Jidouhanbaiki wa soko desu.",bengali:"Vending machine সেখানে।"},
  電:{japanese:"電話は 事務所に あります。",romaji:"Denwa wa jimusho ni arimasu.",bengali:"Telephone office-এ আছে।"},話:{japanese:"ロビーに 電話が あります。",romaji:"Robii ni denwa ga arimasu.",bengali:"Lobby-তে telephone আছে।"},
  社:{japanese:"IMCは 日本の 会社です。",romaji:"IMC wa Nihon no kaisha desu.",bengali:"IMC একটি Japanese company।"},国:{japanese:"お国は どちらですか。",romaji:"Okuni wa dochira desu ka.",bengali:"আপনার দেশ কোনটি?"},
  地:{japanese:"食堂は 地下です。",romaji:"Shokudou wa chika desu.",bengali:"Canteen basement-এ।"},下:{japanese:"地下に 売り場が あります。",romaji:"Chika ni uriba ga arimasu.",bengali:"Basement-এ sales counter আছে।"},何:{japanese:"受付は 何階ですか。",romaji:"Uketsuke wa nan-gai desu ka.",bengali:"Reception কোন তলায়?"},
  百:{japanese:"これは 八百円です。",romaji:"Kore wa happyaku-en desu.",bengali:"এটির দাম ৮০০ yen।"},千:{japanese:"このワインは 二千円です。",romaji:"Kono wain wa ni-sen-en desu.",bengali:"এই wine-এর দাম ২,০০০ yen।"},万:{japanese:"カメラは 二万円です。",romaji:"Kamera wa ni-man-en desu.",bengali:"Camera-র দাম ২০,০০০ yen।"},円:{japanese:"二千五百円です。",romaji:"Ni-sen go-hyaku-en desu.",bengali:"দাম ২,৫০০ yen।"},
  靴:{japanese:"靴売り場は どちらですか。",romaji:"Kutsu uriba wa dochira desu ka.",bengali:"জুতার counter কোন দিকে?"},
};

const unit4KanjiExamples: Record<string, KanjiSentenceExample> = {
  起:{japanese:"毎朝 6時に 起きます。",romaji:"Maiasa roku-ji ni okimasu.",bengali:"প্রতিদিন সকাল ৬টায় উঠি।"},寝:{japanese:"毎晩 11時に 寝ます。",romaji:"Maiban juuichi-ji ni nemasu.",bengali:"প্রতি রাত ১১টায় ঘুমাই।"},働:{japanese:"9時から 5時まで 働きます。",romaji:"Ku-ji kara go-ji made hatarakimasu.",bengali:"৯টা থেকে ৫টা পর্যন্ত কাজ করি।"},休:{japanese:"日曜日に 休みます。",romaji:"Nichiyoubi ni yasumimasu.",bengali:"রবিবার বিশ্রাম নিই।"},
  勉:{japanese:"毎日 日本語を 勉強します。",romaji:"Mainichi Nihongo o benkyou shimasu.",bengali:"প্রতিদিন জাপানি পড়ি।"},強:{japanese:"毎晩 2時間 勉強します。",romaji:"Maiban ni-jikan benkyou shimasu.",bengali:"প্রতি রাতে দুই ঘণ্টা পড়াশোনা করি।"},終:{japanese:"仕事は 5時に 終わります。",romaji:"Shigoto wa go-ji ni owarimasu.",bengali:"কাজ ৫টায় শেষ হয়।"},銀:{japanese:"銀行は 9時からです。",romaji:"Ginkou wa ku-ji kara desu.",bengali:"ব্যাংক ৯টা থেকে খোলে।"},行:{japanese:"銀行は 3時に 終わります。",romaji:"Ginkou wa san-ji ni owarimasu.",bengali:"ব্যাংক ৩টায় বন্ধ হয়।"},
  郵:{japanese:"郵便局は どこですか。",romaji:"Yuubinkyoku wa doko desu ka.",bengali:"ডাকঘর কোথায়?"},便:{japanese:"郵便局は 9時から 5時までです。",romaji:"Yuubinkyoku wa ku-ji kara go-ji made desu.",bengali:"ডাকঘর ৯টা থেকে ৫টা পর্যন্ত।"},局:{japanese:"郵便局は 土曜日に 休みます。",romaji:"Yuubinkyoku wa doyoubi ni yasumimasu.",bengali:"ডাকঘর শনিবার বন্ধ থাকে।"},図:{japanese:"図書館で 勉強します。",romaji:"Toshokan de benkyou shimasu.",bengali:"লাইব্রেরিতে পড়াশোনা করি।"},書:{japanese:"図書館は 月曜日に 休みます。",romaji:"Toshokan wa getsuyoubi ni yasumimasu.",bengali:"লাইব্রেরি সোমবার বন্ধ থাকে।"},館:{japanese:"美術館は 5時までです。",romaji:"Bijutsukan wa go-ji made desu.",bengali:"শিল্প জাদুঘর ৫টা পর্যন্ত।"},
  美:{japanese:"日曜日に 美術館へ 行きます。",romaji:"Nichiyoubi ni bijutsukan e ikimasu.",bengali:"রবিবার শিল্প জাদুঘরে যাই।"},術:{japanese:"美術館は 9時からです。",romaji:"Bijutsukan wa ku-ji kara desu.",bengali:"শিল্প জাদুঘর ৯টা থেকে খোলে।"},今:{japanese:"今 何時ですか。",romaji:"Ima nan-ji desu ka.",bengali:"এখন কয়টা?"},時:{japanese:"今 7時です。",romaji:"Ima shichi-ji desu.",bengali:"এখন ৭টা।"},分:{japanese:"7時10分です。",romaji:"Shichi-ji juppun desu.",bengali:"এখন ৭টা ১০ মিনিট।"},半:{japanese:"6時半に 起きます。",romaji:"Roku-ji han ni okimasu.",bengali:"সাড়ে ৬টায় উঠি।"},何:{japanese:"会議は 何時ですか。",romaji:"Kaigi wa nan-ji desu ka.",bengali:"মিটিং কয়টায়?"},
  午:{japanese:"会議は 午後 2時です。",romaji:"Kaigi wa gogo ni-ji desu.",bengali:"মিটিং দুপুর ২টায়।"},前:{japanese:"午前 8時から 働きます。",romaji:"Gozen hachi-ji kara hatarakimasu.",bengali:"সকাল ৮টা থেকে কাজ করি।"},後:{japanese:"午後 5時に 終わります。",romaji:"Gogo go-ji ni owarimasu.",bengali:"বিকেল ৫টায় শেষ হয়।"},朝:{japanese:"毎朝 6時半に 起きます。",romaji:"Maiasa roku-ji han ni okimasu.",bengali:"প্রতি সকাল সাড়ে ৬টায় উঠি।"},昼:{japanese:"昼休みは 12時からです。",romaji:"Hiruyasumi wa juu-ni-ji kara desu.",bengali:"দুপুরের বিরতি ১২টা থেকে।"},晩:{japanese:"今晩 日本語を 勉強します。",romaji:"Konban Nihongo o benkyou shimasu.",bengali:"আজ রাতে জাপানি পড়ব।"},夜:{japanese:"夜 11時に 寝ます。",romaji:"Yoru juuichi-ji ni nemasu.",bengali:"রাত ১১টায় ঘুমাই।"},
  昨:{japanese:"昨日 勉強しました。",romaji:"Kinou benkyou shimashita.",bengali:"গতকাল পড়াশোনা করেছি।"},日:{japanese:"日曜日は 休みです。",romaji:"Nichiyoubi wa yasumi desu.",bengali:"রবিবার ছুটি।"},明:{japanese:"明日 休みます。",romaji:"Ashita yasumimasu.",bengali:"আগামীকাল বিশ্রাম নেব।"},試:{japanese:"試験は 金曜日です。",romaji:"Shiken wa kinyoubi desu.",bengali:"পরীক্ষা শুক্রবার।"},験:{japanese:"あさって 試験が あります。",romaji:"Asatte shiken ga arimasu.",bengali:"আগামী পরশু পরীক্ষা আছে।"},会:{japanese:"会議は 午後 3時です。",romaji:"Kaigi wa gogo san-ji desu.",bengali:"মিটিং দুপুর ৩টায়।"},議:{japanese:"火曜日に 会議が あります。",romaji:"Kayoubi ni kaigi ga arimasu.",bengali:"মঙ্গলবার মিটিং আছে।"},映:{japanese:"映画は 7時からです。",romaji:"Eiga wa shichi-ji kara desu.",bengali:"সিনেমা ৭টা থেকে।"},画:{japanese:"土曜日に 映画を 見ます。",romaji:"Doyoubi ni eiga o mimasu.",bengali:"শনিবার সিনেমা দেখি।"},毎:{japanese:"毎日 日本語を 勉強します。",romaji:"Mainichi Nihongo o benkyou shimasu.",bengali:"প্রতিদিন জাপানি পড়ি।"},
  月:{japanese:"月曜日に 働きます。",romaji:"Getsuyoubi ni hatarakimasu.",bengali:"সোমবার কাজ করি।"},曜:{japanese:"休みは 何曜日ですか。",romaji:"Yasumi wa nan-youbi desu ka.",bengali:"ছুটি কী বার?"},火:{japanese:"火曜日に 会議が あります。",romaji:"Kayoubi ni kaigi ga arimasu.",bengali:"মঙ্গলবার মিটিং আছে।"},水:{japanese:"水曜日は 休みです。",romaji:"Suiyoubi wa yasumi desu.",bengali:"বুধবার ছুটি।"},木:{japanese:"木曜日に 勉強します。",romaji:"Mokuyoubi ni benkyou shimasu.",bengali:"বৃহস্পতিবার পড়াশোনা করি।"},金:{japanese:"金曜日に 試験が あります。",romaji:"Kinyoubi ni shiken ga arimasu.",bengali:"শুক্রবার পরীক্ষা আছে।"},土:{japanese:"土曜日に 映画を 見ます。",romaji:"Doyoubi ni eiga o mimasu.",bengali:"শনিবার সিনেমা দেখি।"},
  大:{japanese:"毎日 10時まで 働きます。大変ですね。",romaji:"Mainichi juu-ji made hatarakimasu. Taihen desu ne.",bengali:"প্রতিদিন ১০টা পর্যন্ত কাজ করেন—কষ্টকর, তাই না!"},変:{japanese:"毎日 勉強します。大変ですね。",romaji:"Mainichi benkyou shimasu. Taihen desu ne.",bengali:"প্রতিদিন পড়েন—কষ্টকর, তাই না!"},番:{japanese:"会社は 何番ですか。",romaji:"Kaisha wa nan-ban desu ka.",bengali:"কোম্পানির নম্বর কত?"},号:{japanese:"電話番号は 03-1234-5678です。",romaji:"Denwa bangou wa zero-san no ichi-ni-san-yon no go-roku-nana-hachi desu.",bengali:"ফোন নম্বর 03-1234-5678।"},北:{japanese:"北京は 今 午後 3時です。",romaji:"Pekin wa ima gogo san-ji desu.",bengali:"বেইজিংয়ে এখন দুপুর ৩টা।"},京:{japanese:"北京は 何時ですか。",romaji:"Pekin wa nan-ji desu ka.",bengali:"বেইজিংয়ে কয়টা?"},
};

const unit6KanjiExamples: Record<string, KanjiSentenceExample> = {
  食:{japanese:"毎朝 ごはんを 食べます。",romaji:"Maiasa gohan o tabemasu.",bengali:"প্রতি সকালে খাবার খাই।"},
  飲:{japanese:"水を 飲みます。",romaji:"Mizu o nomimasu.",bengali:"পানি পান করি।"},
  吸:{japanese:"たばこを 吸いません。",romaji:"Tabako o suimasen.",bengali:"ধূমপান করি না।"},
  見:{japanese:"うちで テレビを 見ます。",romaji:"Uchi de terebi o mimasu.",bengali:"বাড়িতে টেলিভিশন দেখি।"},
  聞:{japanese:"音楽を 聞きます。",romaji:"Ongaku o kikimasu.",bengali:"গান শুনি।"},
  読:{japanese:"図書館で 本を 読みます。",romaji:"Toshokan de hon o yomimasu.",bengali:"লাইব্রেরিতে বই পড়ি।"},
  書:{japanese:"友達に 手紙を 書きます。",romaji:"Tomodachi ni tegami o kakimasu.",bengali:"বন্ধুকে চিঠি লিখি।"},
  買:{japanese:"市場で 野菜を 買います。",romaji:"Ichiba de yasai o kaimasu.",bengali:"বাজারে শাকসবজি কিনি।"},
  撮:{japanese:"大阪城で 写真を 撮ります。",romaji:"Oosakajou de shashin o torimasu.",bengali:"ওসাকা দুর্গে ছবি তুলি।"},
  会:{japanese:"10時に 大阪駅で 会いましょう。",romaji:"Juu-ji ni Oosaka-eki de aimashou.",bengali:"১০টায় ওসাকা স্টেশনে দেখা করি চলুন।"},
  御:{japanese:"朝御飯を 食べました。",romaji:"Asagohan o tabemashita.",bengali:"সকালের খাবার খেয়েছি।"},
  飯:{japanese:"晩御飯は 7時です。",romaji:"Bangohan wa shichi-ji desu.",bengali:"রাতের খাবার ৭টায়।"},
  朝:{japanese:"毎朝 パンを 食べます。",romaji:"Maiasa pan o tabemasu.",bengali:"প্রতি সকালে রুটি খাই।"},
  昼:{japanese:"食堂で 昼御飯を 食べます。",romaji:"Shokudou de hirugohan o tabemasu.",bengali:"ক্যান্টিনে দুপুরের খাবার খাই।"},
  晩:{japanese:"家族と 晩御飯を 食べます。",romaji:"Kazoku to bangohan o tabemasu.",bengali:"পরিবারের সঙ্গে রাতের খাবার খাই।"},
  卵:{japanese:"卵を 二つ 買います。",romaji:"Tamago o futatsu kaimasu.",bengali:"দুটি ডিম কিনি।"},
  肉:{japanese:"肉を 食べません。",romaji:"Niku o tabemasen.",bengali:"মাংস খাই না।"},
  魚:{japanese:"魚を 食べます。",romaji:"Sakana o tabemasu.",bengali:"মাছ খাই।"},
  野:{japanese:"市場で 野菜を 買います。",romaji:"Ichiba de yasai o kaimasu.",bengali:"বাজারে শাকসবজি কিনি।"},
  菜:{japanese:"毎日 野菜を 食べます。",romaji:"Mainichi yasai o tabemasu.",bengali:"প্রতিদিন শাকসবজি খাই।"},
  果:{japanese:"朝 果物を 食べます。",romaji:"Asa kudamono o tabemasu.",bengali:"সকালে ফল খাই।"},
  物:{japanese:"冷たい 飲み物を 買います。",romaji:"Tsumetai nomimono o kaimasu.",bengali:"ঠান্ডা পানীয় কিনি।"},
  水:{japanese:"冷たい 水を 飲みます。",romaji:"Tsumetai mizu o nomimasu.",bengali:"ঠান্ডা পানি পান করি।"},
  茶:{japanese:"いっしょに お茶を 飲みませんか。",romaji:"Issho ni ocha o nomimasen ka.",bengali:"একসঙ্গে চা খাবেন?"},
  紅:{japanese:"喫茶店で 紅茶を 飲みます。",romaji:"Kissaten de koucha o nomimasu.",bengali:"কফিশপে ব্ল্যাক টি পান করি।"},
  牛:{japanese:"毎朝 牛乳を 飲みます。",romaji:"Maiasa gyuunyuu o nomimasu.",bengali:"প্রতি সকালে দুধ পান করি।"},
  乳:{japanese:"牛乳を 一つ 買います。",romaji:"Gyuunyuu o hitotsu kaimasu.",bengali:"একটি দুধ কিনি।"},
  酒:{japanese:"父は お酒を 飲みます。",romaji:"Chichi wa osake o nomimasu.",bengali:"বাবা সাকে পান করেন।"},
  手:{japanese:"友達に 手紙を 書きます。",romaji:"Tomodachi ni tegami o kakimasu.",bengali:"বন্ধুকে চিঠি লিখি।"},
  紙:{japanese:"この 手紙を 読みます。",romaji:"Kono tegami o yomimasu.",bengali:"এই চিঠিটি পড়ি।"},
  写:{japanese:"庭で 写真を 撮ります。",romaji:"Niwa de shashin o torimasu.",bengali:"বাগানে ছবি তুলি।"},
  真:{japanese:"この 写真を 見てください。",romaji:"Kono shashin o mite kudasai.",bengali:"এই ছবিটি দেখুন।"},
  店:{japanese:"あの 店で パンを 買います。",romaji:"Ano mise de pan o kaimasu.",bengali:"ওই দোকানে রুটি কিনি।"},
  庭:{japanese:"庭で テニスを します。",romaji:"Niwa de tenisu o shimasu.",bengali:"বাগানে টেনিস খেলি।"},
  宿:{japanese:"図書館で 宿題を します。",romaji:"Toshokan de shukudai o shimasu.",bengali:"লাইব্রেরিতে বাড়ির কাজ করি।"},
  題:{japanese:"毎晩 宿題を します。",romaji:"Maiban shukudai o shimasu.",bengali:"প্রতি রাতে বাড়ির কাজ করি।"},
  花:{japanese:"あした お花見を します。",romaji:"Ashita ohanami o shimasu.",bengali:"আগামীকাল চেরি ফুল দেখব।"},
  何:{japanese:"きのう 何を しましたか。",romaji:"Kinou nani o shimashita ka.",bengali:"গতকাল কী করেছিলেন?"},
  一:{japanese:"いっしょに 映画を 見ませんか。",romaji:"Issho ni eiga o mimasen ka.",bengali:"একসঙ্গে সিনেমা দেখবেন?"},
  緒:{japanese:"佐藤さんも 一緒に 行きませんか。",romaji:"Satou-san mo issho ni ikimasen ka.",bengali:"সাতো-সানও একসঙ্গে যাবেন?"},
  時:{japanese:"時々 友達と テニスを します。",romaji:"Tokidoki tomodachi to tenisu o shimasu.",bengali:"মাঝে মাঝে বন্ধুর সঙ্গে টেনিস খেলি।"},
  分:{japanese:"はい、分かりました。",romaji:"Hai, wakarimashita.",bengali:"হ্যাঁ, বুঝেছি।"},
  明:{japanese:"じゃ、また 明日。",romaji:"Ja, mata ashita.",bengali:"তাহলে, কাল আবার দেখা হবে।"},
  日:{japanese:"日曜日に お花見を します。",romaji:"Nichiyoubi ni ohanami o shimasu.",bengali:"রবিবার চেরি ফুল দেখি।"},
  駅:{japanese:"大阪駅で 会いましょう。",romaji:"Oosaka-eki de aimashou.",bengali:"ওসাকা স্টেশনে দেখা করি চলুন।"},
  学:{japanese:"学校で 日本語を 勉強します。",romaji:"Gakkou de Nihongo o benkyou shimasu.",bengali:"স্কুলে জাপানি পড়ি।"},
  校:{japanese:"毎朝 学校へ 行きます。",romaji:"Maiasa gakkou e ikimasu.",bengali:"প্রতি সকালে স্কুলে যাই।"},
  市:{japanese:"市場で 魚を 買います。",romaji:"Ichiba de sakana o kaimasu.",bengali:"বাজারে মাছ কিনি।"},
  場:{japanese:"市場は 駅の 近くです。",romaji:"Ichiba wa eki no chikaku desu.",bengali:"বাজার স্টেশনের কাছে।"},
  関:{japanese:"関西で 写真を 撮りました。",romaji:"Kansai de shashin o torimashita.",bengali:"কানসাইয়ে ছবি তুলেছিলাম।"},
  西:{japanese:"大阪は 関西に あります。",romaji:"Oosaka wa Kansai ni arimasu.",bengali:"ওসাকা কানসাই অঞ্চলে অবস্থিত।"},
  土:{japanese:"京都で お土産を 買います。",romaji:"Kyouto de omiyage o kaimasu.",bengali:"কিয়োটোতে স্মারক কিনি।"},
  産:{japanese:"この お土産は 京都のです。",romaji:"Kono omiyage wa Kyouto no desu.",bengali:"এই স্মারকটি কিয়োটোর।"},
  夜:{japanese:"夜中に 水を 飲みました。",romaji:"Yonaka ni mizu o nomimashita.",bengali:"মধ্যরাতে পানি পান করেছিলাম।"},
  中:{japanese:"夜中に 本を 読みません。",romaji:"Yonaka ni hon o yomimasen.",bengali:"মধ্যরাতে বই পড়ি না।"},
};

const unit7KanjiExamples: Record<string, KanjiSentenceExample> = {
  切:{japanese:"はさみで 紙を 切ります。",romaji:"Hasami de kami o kirimasu.",bengali:"কাঁচি দিয়ে কাগজ কাটি।"},
  送:{japanese:"友達に メールを 送ります。",romaji:"Tomodachi ni meeru o okurimasu.",bengali:"বন্ধুকে ই-মেইল পাঠাই।"},
  貸:{japanese:"太郎ちゃんに 本を 貸しました。",romaji:"Tarou-chan ni hon o kashimashita.",bengali:"তারোকে বই ধার দিয়েছি।"},
  借:{japanese:"友達に CDを 借りました。",romaji:"Tomodachi ni shiidii o karimashita.",bengali:"বন্ধুর কাছ থেকে CD ধার নিয়েছি।"},
  教:{japanese:"山田さんに 英語を 教えます。",romaji:"Yamada-san ni eigo o oshiemasu.",bengali:"ইয়ামাদা-সানকে ইংরেজি শেখাই।"},
  習:{japanese:"先生に 日本語を 習います。",romaji:"Sensei ni nihongo o naraimasu.",bengali:"শিক্ষকের কাছে জাপানি শিখি।"},
  電:{japanese:"母に 電話を かけます。",romaji:"Haha ni denwa o kakemasu.",bengali:"মাকে ফোন করি।"},
  話:{japanese:"電話で 父と 話します。",romaji:"Denwa de chichi to hanashimasu.",bengali:"ফোনে বাবার সঙ্গে কথা বলি।"},
  手:{japanese:"右手で 箸を 持ちます。",romaji:"Migite de hashi o mochimasu.",bengali:"ডান হাতে চপস্টিক ধরি।"},
  箸:{japanese:"箸で ごはんを 食べます。",romaji:"Hashi de gohan o tabemasu.",bengali:"চপস্টিক দিয়ে ভাত খাই।"},
  持:{japanese:"右手で 箸を 持ちます。",romaji:"Migite de hashi o mochimasu.",bengali:"ডান হাতে চপস্টিক ধরি।"},
  年:{japanese:"友達に 年賀状を 送ります。",romaji:"Tomodachi ni nengajou o okurimasu.",bengali:"বন্ধুকে নববর্ষের কার্ড পাঠাই।"},
  賀:{japanese:"もう 年賀状を 書きました。",romaji:"Mou nengajou o kakimashita.",bengali:"নববর্ষের কার্ড ইতোমধ্যে লিখেছি।"},
  状:{japanese:"これは 日本の 年賀状です。",romaji:"Kore wa Nihon no nengajou desu.",bengali:"এটি জাপানের নববর্ষের শুভেচ্ছা কার্ড।"},
  消:{japanese:"消しゴムで 字を 消します。",romaji:"Keshigomu de ji o keshimasu.",bengali:"রাবার দিয়ে লেখা মুছি।"},
  紙:{japanese:"紙に 名前を 書きます。",romaji:"Kami ni namae o kakimasu.",bengali:"কাগজে নাম লিখি।"},
  花:{japanese:"母に 花を あげました。",romaji:"Haha ni hana o agemashita.",bengali:"মাকে ফুল দিয়েছি।"},
  荷:{japanese:"家族に 荷物を 送ります。",romaji:"Kazoku ni nimotsu o okurimasu.",bengali:"পরিবারকে পার্সেল পাঠাই।"},
  物:{japanese:"もう 荷物を 送りましたか。",romaji:"Mou nimotsu o okurimashita ka.",bengali:"পার্সেল কি ইতোমধ্যে পাঠিয়েছেন?"},
  金:{japanese:"銀行から お金を 借りました。",romaji:"Ginkou kara okane o karimashita.",bengali:"ব্যাংক থেকে টাকা ধার নিয়েছি।"},
  符:{japanese:"駅で 切符を 買います。",romaji:"Eki de kippu o kaimasu.",bengali:"স্টেশনে টিকিট কিনি।"},
  父:{japanese:"父に シャツを あげました。",romaji:"Chichi ni shatsu o agemashita.",bengali:"বাবাকে শার্ট দিয়েছি।"},
  母:{japanese:"母に 花を あげます。",romaji:"Haha ni hana o agemasu.",bengali:"মাকে ফুল দিই।"},
  上:{japanese:"どうぞ お上がりください。",romaji:"Douzo oagari kudasai.",bengali:"অনুগ্রহ করে ভেতরে আসুন।"},
  失:{japanese:"おじゃまします。失礼します。",romaji:"Ojama shimasu. Shitsurei shimasu.",bengali:"বিরক্ত করছি; অনুমতি নিচ্ছি।"},
  礼:{japanese:"先生に お礼の メールを 送りました。",romaji:"Sensei ni orei no meeru o okurimashita.",bengali:"শিক্ষককে ধন্যবাদ জানিয়ে ই-মেইল পাঠিয়েছি।"},
  家:{japanese:"わたしの 家族は 5人です。",romaji:"Watashi no kazoku wa go-nin desu.",bengali:"আমার পরিবারে পাঁচজন।"},
  族:{japanese:"家族に お土産を あげました。",romaji:"Kazoku ni omiyage o agemashita.",bengali:"পরিবারকে স্মারক উপহার দিয়েছি।"},
  祖:{japanese:"祖父から 時計を もらいました。",romaji:"Sofu kara tokei o moraimashita.",bengali:"দাদা/নানার কাছ থেকে ঘড়ি পেয়েছি।"},
  両:{japanese:"両親は バングラデシュに います。",romaji:"Ryoushin wa Banguradeshu ni imasu.",bengali:"আমার বাবা-মা বাংলাদেশে আছেন।"},
  親:{japanese:"ご両親は お元気ですか。",romaji:"Goryoushin wa ogenki desu ka.",bengali:"আপনার বাবা-মা ভালো আছেন?"},
  妹:{japanese:"妹に チョコレートを あげます。",romaji:"Imouto ni chokoreeto o agemasu.",bengali:"ছোট বোনকে chocolate দিই।"},
  弟:{japanese:"弟に 本を 貸します。",romaji:"Otouto ni hon o kashimasu.",bengali:"ছোট ভাইকে বই ধার দিই।"},
  姉:{japanese:"姉は 英語の 先生です。",romaji:"Ane wa eigo no sensei desu.",bengali:"আমার বড় বোন ইংরেজির শিক্ষক।"},
  兄:{japanese:"兄に パソコンを 借りました。",romaji:"Ani ni pasokon o karimashita.",bengali:"বড় ভাইয়ের কাছ থেকে কম্পিউটার ধার নিয়েছি।"},
  妻:{japanese:"妻に プレゼントを あげます。",romaji:"Tsuma ni purezento o agemasu.",bengali:"স্ত্রীকে উপহার দিই।"},
  夫:{japanese:"夫から 花を もらいました。",romaji:"Otto kara hana o moraimashita.",bengali:"স্বামীর কাছ থেকে ফুল পেয়েছি।"},
  娘:{japanese:"娘に 日本語を 教えます。",romaji:"Musume ni nihongo o oshiemasu.",bengali:"মেয়েকে জাপানি শেখাই।"},
  息:{japanese:"息子に 本を あげました。",romaji:"Musuko ni hon o agemashita.",bengali:"ছেলেকে বই দিয়েছি।"},
  子:{japanese:"子どもに お菓子を あげます。",romaji:"Kodomo ni okashi o agemasu.",bengali:"শিশুকে মিষ্টি দিই।"},
  奥:{japanese:"奥さんに 花を あげました。",romaji:"Okusan ni hana o agemashita.",bengali:"তার স্ত্রীকে ফুল দিয়েছি।"},
  主:{japanese:"ご主人は 会社員です。",romaji:"Goshujin wa kaishain desu.",bengali:"আপনার স্বামী কোম্পানির কর্মী।"},
  英:{japanese:"英語で レポートを 書きます。",romaji:"Eigo de repooto o kakimasu.",bengali:"ইংরেজিতে রিপোর্ট লিখি।"},
  語:{japanese:"先生に 日本語を 習います。",romaji:"Sensei ni nihongo o naraimasu.",bengali:"শিক্ষকের কাছে জাপানি শিখি।"},
  日:{japanese:"日本語で 何ですか。",romaji:"Nihongo de nan desu ka.",bengali:"জাপানি ভাষায় কী?"},
  本:{japanese:"友達に 本を 貸しました。",romaji:"Tomodachi ni hon o kashimashita.",bengali:"বন্ধুকে বই ধার দিয়েছি।"},
  中:{japanese:"中国語を 習います。",romaji:"Chuugokugo o naraimasu.",bengali:"চীনা ভাষা শিখি।"},
  国:{japanese:"『ありがとう』は 中国語で 何ですか。",romaji:"Arigatou wa chuugokugo de nan desu ka.",bengali:"‘ধন্যবাদ’ চীনা ভাষায় কী?"},
  土:{japanese:"京都の お土産を もらいました。",romaji:"Kyouto no omiyage o moraimashita.",bengali:"কিয়োটোর স্মারক উপহার পেয়েছি।"},
  産:{japanese:"これは メキシコの お土産です。",romaji:"Kore wa Mekishiko no omiyage desu.",bengali:"এটি মেক্সিকোর স্মারক উপহার।"},
  書:{japanese:"日本語で レポートを 書きます。",romaji:"Nihongo de repooto o kakimasu.",bengali:"জাপানিতে রিপোর্ট লিখি।"},
  読:{japanese:"図書館で 本を 読みました。",romaji:"Toshokan de hon o yomimashita.",bengali:"লাইব্রেরিতে বই পড়েছি।"},
  食:{japanese:"箸で ごはんを 食べます。",romaji:"Hashi de gohan o tabemasu.",bengali:"চপস্টিক দিয়ে ভাত খাই।"},
  写:{japanese:"ケータイで 写真を 撮ります。",romaji:"Keetai de shashin o torimasu.",bengali:"মোবাইল দিয়ে ছবি তুলি।"},
  真:{japanese:"この 写真を 母に あげます。",romaji:"Kono shashin o haha ni agemasu.",bengali:"এই ছবিটি মাকে দিই।"},
  会:{japanese:"会社の 人に スプーンを もらいました。",romaji:"Kaisha no hito ni supuun o moraimashita.",bengali:"কোম্পানির একজনের কাছ থেকে চামচ পেয়েছি।"},
  社:{japanese:"会社から プレゼントを もらいました。",romaji:"Kaisha kara purezento o moraimashita.",bengali:"কোম্পানি থেকে উপহার পেয়েছি।"},
  銀:{japanese:"銀行から お金を 借りました。",romaji:"Ginkou kara okane o karimashita.",bengali:"ব্যাংক থেকে টাকা ধার নিয়েছি।"},
  行:{japanese:"きのう 図書館へ 行きました。",romaji:"Kinou toshokan e ikimashita.",bengali:"গতকাল লাইব্রেরিতে গিয়েছি।"},
  図:{japanese:"図書館で 本を 読みます。",romaji:"Toshokan de hon o yomimasu.",bengali:"লাইব্রেরিতে বই পড়ি।"},
  館:{japanese:"きのう 図書館へ 行きました。",romaji:"Kinou toshokan e ikimashita.",bengali:"গতকাল লাইব্রেরিতে গিয়েছি।"},
  宿:{japanese:"もう 宿題を しましたか。",romaji:"Mou shukudai o shimashita ka.",bengali:"বাড়ির কাজ কি ইতোমধ্যে করেছেন?"},
  題:{japanese:"いいえ、宿題は まだです。",romaji:"Iie, shukudai wa mada desu.",bengali:"না, বাড়ির কাজ এখনো হয়নি।"},
  何:{japanese:"『ありがとう』は 英語で 何ですか。",romaji:"Arigatou wa eigo de nan desu ka.",bengali:"‘আরিগাতো’ ইংরেজিতে কী?"},
};

const unit8KanjiExamples: Record<string, KanjiSentenceExample> = {
  静:{japanese:"この 寮は 静かです。",romaji:"Kono ryou wa shizuka desu.",bengali:"এই ছাত্রাবাসটি শান্ত।"},有:{japanese:"富士山は 有名です。",romaji:"Fujisan wa yuumei desu.",bengali:"ফুজি পর্বত বিখ্যাত।"},名:{japanese:"奈良は 有名な 町です。",romaji:"Nara wa yuumei na machi desu.",bengali:"নারা একটি বিখ্যাত শহর।"},親:{japanese:"ワット先生は 親切です。",romaji:"Watto-sensei wa shinsetsu desu.",bengali:"ওয়াত্তো-সেনসেই সদয়।"},切:{japanese:"親切な 人です。",romaji:"Shinsetsu na hito desu.",bengali:"তিনি সদয় মানুষ।"},元:{japanese:"お元気ですか。",romaji:"Ogenki desu ka.",bengali:"কেমন আছেন?"},気:{japanese:"母は 元気です。",romaji:"Haha wa genki desu.",bengali:"মা সুস্থ আছেন।"},暇:{japanese:"日曜日は 暇です。",romaji:"Nichiyoubi wa hima desu.",bengali:"রবিবার অবসর আছে।"},
  便:{japanese:"この アプリは 便利です。",romaji:"Kono apuri wa benri desu.",bengali:"এই app-টি সুবিধাজনক।"},利:{japanese:"電車は 便利です。",romaji:"Densha wa benri desu.",bengali:"ট্রেন সুবিধাজনক।"},大:{japanese:"富士山は 大きいです。",romaji:"Fujisan wa ookii desu.",bengali:"ফুজি পর্বত বড়।"},小:{japanese:"小さい カメラです。",romaji:"Chiisai kamera desu.",bengali:"এটি ছোট ক্যামেরা।"},新:{japanese:"新しい 本を 買いました。",romaji:"Atarashii hon o kaimashita.",bengali:"নতুন বই কিনেছি।"},古:{japanese:"奈良は 古い 町です。",romaji:"Nara wa furui machi desu.",bengali:"নারা পুরোনো শহর।"},悪:{japanese:"きょうの 天気は 悪いです。",romaji:"Kyou no tenki wa warui desu.",bengali:"আজকের আবহাওয়া খারাপ।"},暑:{japanese:"東京は 暑いです。",romaji:"Toukyou wa atsui desu.",bengali:"টোকিও গরম।"},
  寒:{japanese:"北京は 寒いです。",romaji:"Pekin wa samui desu.",bengali:"বেইজিং ঠান্ডা।"},冷:{japanese:"冷たい 水を 飲みます。",romaji:"Tsumetai mizu o nomimasu.",bengali:"ঠান্ডা পানি পান করি।"},難:{japanese:"日本語は 難しいです。",romaji:"Nihongo wa muzukashii desu.",bengali:"জাপানি ভাষা কঠিন।"},易:{japanese:"この 問題は 易しいです。",romaji:"Kono mondai wa yasashii desu.",bengali:"এই প্রশ্নটি সহজ।"},高:{japanese:"富士山は とても 高いです。",romaji:"Fujisan wa totemo takai desu.",bengali:"ফুজি পর্বত খুব উঁচু।"},安:{japanese:"この シャツは 安いです。",romaji:"Kono shatsu wa yasui desu.",bengali:"এই শার্টটি সস্তা।"},低:{japanese:"この いすは 低いです。",romaji:"Kono isu wa hikui desu.",bengali:"এই চেয়ারটি নিচু।"},忙:{japanese:"毎日 忙しいです。",romaji:"Mainichi isogashii desu.",bengali:"প্রতিদিন ব্যস্ত থাকি।"},
  楽:{japanese:"日本の 生活は 楽しいです。",romaji:"Nihon no seikatsu wa tanoshii desu.",bengali:"জাপানের জীবন আনন্দদায়ক।"},白:{japanese:"白い シャツを 買います。",romaji:"Shiroi shatsu o kaimasu.",bengali:"সাদা শার্ট কিনি।"},黒:{japanese:"黒い かばんです。",romaji:"Kuroi kaban desu.",bengali:"এটি কালো ব্যাগ।"},赤:{japanese:"赤い りんごを 食べます。",romaji:"Akai ringo o tabemasu.",bengali:"লাল আপেল খাই।"},青:{japanese:"空は 青いです。",romaji:"Sora wa aoi desu.",bengali:"আকাশ নীল।"},桜:{japanese:"桜は きれいです。",romaji:"Sakura wa kirei desu.",bengali:"চেরি ফুল সুন্দর।"},山:{japanese:"あの 山は 高いです。",romaji:"Ano yama wa takai desu.",bengali:"ওই পাহাড়টি উঁচু।"},町:{japanese:"東京は にぎやかな 町です。",romaji:"Toukyou wa nigiyaka na machi desu.",bengali:"টোকিও প্রাণবন্ত শহর।"},
  食:{japanese:"日本の 食べ物は おいしいです。",romaji:"Nihon no tabemono wa oishii desu.",bengali:"জাপানি খাবার সুস্বাদু।"},物:{japanese:"これは 日本の 食べ物です。",romaji:"Kore wa Nihon no tabemono desu.",bengali:"এটি জাপানি খাবার।"},所:{japanese:"奈良は どんな 所ですか。",romaji:"Nara wa donna tokoro desu ka.",bengali:"নারা কেমন জায়গা?"},寮:{japanese:"寮は あまり 静かじゃありません。",romaji:"Ryou wa amari shizuka ja arimasen.",bengali:"ছাত্রাবাস খুব একটা শান্ত নয়।"},生:{japanese:"日本の 生活は どうですか。",romaji:"Nihon no seikatsu wa dou desu ka.",bengali:"জাপানের জীবন কেমন?"},活:{japanese:"日本の 生活は 楽しいです。",romaji:"Nihon no seikatsu wa tanoshii desu.",bengali:"জাপানের জীবন আনন্দদায়ক।"},仕:{japanese:"お仕事は どうですか。",romaji:"Oshigoto wa dou desu ka.",bengali:"কাজ কেমন?"},事:{japanese:"仕事は 忙しいです。",romaji:"Shigoto wa isogashii desu.",bengali:"কাজ ব্যস্ততাপূর্ণ।"},
  慣:{japanese:"日本の 生活に 慣れました。",romaji:"Nihon no seikatsu ni naremashita.",bengali:"জাপানের জীবনে অভ্যস্ত হয়েছি।"},一:{japanese:"もう 一杯 いかがですか。",romaji:"Mou ippai ikaga desu ka.",bengali:"আরেক কাপ নেবেন?"},杯:{japanese:"コーヒーを 一杯 飲みます。",romaji:"Koohii o ippai nomimasu.",bengali:"এক কাপ কফি পান করি।"},失:{japanese:"そろそろ 失礼します。",romaji:"Sorosoro shitsurei shimasu.",bengali:"এবার বিদায় নিই।"},礼:{japanese:"失礼します。",romaji:"Shitsurei shimasu.",bengali:"অনুমতি নিচ্ছি/বিদায় নিচ্ছি।"},緑:{japanese:"緑の かばんです。",romaji:"Midori no kaban desu.",bengali:"এটি সবুজ ব্যাগ।"},紫:{japanese:"紫の 花が あります。",romaji:"Murasaki no hana ga arimasu.",bengali:"বেগুনি ফুল আছে।"},黄:{japanese:"黄色い レモンです。",romaji:"Kiiroi remon desu.",bengali:"এটি হলুদ লেবু।"},
  色:{japanese:"何色が すきですか。",romaji:"Naniiro ga suki desu ka.",bengali:"কোন রং পছন্দ?"},茶:{japanese:"茶色の かばんです。",romaji:"Chairo no kaban desu.",bengali:"এটি বাদামি ব্যাগ।"},甘:{japanese:"この ケーキは 甘いです。",romaji:"Kono keeki wa amai desu.",bengali:"এই কেকটি মিষ্টি।"},辛:{japanese:"この カレーは 辛いです。",romaji:"Kono karee wa karai desu.",bengali:"এই curry ঝাল।"},苦:{japanese:"この 薬は 苦いです。",romaji:"Kono kusuri wa nigai desu.",bengali:"এই ওষুধটি তিতা।"},塩:{japanese:"この スープは 塩辛いです。",romaji:"Kono suupu wa shiokarai desu.",bengali:"এই soup-টি নোনতা।"},酸:{japanese:"レモンは 酸っぱいです。",romaji:"Remon wa suppai desu.",bengali:"লেবু টক।"},濃:{japanese:"この コーヒーは 濃いです。",romaji:"Kono koohii wa koi desu.",bengali:"এই কফি ঘন/strong।"},薄:{japanese:"この お茶は 薄いです。",romaji:"Kono ocha wa usui desu.",bengali:"এই চা হালকা।"},
  田:{japanese:"山田さんは 親切です。",romaji:"Yamada-san wa shinsetsu desu.",bengali:"ইয়ামাদা-সান সদয়।"},毎:{japanese:"毎日 とても 楽しいです。",romaji:"Mainichi totemo tanoshii desu.",bengali:"প্রতিদিন খুব আনন্দের।"},日:{japanese:"日曜日は 暇です。",romaji:"Nichiyoubi wa hima desu.",bengali:"রবিবার অবসর আছে।"},形:{japanese:"形容詞を 練習します。",romaji:"Keiyoushi o renshuu shimasu.",bengali:"Adjective অনুশীলন করি।"},容:{japanese:"これは 形容詞です。",romaji:"Kore wa keiyoushi desu.",bengali:"এটি adjective।"},詞:{japanese:"新しい 形容詞を 習います。",romaji:"Atarashii keiyoushi o naraimasu.",bengali:"নতুন adjective শিখি।"},会:{japanese:"会話を 練習します。",romaji:"Kaiwa o renshuu shimasu.",bengali:"কথোপকথন অনুশীলন করি।"},話:{japanese:"日本語で 会話します。",romaji:"Nihongo de kaiwa shimasu.",bengali:"জাপানিতে কথোপকথন করি।"},
  読:{japanese:"短い 文を 読みます。",romaji:"Mijikai bun o yomimasu.",bengali:"ছোট বাক্য পড়ি।"},解:{japanese:"読解の 問題は 易しいです。",romaji:"Dokkai no mondai wa yasashii desu.",bengali:"Reading comprehension-এর প্রশ্ন সহজ।"},寺:{japanese:"金閣寺は きれいです。",romaji:"Kinkakuji wa kirei desu.",bengali:"কিনকাকুজি সুন্দর।"},公:{japanese:"この 公園は 静かです。",romaji:"Kono kouen wa shizuka desu.",bengali:"এই পার্কটি শান্ত।"},園:{japanese:"有名な 公園です。",romaji:"Yuumei na kouen desu.",bengali:"এটি বিখ্যাত পার্ক।"},奈:{japanese:"奈良は 古い 町です。",romaji:"Nara wa furui machi desu.",bengali:"নারা পুরোনো শহর।"},良:{japanese:"奈良は きれいな 町です。",romaji:"Nara wa kirei na machi desu.",bengali:"নারা সুন্দর শহর।"},何:{japanese:"何を 見ましたか。",romaji:"Nani o mimashita ka.",bengali:"কী দেখেছেন?"},
  本:{japanese:"新しい 本を 読みます。",romaji:"Atarashii hon o yomimasu.",bengali:"নতুন বই পড়ি।"},友:{japanese:"友達は 元気です。",romaji:"Tomodachi wa genki desu.",bengali:"বন্ধু ভালো আছে।"},子:{japanese:"友子さんは 親切です。",romaji:"Tomoko-san wa shinsetsu desu.",bengali:"তোমোকো-সান সদয়।"},時:{japanese:"もう 6時です。",romaji:"Mou roku-ji desu.",bengali:"ইতোমধ্যে ৬টা।"},文:{japanese:"この 文型は 易しいです。",romaji:"Kono bunkei wa yasashii desu.",bengali:"এই sentence pattern সহজ।"},型:{japanese:"新しい 文型を 習います。",romaji:"Atarashii bunkei o naraimasu.",bengali:"নতুন sentence pattern শিখি।"},花:{japanese:"きれいな 花を 買いました。",romaji:"Kirei na hana o kaimashita.",bengali:"সুন্দর ফুল কিনেছি।"},練:{japanese:"毎日 練習します。",romaji:"Mainichi renshuu shimasu.",bengali:"প্রতিদিন অনুশীলন করি।"},
  習:{japanese:"形容詞を 練習します。",romaji:"Keiyoushi o renshuu shimasu.",bengali:"Adjective অনুশীলন করি।"},自:{japanese:"この 自転車は 新しいです。",romaji:"Kono jitensha wa atarashii desu.",bengali:"এই সাইকেলটি নতুন।"},転:{japanese:"新しい 自転車です。",romaji:"Atarashii jitensha desu.",bengali:"এটি নতুন সাইকেল।"},車:{japanese:"赤い 車は 高いです。",romaji:"Akai kuruma wa takai desu.",bengali:"লাল গাড়িটি দামি।"},北:{japanese:"北京は 今 寒いです。",romaji:"Pekin wa ima samui desu.",bengali:"বেইজিং এখন ঠান্ডা।"},京:{japanese:"東京は にぎやかです。",romaji:"Toukyou wa nigiyaka desu.",bengali:"টোকিও জমজমাট।"},今:{japanese:"今は とても 忙しいです。",romaji:"Ima wa totemo isogashii desu.",bengali:"এখন খুব ব্যস্ত।"},上:{japanese:"上海は あまり 寒くないです。",romaji:"Shanhai wa amari samuku nai desu.",bengali:"সাংহাই খুব একটা ঠান্ডা নয়।"},
  海:{japanese:"上海は 大きい 町です。",romaji:"Shanhai wa ookii machi desu.",bengali:"সাংহাই বড় শহর।"},学:{japanese:"さくら大学は 有名です。",romaji:"Sakura Daigaku wa yuumei desu.",bengali:"সাকুরা বিশ্ববিদ্যালয় বিখ্যাত।"},松:{japanese:"松本さんの うちは 大きいです。",romaji:"Matsumoto-san no uchi wa ookii desu.",bengali:"মাতসুমোতো-সানের বাড়ি বড়।"},見:{japanese:"おもしろい 映画を 見ました。",romaji:"Omoshiroi eiga o mimashita.",bengali:"মজার সিনেমা দেখেছি।"},金:{japanese:"金閣寺へ 行きました。",romaji:"Kinkakuji e ikimashita.",bengali:"কিনকাকুজিতে গিয়েছি।"},閣:{japanese:"金閣寺は 有名な 所です。",romaji:"Kinkakuji wa yuumei na tokoro desu.",bengali:"কিনকাকুজি বিখ্যাত জায়গা।"},写:{japanese:"写真を 見ますか。",romaji:"Shashin o mimasu ka.",bengali:"ছবি দেখবেন?"},真:{japanese:"きれいな 写真です。",romaji:"Kirei na shashin desu.",bengali:"এটি সুন্দর ছবি।"},
  問:{japanese:"問題は 難しくないです。",romaji:"Mondai wa muzukashiku nai desu.",bengali:"প্রশ্নটি কঠিন নয়।"},題:{japanese:"この 問題は 易しいです。",romaji:"Kono mondai wa yasashii desu.",bengali:"এই প্রশ্নটি সহজ।"},先:{japanese:"ワット先生は おもしろいです。",romaji:"Watto-sensei wa omoshiroi desu.",bengali:"ওয়াট-সেনসেই মজার মানুষ।"},英:{japanese:"ワット先生は 英語の 先生です。",romaji:"Watto-sensei wa eigo no sensei desu.",bengali:"ওয়াট-সেনসেই ইংরেজির শিক্ষক।"},語:{japanese:"英語は 難しくないです。",romaji:"Eigo wa muzukashiku nai desu.",bengali:"ইংরেজি কঠিন নয়।"},堂:{japanese:"大学の 食堂は にぎやかです。",romaji:"Daigaku no shokudou wa nigiyaka desu.",bengali:"বিশ্ববিদ্যালয়ের cafeteria জমজমাট।"},
};

export function getMinnaN5KanjiExample(unitNumber: number, kanji: string) {
  if (unitNumber === 1) return unit1KanjiExamples[kanji];
  if (unitNumber === 2) return unit2KanjiExamples[kanji];
  if (unitNumber === 3) return unit3KanjiExamples[kanji];
  if (unitNumber === 4) return unit4KanjiExamples[kanji];
  if (unitNumber === 6) return unit6KanjiExamples[kanji];
  if (unitNumber === 7) return unit7KanjiExamples[kanji];
  if (unitNumber === 8) return unit8KanjiExamples[kanji];
  return undefined;
}
