create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null,
  content text,
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.posts
  add column if not exists slug text,
  add column if not exists excerpt text,
  add column if not exists cover_image text,
  add column if not exists author_id uuid references public.profiles(id) on delete set null,
  add column if not exists published_at timestamptz;

update public.posts
set
  slug = coalesce(slug, 'post-' || id::text),
  excerpt = coalesce(excerpt, left(coalesce(content, ''), 180)),
  published_at = coalesce(published_at, created_at)
where slug is null
   or excerpt is null
   or published_at is null;

alter table public.posts
  alter column slug set not null,
  alter column excerpt set not null,
  alter column published_at set not null;

create unique index if not exists posts_slug_key on public.posts(slug);
create index if not exists posts_published_at_idx
  on public.posts(published_at desc)
  where published = true;

alter table public.posts enable row level security;

drop policy if exists "Published posts are publicly readable" on public.posts;
create policy "Published posts are publicly readable"
on public.posts
for select
to anon, authenticated
using (
  published = true
  or author_id = (select auth.uid())
  or (select public.is_admin())
);

drop policy if exists "Authenticated users can create posts" on public.posts;
create policy "Authenticated users can create posts"
on public.posts
for insert
to authenticated
with check (author_id = (select auth.uid()));

drop policy if exists "Authenticated users can update posts" on public.posts;
create policy "Authenticated users can update posts"
on public.posts
for update
to authenticated
using (
  author_id = (select auth.uid())
  or (select public.is_admin())
)
with check (
  author_id = (select auth.uid())
  or (select public.is_admin())
);

drop policy if exists "Authenticated users can delete posts" on public.posts;
create policy "Authenticated users can delete posts"
on public.posts
for delete
to authenticated
using (
  author_id = (select auth.uid())
  or (select public.is_admin())
);

grant select on table public.posts to anon, authenticated;
grant insert, update, delete on table public.posts to authenticated;
grant usage, select on sequence public.posts_id_seq to authenticated;

insert into public.posts (
  slug,
  title,
  excerpt,
  content,
  published,
  published_at
)
values (
  'japan-engineering-team-communication',
  'জাপানের Engineering Team-এ কাজ করে Communication নিয়ে যা শিখেছি',
  'Technical skill-এর পাশাপাশি documentation, context sharing এবং consistent update কেন গুরুত্বপূর্ণ।',
  'জাপানে engineering team-এ কাজ করার পর আমি একটি বিষয় খুব ভালোভাবে বুঝেছি—ভালো code একা একটি project সফল করতে পারে না।

Team-এর সবাই যেন একই context বুঝতে পারে, সেই দায়িত্বও একজন engineer-এর। Meeting-এর আগে প্রয়োজনীয় তথ্য লেখা, decision-এর কারণ document করা এবং progress নিয়মিত share করা trust তৈরি করে।

Language perfect না হলেও communication clear হতে পারে। ছোট sentence, visual example এবং written summary ব্যবহার করলে misunderstanding অনেক কমে যায়।

আমার সবচেয়ে বড় lesson হলো: communication কোনো soft extra নয়। এটি engineering delivery-এর একটি গুরুত্বপূর্ণ অংশ।',
  true,
  now()
)
on conflict (slug) do nothing;
