create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 200),
  content text,
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.posts enable row level security;

drop policy if exists "Published posts are publicly readable" on public.posts;
create policy "Published posts are publicly readable"
on public.posts
for select
to anon, authenticated
using (published = true);

drop policy if exists "Authenticated users can create posts" on public.posts;
create policy "Authenticated users can create posts"
on public.posts
for insert
to authenticated
with check (true);

drop policy if exists "Authenticated users can update posts" on public.posts;
create policy "Authenticated users can update posts"
on public.posts
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated users can delete posts" on public.posts;
create policy "Authenticated users can delete posts"
on public.posts
for delete
to authenticated
using (true);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists posts_set_updated_at on public.posts;
create trigger posts_set_updated_at
before update on public.posts
for each row
execute function public.set_updated_at();

insert into public.posts (title, content, published)
select
  'Supabase is connected',
  'This sample row confirms that the posts table was created successfully.',
  true
where not exists (
  select 1
  from public.posts
  where title = 'Supabase is connected'
);
