-- Lets an admin attach one or more scholarship recommendations (name,
-- university, and other details) to a specific Scholarship Support request.
-- Recommendations are visible to the admin (in /admin/scholarship-support)
-- and to the applicant who submitted the request (in
-- /account/scholarship-support) — nobody else.
create table if not exists public.scholarship_recommendations (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.contact_messages(id) on delete cascade,
  scholarship_name text not null check (char_length(scholarship_name) between 2 and 200),
  university text not null check (char_length(university) between 2 and 200),
  degree_level text check (degree_level is null or char_length(degree_level) <= 60),
  country text check (country is null or char_length(country) <= 100),
  deadline date,
  link text check (link is null or char_length(link) <= 500),
  notes text check (notes is null or char_length(notes) <= 2000),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists scholarship_recommendations_request_id_idx
  on public.scholarship_recommendations(request_id, created_at desc);

alter table public.scholarship_recommendations enable row level security;

drop policy if exists "Admins can manage scholarship recommendations"
  on public.scholarship_recommendations;
create policy "Admins can manage scholarship recommendations"
on public.scholarship_recommendations
for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "Applicants can read their own recommendations"
  on public.scholarship_recommendations;
create policy "Applicants can read their own recommendations"
on public.scholarship_recommendations
for select
to authenticated
using (
  exists (
    select 1 from public.contact_messages
    where contact_messages.id = scholarship_recommendations.request_id
      and contact_messages.user_id = (select auth.uid())
  )
);

grant select, insert, update, delete on table public.scholarship_recommendations to authenticated;
grant usage, select on sequence public.scholarship_recommendations_id_seq to authenticated;

comment on table public.scholarship_recommendations is
  'Admin-authored scholarship recommendations attached to a Scholarship Support request, visible to the admin and to the applicant who submitted the request.';
