-- Stores submissions from the "Personalized scholarship navigator" modal
-- (src/components/scholarship-profile-modal.tsx) so admins can see who asked
-- for a personalized shortlist, and lets the server send an account-setup
-- invite email when the submitted address has no existing account.
create table if not exists public.scholarship_navigator_profiles (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 80),
  email text not null check (char_length(email) between 5 and 254),
  current_country text not null check (char_length(current_country) between 2 and 80),
  target_country text not null check (target_country in ('usa', 'canada', 'korea', 'switzerland', 'italy', 'japan')),
  degree text not null check (degree in ('masters', 'phd')),
  research_interest text not null check (char_length(research_interest) between 2 and 120),
  ielts_status text not null check (ielts_status in ('planning', 'booked', 'completed', 'waiver')),
  ielts_score text,
  other_information text,
  invite_sent boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists scholarship_navigator_profiles_created_at_idx
  on public.scholarship_navigator_profiles(created_at desc);

alter table public.scholarship_navigator_profiles enable row level security;

drop policy if exists "Anyone can submit a scholarship navigator profile"
  on public.scholarship_navigator_profiles;
create policy "Anyone can submit a scholarship navigator profile"
on public.scholarship_navigator_profiles
for insert
to anon, authenticated
with check (true);

drop policy if exists "Admins can read scholarship navigator profiles"
  on public.scholarship_navigator_profiles;
create policy "Admins can read scholarship navigator profiles"
on public.scholarship_navigator_profiles
for select
to authenticated
using ((select public.is_admin()));

grant insert on table public.scholarship_navigator_profiles to anon, authenticated;
grant select on table public.scholarship_navigator_profiles to authenticated;
grant usage, select on sequence public.scholarship_navigator_profiles_id_seq
  to anon, authenticated;

comment on table public.scholarship_navigator_profiles is
  'Submissions from the personalized scholarship navigator modal on /scholarships. Visitors can insert only; administrators can read.';
