-- Links scholarship navigator profiles to the submitting account (when
-- logged in) and adds the bookkeeping needed for a weekly personalized
-- scholarship-pick email, sent by a Vercel Cron job hitting
-- /api/cron/weekly-digest.

-- 1. Link navigator profiles to the submitting account, when logged in.
alter table public.scholarship_navigator_profiles
  add column if not exists user_id uuid references auth.users(id) on delete set null;

drop policy if exists "Anyone can submit a scholarship navigator profile"
  on public.scholarship_navigator_profiles;
create policy "Anyone can submit a scholarship navigator profile"
on public.scholarship_navigator_profiles
for insert
to anon, authenticated
with check (
  user_id is null or user_id = (select auth.uid())
);

-- 2. Let a user opt out of the weekly digest (checked before every send).
alter table public.profiles
  add column if not exists weekly_digest_opt_out boolean not null default false;

-- 3. Track which scholarship slug was already emailed to which user, so the
--    digest never repeats a pick and knows what to send next.
create table if not exists public.weekly_digest_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  scholarship_slug text not null,
  sent_at timestamptz not null default now(),
  unique (user_id, scholarship_slug)
);

alter table public.weekly_digest_log enable row level security;
-- No anon/authenticated policies on purpose: this table is only ever read or
-- written by the cron route's service-role client, which bypasses RLS.

comment on table public.weekly_digest_log is
  'One row per (user, scholarship) pair already sent in the weekly personalized digest, so the cron job never repeats a pick. Written only by the service-role cron route.';
comment on column public.profiles.weekly_digest_opt_out is
  'When true, the weekly personalized scholarship digest skips this user.';
