-- Scholarship Support requests only ever supported one admin reply per
-- request (contact_messages.admin_reply/replied_at), delivered by email with
-- no way for the applicant to reply back through the site. This table adds a
-- simple two-way thread of follow-up messages per request: the admin can add
-- more than one reply, and the applicant can send follow-ups of their own.
-- The original admin_reply/replied_at columns are left untouched for
-- backward compatibility with requests that were already replied to before
-- this table existed.
create table if not exists public.contact_message_replies (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.contact_messages(id) on delete cascade,
  sender text not null check (sender in ('admin', 'user')),
  message text not null check (char_length(message) between 1 and 4000),
  created_at timestamptz not null default now()
);

create index if not exists contact_message_replies_request_id_idx
  on public.contact_message_replies(request_id, created_at);

alter table public.contact_message_replies enable row level security;

drop policy if exists "Owners and admins can read replies"
  on public.contact_message_replies;
create policy "Owners and admins can read replies"
on public.contact_message_replies
for select
to authenticated
using (
  (select public.is_admin())
  or exists (
    select 1 from public.contact_messages cm
    where cm.id = request_id and cm.user_id = (select auth.uid())
  )
);

drop policy if exists "Owners can add their own follow-up"
  on public.contact_message_replies;
create policy "Owners can add their own follow-up"
on public.contact_message_replies
for insert
to authenticated
with check (
  sender = 'user'
  and exists (
    select 1 from public.contact_messages cm
    where cm.id = request_id and cm.user_id = (select auth.uid())
  )
);

drop policy if exists "Admins can add replies"
  on public.contact_message_replies;
create policy "Admins can add replies"
on public.contact_message_replies
for insert
to authenticated
with check (
  sender = 'admin' and (select public.is_admin())
);

grant select, insert on table public.contact_message_replies to authenticated;
grant usage, select on sequence public.contact_message_replies_id_seq
  to authenticated;

comment on table public.contact_message_replies is
  'Follow-up messages on a contact_messages request, after the initial admin_reply. Applicants can add their own (sender=''user''); admins can add more (sender=''admin'').';
