create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('page_view', 'click')),
  path text not null check (char_length(path) between 1 and 500),
  target text check (target is null or char_length(target) <= 500),
  label text check (label is null or char_length(label) <= 160),
  referrer text check (referrer is null or char_length(referrer) <= 500),
  session_id uuid not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_created_at_idx
  on public.analytics_events(created_at desc);

create index if not exists analytics_events_type_path_idx
  on public.analytics_events(event_type, path);

create index if not exists analytics_events_session_idx
  on public.analytics_events(session_id, created_at desc);

alter table public.analytics_events enable row level security;

drop policy if exists "Visitors can submit analytics events"
  on public.analytics_events;
create policy "Visitors can submit analytics events"
on public.analytics_events
for insert
to anon, authenticated
with check (
  event_type in ('page_view', 'click')
  and path like '/%'
  and jsonb_typeof(metadata) = 'object'
);

drop policy if exists "Admins can read analytics events"
  on public.analytics_events;
create policy "Admins can read analytics events"
on public.analytics_events
for select
to authenticated
using ((select public.is_admin()));

grant insert on table public.analytics_events to anon, authenticated;
grant select on table public.analytics_events to authenticated;
grant usage, select on sequence public.analytics_events_id_seq
  to anon, authenticated;

comment on table public.analytics_events is
  'Privacy-safe first-party page-view and click analytics. Does not store IP addresses, form values, or user credentials.';
