create table if not exists public.lecture_materials (
  id bigint generated by default as identity primary key,
  lecture_id bigint not null references public.lectures(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 160),
  file_url text not null,
  storage_path text,
  file_type text,
  file_size bigint check (file_size is null or file_size >= 0),
  position integer not null default 0 check (position >= 0),
  created_at timestamptz not null default now()
);

create index if not exists lecture_materials_lecture_position_idx
  on public.lecture_materials(lecture_id, position, id);

alter table public.lecture_materials enable row level security;

create policy "Published lecture materials are publicly readable"
on public.lecture_materials for select to anon, authenticated
using (
  exists (
    select 1 from public.lectures
    join public.course_sections on course_sections.id = lectures.section_id
    join public.courses on courses.id = course_sections.course_id
    where lectures.id = lecture_materials.lecture_id
      and courses.published = true
  )
  or (select public.is_admin())
);

create policy "Admins manage lecture materials"
on public.lecture_materials for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

grant select on public.lecture_materials to anon, authenticated;
grant insert, update, delete on public.lecture_materials to authenticated;
grant usage, select on sequence public.lecture_materials_id_seq to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'course-materials',
  'course-materials',
  true,
  3145728,
  array[
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/zip',
    'text/plain'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can download course materials" on storage.objects;
create policy "Public can download course materials"
on storage.objects for select to anon, authenticated
using (bucket_id = 'course-materials');

drop policy if exists "Admins can upload course materials" on storage.objects;
create policy "Admins can upload course materials"
on storage.objects for insert to authenticated
with check (bucket_id = 'course-materials' and (select public.is_admin()));

drop policy if exists "Admins can update course materials" on storage.objects;
create policy "Admins can update course materials"
on storage.objects for update to authenticated
using (bucket_id = 'course-materials' and (select public.is_admin()))
with check (bucket_id = 'course-materials' and (select public.is_admin()));

drop policy if exists "Admins can delete course materials" on storage.objects;
create policy "Admins can delete course materials"
on storage.objects for delete to authenticated
using (bucket_id = 'course-materials' and (select public.is_admin()));

comment on table public.lecture_materials is
  'Downloadable files and external resources attached to Academy lectures.';
