create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null default auth.uid(),
  name text not null check (char_length(name) between 2 and 80),
  email text not null check (char_length(email) between 5 and 254),
  topic text not null check (topic in ('general', 'academy', 'engineering', 'research', 'career', 'collaboration')),
  subject text not null check (char_length(subject) between 3 and 120),
  message text not null check (char_length(message) between 10 and 2000),
  status text not null default 'new' check (status in ('new', 'read', 'replied')),
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists contact_messages_created_at_idx
  on public.contact_messages(created_at desc);

create index if not exists contact_messages_status_idx
  on public.contact_messages(status, created_at desc);

alter table public.contact_messages enable row level security;

drop policy if exists "Visitors can send contact messages"
  on public.contact_messages;
create policy "Visitors can send contact messages"
on public.contact_messages
for insert
to anon, authenticated
with check (
  status = 'new'
  and is_read = false
  and (user_id is null or user_id = (select auth.uid()))
);

drop policy if exists "Admins can read contact messages"
  on public.contact_messages;
create policy "Admins can read contact messages"
on public.contact_messages
for select
to authenticated
using ((select public.is_admin()));

drop policy if exists "Admins can update contact messages"
  on public.contact_messages;
create policy "Admins can update contact messages"
on public.contact_messages
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

grant insert on table public.contact_messages to anon, authenticated;
grant select, update on table public.contact_messages to authenticated;
grant usage, select on sequence public.contact_messages_id_seq
  to anon, authenticated;

comment on table public.contact_messages is
  'Messages submitted through the public contact form. Visitors can insert only; administrators can read and manage them.';
