create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  title text not null check (char_length(title) between 1 and 160),
  subtitle text,
  description text,
  category text not null default 'General',
  level text not null default 'Beginner',
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.course_sections (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 160),
  position integer not null default 0 check (position >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.lectures (
  id bigint generated by default as identity primary key,
  section_id bigint not null references public.course_sections(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 200),
  lecture_type text not null default 'video' check (lecture_type in ('video', 'reading', 'quiz')),
  duration text,
  video_url text,
  content text,
  position integer not null default 0 check (position >= 0),
  is_preview boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists course_sections_course_position_idx
  on public.course_sections(course_id, position, id);
create index if not exists lectures_section_position_idx
  on public.lectures(section_id, position, id);

alter table public.courses enable row level security;
alter table public.course_sections enable row level security;
alter table public.lectures enable row level security;

create policy "Published courses are publicly readable" on public.courses
for select to anon, authenticated
using (published = true or (select public.is_admin()));

create policy "Published course sections are publicly readable" on public.course_sections
for select to anon, authenticated
using (
  exists (select 1 from public.courses where courses.id = course_sections.course_id and courses.published = true)
  or (select public.is_admin())
);

create policy "Published lectures are publicly readable" on public.lectures
for select to anon, authenticated
using (
  exists (
    select 1 from public.course_sections
    join public.courses on courses.id = course_sections.course_id
    where course_sections.id = lectures.section_id and courses.published = true
  )
  or (select public.is_admin())
);

create policy "Admins manage courses" on public.courses
for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
create policy "Admins manage course sections" on public.course_sections
for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
create policy "Admins manage lectures" on public.lectures
for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));

grant select on public.courses, public.course_sections, public.lectures to anon, authenticated;
grant insert, update, delete on public.courses, public.course_sections, public.lectures to authenticated;
grant usage, select on sequence public.courses_id_seq, public.course_sections_id_seq, public.lectures_id_seq to authenticated;

drop trigger if exists courses_set_updated_at on public.courses;
create trigger courses_set_updated_at before update on public.courses
for each row execute function public.set_updated_at();
drop trigger if exists lectures_set_updated_at on public.lectures;
create trigger lectures_set_updated_at before update on public.lectures
for each row execute function public.set_updated_at();

comment on table public.courses is 'Academy courses managed from the admin dashboard.';
comment on table public.course_sections is 'Ordered curriculum sections belonging to courses.';
comment on table public.lectures is 'Video, reading, and quiz lessons belonging to course sections.';
